"""Shared build/version metadata for diagnostics and MCP config output."""

from __future__ import annotations

import hashlib
import os
import shutil
import sys

try:
    from . import blender_compat, tool_registry
except ImportError:  # Allows direct imports from addon/claude_blender.
    import blender_compat
    import tool_registry


ADDON_ID = "claude_blender"
ADDON_NAME = "Blender Agent Bridge"
ADDON_VERSION_TUPLE = (0, 4, 0)
ADDON_VERSION = "0.4.0"
BLENDER_VERSION_MIN_TUPLE = blender_compat.MINIMUM_VERSION
BLENDER_VERSION_MIN = blender_compat.MINIMUM_VERSION_TEXT
BRIDGE_VERSION = "0.3"
MCP_SERVER_VERSION = "0.4.0"
MCP_CONFIG_VERSION = "3"
MCP_RUNTIME_BUNDLED = "bundled"
MCP_RUNTIME_UVX = "uvx"
MCP_RUNTIME_MODES = {MCP_RUNTIME_BUNDLED, MCP_RUNTIME_UVX}
MCP_DISTRIBUTION_NAME = "blender-bridge"
MCP_CONSOLE_COMMAND = "blender-bridge"
TOOL_REGISTRY_DIGEST = tool_registry.TOOL_REGISTRY_DIGEST

MCP_CONFIG_NOTE = (
    "Generated by Blender Agent Bridge; refresh or restart the MCP client after replacing this config."
)
EXTERNAL_AUTH_ENV_NOTE = (
    "Poly Haven needs no API key. Sketchfab downloads read SKETCHFAB_API_TOKEN or "
    "BLENDER_AGENT_BRIDGE_SKETCHFAB_API_TOKEN from this MCP server config; refresh or restart "
    "the MCP client after changing env values."
)
SOURCE_HASH_EXTENSIONS = (".py", ".toml")
SOURCE_HASH_EXCLUDES = {"__pycache__", ".git", ".mypy_cache", ".pytest_cache"}


def addon_root():
    return os.path.dirname(os.path.abspath(__file__))


def mcp_server_path():
    return os.path.join(addon_root(), "mcp_server.py")


def source_tree_hash(root=None):
    root = os.path.abspath(root or addon_root())
    digest = hashlib.sha256()
    for current_root, dirnames, filenames in os.walk(root):
        dirnames[:] = [name for name in sorted(dirnames) if name not in SOURCE_HASH_EXCLUDES]
        for filename in sorted(filenames):
            if not filename.endswith(SOURCE_HASH_EXTENSIONS):
                continue
            path = os.path.join(current_root, filename)
            relpath = os.path.relpath(path, root).replace(os.sep, "/")
            digest.update(relpath.encode("utf-8"))
            digest.update(b"\0")
            try:
                with open(path, "rb") as handle:
                    for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                        digest.update(chunk)
            except OSError:
                digest.update(b"<unreadable>")
            digest.update(b"\0")
    return digest.hexdigest()


LOADED_SOURCE_HASH = source_tree_hash()


def expected_source_hash_from_env():
    return str(os.environ.get("CLAUDE_BLENDER_ADDON_SOURCE_HASH") or "").strip()


def expected_tool_registry_digest_from_env():
    return str(os.environ.get("CLAUDE_BLENDER_TOOL_REGISTRY_DIGEST") or "").strip()


def mcp_runtime_mode_from_env():
    value = str(os.environ.get("CLAUDE_BLENDER_MCP_RUNTIME_MODE") or MCP_RUNTIME_BUNDLED).strip().lower()
    return value if value in MCP_RUNTIME_MODES else MCP_RUNTIME_BUNDLED


def normalize_mcp_runtime_mode(value):
    normalized = str(value or MCP_RUNTIME_BUNDLED).strip().lower()
    if normalized not in MCP_RUNTIME_MODES:
        raise ValueError(f"Unsupported MCP runtime mode: {value!r}")
    return normalized


def uvx_executable():
    return str(shutil.which("uvx") or "")


def _is_python_executable_name(path):
    name = os.path.basename(str(path or "")).lower()
    if name.endswith(".exe"):
        name = name[:-4]
    if name == "python":
        return True
    if not name.startswith("python3"):
        return False
    version_suffix = name[len("python3") :]
    return not version_suffix or all(character.isdigit() or character == "." for character in version_suffix)


def bundled_python_executable(*, executable=None, prefix=None):
    """Return Blender's bundled Python command, with a PATH fallback for older builds."""

    candidates = [str(executable if executable is not None else sys.executable or "")]
    python_prefix = os.path.abspath(str(prefix if prefix is not None else sys.prefix or ""))
    bin_dir = os.path.join(python_prefix, "bin")
    try:
        candidates.extend(os.path.join(bin_dir, name) for name in sorted(os.listdir(bin_dir), reverse=True))
    except OSError:
        pass
    candidates.append(os.path.join(python_prefix, "python.exe"))

    seen = set()
    for candidate in candidates:
        candidate = os.path.abspath(candidate) if candidate else ""
        normalized = os.path.normcase(candidate)
        if not candidate or normalized in seen:
            continue
        seen.add(normalized)
        executable_file = os.path.isfile(candidate) and (os.name == "nt" or os.access(candidate, os.X_OK))
        if _is_python_executable_name(candidate) and executable_file:
            return candidate
    return "python"


def source_hash_status(actual_hash=None, expected_hash=None):
    actual = str(actual_hash or source_tree_hash()).strip()
    expected = str(expected_hash if expected_hash is not None else expected_source_hash_from_env()).strip()
    if not expected:
        return {
            "actual": actual,
            "expected": "",
            "match": None,
            "status": "not_provided",
            "message": "No expected add-on source hash was provided by the MCP config environment.",
        }
    match = actual == expected
    return {
        "actual": actual,
        "expected": expected,
        "match": match,
        "status": "match" if match else "mismatch",
        "message": "Add-on source hash matches MCP config." if match else "Add-on source hash differs from MCP config.",
    }


def mcp_config_env(token="", sketchfab_api_token="", *, launch_mode=MCP_RUNTIME_BUNDLED):
    launch_mode = normalize_mcp_runtime_mode(launch_mode)
    source_hash = source_tree_hash()
    env = {
        "CLAUDE_BLENDER_ADDON_ID": ADDON_ID,
        "CLAUDE_BLENDER_ADDON_VERSION": ADDON_VERSION,
        "CLAUDE_BLENDER_ADDON_SOURCE_HASH": source_hash,
        "CLAUDE_BLENDER_BRIDGE_VERSION": BRIDGE_VERSION,
        "CLAUDE_BLENDER_MCP_SERVER_VERSION": MCP_SERVER_VERSION,
        "CLAUDE_BLENDER_MCP_CONFIG_VERSION": MCP_CONFIG_VERSION,
        "CLAUDE_BLENDER_MCP_CONFIG_NOTE": MCP_CONFIG_NOTE,
        "CLAUDE_BLENDER_MCP_RUNTIME_MODE": launch_mode,
        "CLAUDE_BLENDER_TOOL_REGISTRY_DIGEST": TOOL_REGISTRY_DIGEST,
        "BLENDER_AGENT_BRIDGE_EXTERNAL_AUTH_NOTE": EXTERNAL_AUTH_ENV_NOTE,
        "SKETCHFAB_API_TOKEN": str(sketchfab_api_token or ""),
    }
    if token:
        env["BLENDER_BRIDGE_TOKEN"] = str(token)
    return env


def mcp_launch_command(*, launch_mode=MCP_RUNTIME_BUNDLED, platform_name=None, command=""):
    launch_mode = normalize_mcp_runtime_mode(launch_mode)
    if launch_mode == MCP_RUNTIME_BUNDLED:
        return str(command or "python"), [mcp_server_path()]
    package_spec = f"{MCP_DISTRIBUTION_NAME}=={MCP_SERVER_VERSION}"
    args = ["--from", package_spec, MCP_CONSOLE_COMMAND]
    current_platform = str(platform_name or os.name).strip().lower()
    if current_platform in {"nt", "windows", "win32"}:
        return "cmd", ["/c", "uvx", *args]
    return "uvx", args


def mcp_config(
    bridge_url,
    *,
    token="",
    sketchfab_api_token="",
    command="",
    launch_mode=MCP_RUNTIME_BUNDLED,
    platform_name=None,
):
    launch_mode = normalize_mcp_runtime_mode(launch_mode)
    launch_command, launch_args = mcp_launch_command(
        launch_mode=launch_mode,
        platform_name=platform_name,
        command=command,
    )
    return {
        "mcpServers": {
            "blender": {
                "command": launch_command,
                "args": [
                    *launch_args,
                    "--bridge-url",
                    str(bridge_url or ""),
                ],
                "env": mcp_config_env(token, sketchfab_api_token, launch_mode=launch_mode),
            }
        }
    }


def diagnostics_dict(*, bridge_url="", blender_version=""):
    source_hash = source_tree_hash()
    runtime_source_stale = bool(LOADED_SOURCE_HASH and LOADED_SOURCE_HASH != source_hash)
    hash_status = source_hash_status(source_hash)
    compatibility = blender_compat.compatibility_report(blender_version) if blender_version else {}
    reload_guidance = (
        "Save the current file, then use Reload Scripts (F3) or restart Blender before testing the patched add-on."
    )
    return {
        "addon_id": ADDON_ID,
        "addon_name": ADDON_NAME,
        "addon_version": ADDON_VERSION,
        "addon_path": addon_root(),
        "addon_source_hash": source_hash,
        "addon_loaded_source_hash": LOADED_SOURCE_HASH,
        "addon_runtime_source_stale": runtime_source_stale,
        "addon_runtime_source_status": "stale" if runtime_source_stale else "current",
        "addon_runtime_source_message": (
            f"Add-on files changed on disk after these Python modules loaded. {reload_guidance}"
            if runtime_source_stale
            else "Loaded add-on modules match the files currently on disk."
        ),
        "addon_reload_required": runtime_source_stale,
        "addon_reload_guidance": reload_guidance,
        "expected_addon_source_hash": hash_status["expected"],
        "addon_source_hash_match": hash_status["match"],
        "addon_source_hash_status": hash_status["status"],
        "addon_source_hash_message": hash_status["message"],
        "blender_version_min": BLENDER_VERSION_MIN,
        "blender_version": str(blender_version or ""),
        "blender_compatibility": compatibility,
        "bridge_version": BRIDGE_VERSION,
        "bridge_url": str(bridge_url or ""),
        "mcp_server_version": MCP_SERVER_VERSION,
        "mcp_server_path": mcp_server_path(),
        "mcp_config_version": MCP_CONFIG_VERSION,
        "mcp_runtime_mode": mcp_runtime_mode_from_env(),
        "tool_registry_digest": TOOL_REGISTRY_DIGEST,
        "expected_tool_registry_digest": expected_tool_registry_digest_from_env(),
    }


def diagnostics_summary(diagnostics=None):
    diagnostics = diagnostics if diagnostics is not None else diagnostics_dict()
    source_hash = str(diagnostics["addon_source_hash"])[:12]
    runtime_note = " | Runtime stale" if diagnostics["addon_runtime_source_stale"] else ""
    return (
        f"{ADDON_NAME} {ADDON_VERSION} | "
        f"Bridge {BRIDGE_VERSION} | MCP {MCP_SERVER_VERSION} | Config {MCP_CONFIG_VERSION} | "
        f"Registry {TOOL_REGISTRY_DIGEST[:12]} | Source {source_hash}"
        f"{runtime_note}"
    )
