"""Canonical tool specifications for the animation domain."""

from __future__ import annotations

from ..registry import ToolSpec


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'get_animation_details',
  'description': 'Fetch read-only scene, object, action, f-curve, and keyframe details for animation planning.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array',
                                                   'items': {'type': 'string'},
                                                   'description': 'Optional object names whose actions should be '
                                                                  'inspected'},
                                  'action_names': {'type': 'array',
                                                   'items': {'type': 'string'},
                                                   'description': 'Optional action names to inspect'},
                                  'max_actions': {'type': 'integer', 'description': 'Maximum actions to return'},
                                  'max_keyframes_per_curve': {'type': 'integer',
                                                              'description': 'Maximum keyframes to show per f-curve'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return scene timeline, action, f-curve, and keyframe details', 'mutates_scene': False},
  'handler_key': 'get_animation_details',
  'order': 220,
  'groups': ('animation',),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'get_animation_scene_context',
  'description': 'Build read-only animation-aware scene context that identifies likely edit targets, rig-driven '
                 'objects, rig control candidates, shape keys, constraints, drivers, NLA, physics/simulation hints, '
                 'contact surfaces, camera readiness, hardening risk flags, required pre-mutation inspections, and '
                 'recommended deeper inspection/review tools.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array',
                                                   'items': {'type': 'string'},
                                                   'description': 'Optional objects to inspect. Defaults to the scene '
                                                                  'unless selected_only is true.'},
                                  'selected_only': {'type': 'boolean',
                                                    'description': 'Inspect only selected objects when object_names is '
                                                                   'empty.'},
                                  'max_objects': {'type': 'integer', 'description': 'Maximum objects to summarize.'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return animation-aware routing and hardening context for rigs, control candidates, '
                              'shape keys, physics, materials, cameras, contact surfaces, likely edit targets, and '
                              'required pre-mutation inspections',
               'mutates_scene': False},
  'handler_key': 'get_animation_scene_context',
  'order': 230,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_animation_brief',
  'description': 'Create a structured animation prompt contract with subjects, action, timing, assumptions, '
                 'ambiguities, success criteria, and validation checks. Does not mutate the scene.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string',
                                             'description': "The user's animation request or concise animation intent "
                                                            'to formalize.'},
                                  'subject_names': {'type': 'array',
                                                    'items': {'type': 'string'},
                                                    'description': 'Optional existing Blender object names to treat as '
                                                                   'animated subjects. Defaults to the current '
                                                                   'selection.'},
                                  'action': {'type': 'string',
                                             'description': 'Optional explicit primary action if the prompt is '
                                                            'ambiguous.'},
                                  'style': {'type': 'string',
                                            'description': 'Optional style/read such as playful, heavy, snappy, or '
                                                           'cinematic.'},
                                  'camera': {'type': 'string',
                                             'description': 'Optional camera name or framing requirement.'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'constraints': {'type': 'array', 'items': {'type': 'string'}},
                                  'success_criteria': {'type': 'array', 'items': {'type': 'string'}}},
                   'required': ['prompt'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a structured animation prompt contract from the user brief and scene context',
               'mutates_scene': False},
  'handler_key': 'create_animation_brief',
  'order': 240,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_timing_chart',
  'description': 'Create a read-only animator-style timing chart from a prompt or animation brief, with key poses, '
                 'contacts, holds, breakdowns, and spacing notes.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string'},
                                  'brief': {'type': 'object'},
                                  'subject_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'beats': {'type': 'array',
                                            'items': {'type': 'object',
                                                      'properties': {'frame': {'type': 'integer'},
                                                                     'label': {'type': 'string'},
                                                                     'role': {'type': 'string'},
                                                                     'hold_frames': {'type': 'integer'},
                                                                     'notes': {'type': 'array',
                                                                               'items': {'type': 'string'}}},
                                                      'additionalProperties': False}}},
                   'additionalProperties': False},
  'contract': {'description': 'Create a structured timing/blocking chart from an animation brief',
               'mutates_scene': False},
  'handler_key': 'create_timing_chart',
  'order': 250,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'plan_animation_workflow',
  'description': 'Plan the Milestone 7 animation workflow for generation, review, or repair. Returns a brief, '
                 'animation-aware scene context, timing chart, ordered helper/evaluator/repair tool calls, and '
                 'explicit draft_script fallback rules. Does not mutate the scene.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string',
                                             'description': "The user's animation generation, review, or repair "
                                                            'request.'},
                                  'subject_names': {'type': 'array',
                                                    'items': {'type': 'string'},
                                                    'description': 'Optional existing Blender object names to treat as '
                                                                   'animated subjects.'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'mode': {'type': 'string',
                                           'enum': ['generate', 'review', 'repair', 'full'],
                                           'description': 'Workflow focus. full includes generation and validation '
                                                          'guidance.'},
                                  'selected_only': {'type': 'boolean'},
                                  'max_objects': {'type': 'integer'},
                                  'brief': {'type': 'object', 'description': 'Optional existing animation brief.'},
                                  'timing_chart': {'type': 'object', 'description': 'Optional existing timing chart.'},
                                  'playblast': {'type': 'object',
                                                'description': 'Optional existing playblast metadata.'},
                                  'findings': {'type': 'array',
                                               'items': {'type': 'object'},
                                               'description': 'Optional evaluator findings to plan repair calls.'}},
                   'required': ['prompt'],
                   'additionalProperties': False},
  'contract': {'description': 'Plan the Milestone 7 animation workflow with brief, scene routing, timing chart, helper '
                              'calls, evaluator calls, repair calls, and script fallback rules',
               'mutates_scene': False,
               'input_schema': {'type': 'object',
                                'properties': {'prompt': {'type': 'string'},
                                               'subject_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'frame_start': {'type': 'integer'},
                                               'frame_end': {'type': 'integer'},
                                               'mode': {'type': 'string',
                                                        'enum': ['generate', 'review', 'repair', 'full']},
                                               'selected_only': {'type': 'boolean'},
                                               'max_objects': {'type': 'integer'},
                                               'brief': {'type': 'object'},
                                               'timing_chart': {'type': 'object'},
                                               'playblast': {'type': 'object'},
                                               'findings': {'type': 'array', 'items': {'type': 'object'}}},
                                'required': ['prompt'],
                                'additionalProperties': False}},
  'handler_key': 'plan_animation_workflow',
  'order': 260,
  'groups': ('animation', 'advanced_workflow'),
  'exposure': 'compact_direct',
  'owner': 'animation'},
 {'name': 'run_animation_workflow',
  'description': 'Execute the Milestone 7 helper-backed animation workflow for common requests, then run structured '
                 'review and optional bounded repair. May leave live preview changes pending for commit/revert.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string',
                                             'description': "The user's animation generation, review, or repair "
                                                            'request.'},
                                  'subject_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'mode': {'type': 'string', 'enum': ['generate', 'review', 'repair', 'full']},
                                  'selected_only': {'type': 'boolean'},
                                  'max_objects': {'type': 'integer'},
                                  'brief': {'type': 'object'},
                                  'timing_chart': {'type': 'object'},
                                  'playblast': {'type': 'object'},
                                  'findings': {'type': 'array', 'items': {'type': 'object'}},
                                  'apply_generation': {'type': 'boolean',
                                                       'description': 'Whether to execute allowlisted generation '
                                                                      'helpers from the workflow. Defaults to true.'},
                                  'run_review': {'type': 'boolean',
                                                 'description': 'Whether to run structured evaluator review after '
                                                                'generation. Defaults to true.'},
                                  'capture_playblast': {'type': 'boolean',
                                                        'description': 'Whether to request sampled viewport frames '
                                                                       'during review. Defaults to false for '
                                                                       'headless-safe use.'},
                                  'apply_repairs': {'type': 'boolean',
                                                    'description': 'Whether to execute bounded repair operations from '
                                                                   'evaluator findings. Defaults to false.'},
                                  'max_generation_steps': {'type': 'integer'},
                                  'max_repair_iterations': {'type': 'integer'},
                                  'max_repair_operations': {'type': 'integer'},
                                  'recapture_after_repair': {'type': 'boolean'}},
                   'required': ['prompt'],
                   'additionalProperties': False},
  'contract': {'description': 'Execute a helper-backed Milestone 7 animation workflow, run structured review, and '
                              'optionally apply bounded repair operations while leaving changes in preview',
               'mutates_scene': True,
               'long_running': True,
               'duration_hint': 'Usually seconds for helper-only animation; can take longer when capture_playblast or '
                                'repair recapture is enabled.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'message': 'If the client times out, wait briefly, check bridge status, then '
                                               'inspect visual evidence resources and audit logs before rerunning.'},
               'input_schema': {'type': 'object',
                                'properties': {'prompt': {'type': 'string'},
                                               'subject_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'frame_start': {'type': 'integer'},
                                               'frame_end': {'type': 'integer'},
                                               'mode': {'type': 'string',
                                                        'enum': ['generate', 'review', 'repair', 'full']},
                                               'selected_only': {'type': 'boolean'},
                                               'max_objects': {'type': 'integer'},
                                               'brief': {'type': 'object'},
                                               'timing_chart': {'type': 'object'},
                                               'playblast': {'type': 'object'},
                                               'findings': {'type': 'array', 'items': {'type': 'object'}},
                                               'apply_generation': {'type': 'boolean'},
                                               'run_review': {'type': 'boolean'},
                                               'capture_playblast': {'type': 'boolean'},
                                               'apply_repairs': {'type': 'boolean'},
                                               'max_generation_steps': {'type': 'integer'},
                                               'max_repair_iterations': {'type': 'integer'},
                                               'max_repair_operations': {'type': 'integer'},
                                               'recapture_after_repair': {'type': 'boolean'}},
                                'required': ['prompt'],
                                'additionalProperties': False}},
  'handler_key': 'run_animation_workflow',
  'order': 270,
  'groups': ('animation', 'deep_inspect', 'advanced_create', 'advanced_workflow'),
  'exposure': 'compact_direct',
  'owner': 'animation'},
 {'name': 'run_animation_task',
  'description': 'One-input animation entry point for MCP clients. Routes the prompt through the Milestone 7 '
                 'planner/runner workflow before any draft_script fallback.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string',
                                             'description': "The user's animation generation, review, or repair "
                                                            'request.'}},
                   'required': ['prompt'],
                   'additionalProperties': False},
  'contract': {'description': 'One-input animation task wrapper that routes the prompt through the Milestone 7 '
                              'planner/runner workflow before any script fallback',
               'mutates_scene': True,
               'long_running': True,
               'duration_hint': 'Usually seconds for helper-backed animation; can take longer when the workflow '
                                'captures or reviews visual evidence.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'message': 'If the client times out, wait briefly, check bridge status, then '
                                               'inspect visual evidence resources and audit logs before rerunning.'},
               'input_schema': {'type': 'object',
                                'properties': {'prompt': {'type': 'string'}},
                                'required': ['prompt'],
                                'additionalProperties': False}},
  'handler_key': 'run_animation_task',
  'order': 280,
  'groups': ('animation', 'deep_inspect', 'advanced_create'),
  'exposure': 'compact_direct',
  'owner': 'animation'},
 {'name': 'analyze_motion_arcs',
  'description': 'Read-only analysis of sampled keyed location motion arcs for selected or named objects.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'max_samples': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Analyze sampled location motion arcs for selected or named objects',
               'mutates_scene': False},
  'handler_key': 'analyze_motion_arcs',
  'order': 290,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'analyze_fcurve_spacing',
  'description': 'Read-only analysis of transform key spacing, segment distances, and interpolation choices.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'paths': {'type': 'array',
                                            'items': {'type': 'string',
                                                      'enum': ['location', 'rotation_euler', 'scale']}}},
                   'additionalProperties': False},
  'contract': {'description': 'Analyze transform key spacing and interpolation for selected or named objects',
               'mutates_scene': False},
  'handler_key': 'analyze_fcurve_spacing',
  'order': 300,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'analyze_pose_clarity',
  'description': 'Read-only analysis of keyed pose count, transform readability, and detected holds.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'}},
                   'additionalProperties': False},
  'contract': {'description': 'Analyze keyed pose count, holds, and transform readability', 'mutates_scene': False},
  'handler_key': 'analyze_pose_clarity',
  'order': 310,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'analyze_animation_principles',
  'description': 'Evaluate keyed animation against core animation principles and the prompt contract. Returns '
                 'structured findings that can feed repair.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'prompt': {'type': 'string'},
                                  'brief': {'type': 'object'},
                                  'timing_chart': {'type': 'object'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Evaluate animation data against animator principles and the prompt contract',
               'mutates_scene': False},
  'handler_key': 'analyze_animation_principles',
  'order': 320,
  'groups': ('animation', 'deep_inspect', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'sample_animation_state',
  'description': 'Sample selected or named object transforms across an animation range for objective review.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'sample_step': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Sample object transform state across an animation range', 'mutates_scene': False},
  'handler_key': 'sample_animation_state',
  'order': 330,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'analyze_contact_sliding',
  'description': 'Detect sliding while animated object bounds are near a contact plane.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'sample_step': {'type': 'integer'},
                                  'contact_z': {'type': 'number'},
                                  'contact_tolerance': {'type': 'number'},
                                  'sliding_tolerance': {'type': 'number'}},
                   'additionalProperties': False},
  'contract': {'description': 'Detect object sliding while sampled bounding boxes are near a contact plane',
               'mutates_scene': False},
  'handler_key': 'analyze_contact_sliding',
  'order': 340,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'analyze_collision_penetration',
  'description': 'Detect sampled world bounding-box intersections between animated objects.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'sample_step': {'type': 'integer'},
                                  'tolerance': {'type': 'number'}},
                   'additionalProperties': False},
  'contract': {'description': 'Detect sampled world bounding-box intersections between animated objects',
               'mutates_scene': False},
  'handler_key': 'analyze_collision_penetration',
  'order': 350,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'analyze_center_of_mass',
  'description': 'Check sampled subject centers against support-surface footprints for balance, weight, and contact '
                 'plausibility.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'support_object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'sample_step': {'type': 'integer'},
                                  'support_margin': {'type': 'number'},
                                  'contact_tolerance': {'type': 'number'}},
                   'additionalProperties': False},
  'contract': {'description': 'Check sampled subject centers against support-surface footprints for balance and weight',
               'mutates_scene': False},
  'handler_key': 'analyze_center_of_mass',
  'order': 360,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'analyze_camera_framing',
  'description': 'Check whether animated subjects stay inside a camera-safe region.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'camera_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'sample_step': {'type': 'integer'},
                                  'margin': {'type': 'number'}},
                   'additionalProperties': False},
  'contract': {'description': 'Check whether animated subjects remain framed by the active or named camera',
               'mutates_scene': False},
  'handler_key': 'analyze_camera_framing',
  'order': 370,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'analyze_motion_physics',
  'description': 'Check sampled speed and acceleration for physically implausible spikes in Blender units.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'sample_step': {'type': 'integer'},
                                  'max_speed': {'type': 'number'},
                                  'max_acceleration': {'type': 'number'}},
                   'additionalProperties': False},
  'contract': {'description': 'Check sampled speed and acceleration for physically implausible spikes',
               'mutates_scene': False},
  'handler_key': 'analyze_motion_physics',
  'order': 380,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'compare_animation_to_brief',
  'description': 'Compare current animation samples and framing against a structured animation brief or prompt.',
  'input_schema': {'type': 'object',
                   'properties': {'brief': {'type': 'object'},
                                  'prompt': {'type': 'string'},
                                  'subject_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Compare current animation state against a structured animation brief',
               'mutates_scene': False},
  'handler_key': 'compare_animation_to_brief',
  'order': 390,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'review_playblast_against_brief',
  'description': 'Review playblast visual frame evidence, compact pixel motion evidence, and current animation state '
                 'against a prompt contract. Returns structured findings and repair_operations with executable '
                 'tool_call name/input pairs.',
  'input_schema': {'type': 'object',
                   'properties': {'playblast': {'type': 'object'},
                                  'brief': {'type': 'object'},
                                  'prompt': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Review playblast metadata, compact pixel motion evidence, and current animation state '
                              'against a prompt contract',
               'mutates_scene': False,
               'duration_hint': 'Normally a few seconds. Oversized image batches are pixel-budgeted and may skip extra '
                                'frame inspection to keep the bridge responsive.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'message': 'If review times out, wait for the bridge to become responsive, inspect '
                                               'the latest playblast metadata/audit log, and rerun with fewer or '
                                               'smaller frames if needed.'}},
  'handler_key': 'review_playblast_against_brief',
  'order': 400,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'review_inspection_renders_against_brief',
  'description': 'Review diagnostic object render evidence against a prompt contract. Returns visual-detail findings '
                 'and repair_operations, including focused recapture calls when views or image evidence are missing.',
  'input_schema': {'type': 'object',
                   'properties': {'inspection_render': {'type': 'object'},
                                  'brief': {'type': 'object'},
                                  'prompt': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Review diagnostic object render metadata and image evidence against a prompt contract',
               'mutates_scene': False,
               'duration_hint': 'Normally a few seconds. Oversized image batches are pixel-budgeted and may skip extra '
                                'image inspection to keep the bridge responsive.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'message': 'If review times out, wait for the bridge to become responsive, inspect '
                                               'the latest inspection-render metadata/audit log, and rerun with fewer '
                                               'or smaller images if needed.'}},
  'handler_key': 'review_inspection_renders_against_brief',
  'order': 410,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'repair_animation_from_findings',
  'description': 'Turn structured animation findings into focused repair operations with suggested helper tool '
                 'arguments and executable tool_call name/input pairs. Does not mutate the scene.',
  'input_schema': {'type': 'object',
                   'properties': {'findings': {'type': 'array', 'items': {'type': 'object'}},
                                  'brief': {'type': 'object'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create targeted non-mutating repair operations with executable helper tool-call '
                              'payloads',
               'mutates_scene': False},
  'handler_key': 'repair_animation_from_findings',
  'order': 420,
  'groups': ('animation', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'run_animation_repair_loop',
  'description': 'Apply a bounded set of animation repair_operations through safe helper tools, optionally recapture '
                 'playblast evidence, and re-run review_playblast_against_brief. May leave preview changes pending for '
                 'commit/revert.',
  'input_schema': {'type': 'object',
                   'properties': {'playblast': {'type': 'object'},
                                  'brief': {'type': 'object'},
                                  'prompt': {'type': 'string'},
                                  'findings': {'type': 'array', 'items': {'type': 'object'}},
                                  'repair_operations': {'type': 'array', 'items': {'type': 'object'}},
                                  'max_iterations': {'type': 'integer',
                                                     'description': 'Maximum review/repair iterations. Defaults to 2.'},
                                  'max_operations': {'type': 'integer',
                                                     'description': 'Maximum helper operations to execute. Defaults to '
                                                                    '4.'},
                                  'apply_mutating_repairs': {'type': 'boolean',
                                                             'description': 'Whether to execute preview-safe mutating '
                                                                            'repair helpers. Defaults to true.'},
                                  'recapture_after_mutation': {'type': 'boolean',
                                                               'description': 'Whether to request a fresh playblast '
                                                                              'after mutating repairs before final '
                                                                              'review. Defaults to true.'},
                                  'allowed_tools': {'type': 'array',
                                                    'items': {'type': 'string'},
                                                    'description': 'Optional allowlist of repair helper tool names for '
                                                                   'this loop.'}},
                   'additionalProperties': False},
  'contract': {'description': 'Apply bounded animation repair operations and re-run playblast/brief review',
               'mutates_scene': True,
               'long_running': True,
               'duration_hint': 'Usually seconds to a minute depending on repair count and whether playblast recapture '
                                'is enabled.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'message': 'If the client times out, wait briefly, check bridge status, then '
                                               'inspect visual evidence resources and audit logs before rerunning '
                                               'repairs.'}},
  'handler_key': 'run_animation_repair_loop',
  'order': 430,
  'groups': ('animation', 'deep_inspect', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_shape_key',
  'description': 'Create or update a shape key value on a mesh object. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_name': {'type': 'string'},
                                  'key_name': {'type': 'string'},
                                  'value': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'required': ['key_name'],
                   'additionalProperties': False},
  'contract': {'description': 'Create or update a mesh shape key value',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_shape_key',
  'order': 780,
  'groups': ('advanced_create',),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'animate_shape_key',
  'description': 'Keyframe a shape key value over a frame range. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_name': {'type': 'string'},
                                  'key_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'value_start': {'type': 'number'},
                                  'value_end': {'type': 'number'},
                                  'create_if_missing': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'required': ['key_name', 'frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Keyframe a mesh shape key value over a frame range',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'animate_shape_key',
  'order': 790,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'animate_object_bounce',
  'description': 'Create repeated location keyframes that bounce one object along an axis. Applies immediately with '
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'distance': {'type': 'number'},
                                  'cycles': {'type': 'integer', 'minimum': 1, 'maximum': 24},
                                  'interpolation': {'type': 'string', 'enum': ['CONSTANT', 'LINEAR', 'BEZIER']},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Create repeated location keyframes that bounce one object along an axis',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'animate_object_bounce',
  'order': 800,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_progressive_bounce_animation',
  'description': 'Create repeated bounce keyframes plus decreasing scale keys for one object. Applies immediately with '
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'distance': {'type': 'number'},
                                  'cycles': {'type': 'integer', 'minimum': 1, 'maximum': 24},
                                  'scale_end_factor': {'type': 'number'},
                                  'interpolation': {'type': 'string', 'enum': ['CONSTANT', 'LINEAR', 'BEZIER']},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Create repeated bounce keyframes plus decreasing scale keys for one object',
               'mutates_scene': True},
  'handler_key': 'create_progressive_bounce_animation',
  'order': 810,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'animate_material_property',
  'description': 'Keyframe a Principled material socket such as base color, emission strength, roughness, metallic, or '
                 'alpha. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'material_name': {'type': 'string'},
                                  'object_name': {'type': 'string'},
                                  'property_name': {'type': 'string',
                                                    'enum': ['base_color',
                                                             'diffuse_color',
                                                             'color',
                                                             'emission_color',
                                                             'emission',
                                                             'emission_strength',
                                                             'glow',
                                                             'roughness',
                                                             'metallic',
                                                             'alpha']},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'value_start': {'oneOf': [{'type': 'number'},
                                                            {'type': 'array',
                                                             'items': {'type': 'number'},
                                                             'minItems': 3,
                                                             'maxItems': 4}]},
                                  'value_end': {'oneOf': [{'type': 'number'},
                                                          {'type': 'array',
                                                           'items': {'type': 'number'},
                                                           'minItems': 3,
                                                           'maxItems': 4}]},
                                  'create_if_missing': {'type': 'boolean'},
                                  'interpolation': {'type': 'string', 'enum': ['CONSTANT', 'LINEAR', 'BEZIER']},
                                  'label': {'type': 'string'}},
                   'required': ['property_name', 'frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Keyframe a Principled material socket such as base color, emission strength, roughness, '
                              'metallic, or alpha',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'animate_material_property',
  'order': 820,
  'groups': ('materials', 'animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'animate_light_property',
  'description': 'Keyframe a light data property such as energy, color, shadow softness, spot size, or spot blend. '
                 'Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'light_name': {'type': 'string'},
                                  'property_name': {'type': 'string',
                                                    'enum': ['energy',
                                                             'intensity',
                                                             'color',
                                                             'colour',
                                                             'shadow_soft_size',
                                                             'spot_size',
                                                             'spot_blend']},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'value_start': {'oneOf': [{'type': 'number'},
                                                            {'type': 'array',
                                                             'items': {'type': 'number'},
                                                             'minItems': 3,
                                                             'maxItems': 3}]},
                                  'value_end': {'oneOf': [{'type': 'number'},
                                                          {'type': 'array',
                                                           'items': {'type': 'number'},
                                                           'minItems': 3,
                                                           'maxItems': 3}]},
                                  'interpolation': {'type': 'string', 'enum': ['CONSTANT', 'LINEAR', 'BEZIER']},
                                  'label': {'type': 'string'}},
                   'required': ['property_name', 'frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Keyframe a light data property such as energy, color, shadow softness, spot size, or '
                              'spot blend',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'animate_light_property',
  'order': 830,
  'groups': ('animation', 'camera_render', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_follow_path_animation',
  'description': 'Animate an object along an existing curve or a new curve built from path points. Applies immediately '
                 'with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_name': {'type': 'string'},
                                  'path_name': {'type': 'string'},
                                  'path_points': {'type': 'array',
                                                  'items': {'type': 'array',
                                                            'items': {'type': 'number'},
                                                            'minItems': 3,
                                                            'maxItems': 3}},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'constraint_name': {'type': 'string'},
                                  'follow_curve': {'type': 'boolean'},
                                  'interpolation': {'type': 'string', 'enum': ['CONSTANT', 'LINEAR', 'BEZIER']},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Animate an object along an existing curve or a new curve built from path points',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_follow_path_animation',
  'order': 840,
  'groups': ('animation', 'advanced_create', 'curves_text'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'set_action_interpolation',
  'description': 'Set keyframe interpolation and optional easing for named actions or object-owned actions. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'action_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'interpolation': {'type': 'string',
                                                    'enum': ['CONSTANT',
                                                             'LINEAR',
                                                             'BEZIER',
                                                             'SINE',
                                                             'QUAD',
                                                             'CUBIC',
                                                             'QUART',
                                                             'QUINT',
                                                             'EXPO',
                                                             'CIRC',
                                                             'BACK',
                                                             'BOUNCE',
                                                             'ELASTIC']},
                                  'easing': {'type': 'string', 'enum': ['AUTO', 'EASE_IN', 'EASE_OUT', 'EASE_IN_OUT']},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Set interpolation and optional easing on action keyframes',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_action_interpolation',
  'order': 850,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'retime_actions',
  'description': 'Scale existing action keyframes into a new frame range. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'action_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'snap_to_integer': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Scale existing action keyframes into a new frame range',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'retime_actions',
  'order': 860,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'add_action_cycles',
  'description': 'Add cycles modifiers to action f-curves so an animation loops. Applies immediately with preview '
                 'revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'action_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'mode_before': {'type': 'string',
                                                  'enum': ['NONE', 'REPEAT', 'REPEAT_OFFSET', 'MIRROR']},
                                  'mode_after': {'type': 'string',
                                                 'enum': ['NONE', 'REPEAT', 'REPEAT_OFFSET', 'MIRROR']},
                                  'replace_existing': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add cycles modifiers to action f-curves for looping animation',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_action_cycles',
  'order': 870,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'clear_animation',
  'description': 'Clear object, data, shape-key, and optionally material animation from selected or named objects. '
                 'Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'include_object_animation': {'type': 'boolean'},
                                  'include_data_animation': {'type': 'boolean'},
                                  'include_shape_key_animation': {'type': 'boolean'},
                                  'include_material_animation': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Clear object, data, shape-key, and optional material animation',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'clear_animation',
  'order': 880,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'set_animation_preview_range',
  'description': 'Set scene preview playback range and optionally move the playhead. Applies immediately with preview '
                 'revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'current_frame': {'type': 'integer'},
                                  'use_preview_range': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Set scene preview playback range and optional current frame',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_animation_preview_range',
  'order': 890,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_turntable_animation',
  'description': 'Create a simple rotating product/object turntable animation. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'revolutions': {'type': 'number'},
                                  'add_cycles': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a rotating product/object turntable animation',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_turntable_animation',
  'order': 900,
  'groups': ('animation', 'camera_render', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_pulse_animation',
  'description': 'Create a scale pulse and optional emission-strength pulse for an object. Applies immediately with '
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'scale_factor': {'type': 'number'},
                                  'emission_strength_end': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a scale pulse and optional emission-strength pulse',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_pulse_animation',
  'order': 910,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_reveal_animation',
  'description': 'Create a scale reveal and optional material alpha fade. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'scale_start': {'type': 'number'},
                                  'scale_end': {'type': 'number'},
                                  'fade_material': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a scale reveal and optional material alpha fade',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_reveal_animation',
  'order': 920,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_staggered_motion',
  'description': 'Create staggered location animation across selected or named objects. Applies immediately with '
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'frame_start': {'type': 'integer'},
                                  'duration': {'type': 'integer'},
                                  'frame_step': {'type': 'integer'},
                                  'location_delta': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3},
                                  'interpolation': {'type': 'string',
                                                    'enum': ['CONSTANT',
                                                             'LINEAR',
                                                             'BEZIER',
                                                             'SINE',
                                                             'QUAD',
                                                             'CUBIC',
                                                             'QUART',
                                                             'QUINT',
                                                             'EXPO',
                                                             'CIRC',
                                                             'BACK',
                                                             'BOUNCE',
                                                             'ELASTIC']},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start'],
                   'additionalProperties': False},
  'contract': {'description': 'Create staggered location animation across selected or named objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_staggered_motion',
  'order': 930,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'block_key_poses',
  'description': 'Block animator-style keyed transform poses for selected or named objects. Use this after '
                 'create_timing_chart when you have concrete pose transforms. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'poses': {'type': 'array',
                                            'items': {'type': 'object',
                                                      'properties': {'frame': {'type': 'integer'},
                                                                     'label': {'type': 'string'},
                                                                     'location': {'type': 'array',
                                                                                  'items': {'type': 'number'},
                                                                                  'minItems': 3,
                                                                                  'maxItems': 3},
                                                                     'rotation': {'type': 'array',
                                                                                  'items': {'type': 'number'},
                                                                                  'minItems': 3,
                                                                                  'maxItems': 3},
                                                                     'rotation_euler': {'type': 'array',
                                                                                        'items': {'type': 'number'},
                                                                                        'minItems': 3,
                                                                                        'maxItems': 3},
                                                                     'scale': {'type': 'array',
                                                                               'items': {'type': 'number'},
                                                                               'minItems': 3,
                                                                               'maxItems': 3},
                                                                     'hold_frames': {'type': 'integer'}},
                                                      'additionalProperties': False}},
                                  'interpolation': {'type': 'string',
                                                    'enum': ['CONSTANT',
                                                             'LINEAR',
                                                             'BEZIER',
                                                             'SINE',
                                                             'QUAD',
                                                             'CUBIC',
                                                             'QUART',
                                                             'QUINT',
                                                             'EXPO',
                                                             'CIRC',
                                                             'BACK',
                                                             'BOUNCE',
                                                             'ELASTIC']},
                                  'label': {'type': 'string'}},
                   'required': ['poses'],
                   'additionalProperties': False},
  'contract': {'description': 'Block keyed transform poses for selected or named objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'block_key_poses',
  'order': 940,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'add_breakdown_pose',
  'description': 'Add a keyed breakdown pose between surrounding key poses, optionally using explicit transform '
                 'values. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame': {'type': 'integer'},
                                  'previous_frame': {'type': 'integer'},
                                  'next_frame': {'type': 'integer'},
                                  'factor': {'type': 'number'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'rotation': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'scale': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 3},
                                  'paths': {'type': 'array',
                                            'items': {'type': 'string',
                                                      'enum': ['location', 'rotation_euler', 'scale']}},
                                  'interpolation': {'type': 'string',
                                                    'enum': ['CONSTANT',
                                                             'LINEAR',
                                                             'BEZIER',
                                                             'SINE',
                                                             'QUAD',
                                                             'CUBIC',
                                                             'QUART',
                                                             'QUINT',
                                                             'EXPO',
                                                             'CIRC',
                                                             'BACK',
                                                             'BOUNCE',
                                                             'ELASTIC']},
                                  'label': {'type': 'string'}},
                   'required': ['frame'],
                   'additionalProperties': False},
  'contract': {'description': 'Add a keyed breakdown pose between existing key poses',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_breakdown_pose',
  'order': 950,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'set_pose_hold',
  'description': 'Duplicate a keyed pose for a hold so contact, staging, or hero poses read before polish. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame': {'type': 'integer'},
                                  'hold_frames': {'type': 'integer'},
                                  'paths': {'type': 'array',
                                            'items': {'type': 'string',
                                                      'enum': ['location', 'rotation_euler', 'scale']}},
                                  'interpolation': {'type': 'string',
                                                    'enum': ['CONSTANT',
                                                             'LINEAR',
                                                             'BEZIER',
                                                             'SINE',
                                                             'QUAD',
                                                             'CUBIC',
                                                             'QUART',
                                                             'QUINT',
                                                             'EXPO',
                                                             'CIRC',
                                                             'BACK',
                                                             'BOUNCE',
                                                             'ELASTIC']},
                                  'label': {'type': 'string'}},
                   'required': ['frame'],
                   'additionalProperties': False},
  'contract': {'description': 'Duplicate a keyed pose to create a readable hold',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_pose_hold',
  'order': 960,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_motion_arc',
  'description': 'Create preview curve objects from sampled object locations so motion arcs are visible in the scene. '
                 'Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'sample_step': {'type': 'integer'},
                                  'name_prefix': {'type': 'string'},
                                  'bevel_depth': {'type': 'number'},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 4, 'maxItems': 4},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create preview curve objects that visualize sampled object motion arcs',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_motion_arc',
  'order': 1040,
  'groups': ('animation', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_camera_dolly_animation',
  'description': 'Create a camera dolly/shot move with location keyframes, optional target tracking, and optional lens '
                 'keyframes. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'camera_name': {'type': 'string'},
                                  'target_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'start_location': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3},
                                  'end_location': {'type': 'array',
                                                   'items': {'type': 'number'},
                                                   'minItems': 3,
                                                   'maxItems': 3},
                                  'lens_start': {'type': 'number'},
                                  'lens_end': {'type': 'number'},
                                  'interpolation': {'type': 'string',
                                                    'enum': ['CONSTANT',
                                                             'LINEAR',
                                                             'BEZIER',
                                                             'SINE',
                                                             'QUAD',
                                                             'CUBIC',
                                                             'QUART',
                                                             'QUINT',
                                                             'EXPO',
                                                             'CIRC',
                                                             'BACK',
                                                             'BOUNCE',
                                                             'ELASTIC']},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create a reversible camera dolly move with optional target tracking and lens keyframes',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'camera_name': {'type': 'string'},
                                               'target_name': {'type': 'string'},
                                               'frame_start': {'type': 'integer'},
                                               'frame_end': {'type': 'integer'},
                                               'start_location': {'type': 'array',
                                                                  'items': {'type': 'number'},
                                                                  'minItems': 3,
                                                                  'maxItems': 3},
                                               'end_location': {'type': 'array',
                                                                'items': {'type': 'number'},
                                                                'minItems': 3,
                                                                'maxItems': 3},
                                               'lens_start': {'type': 'number'},
                                               'lens_end': {'type': 'number'},
                                               'interpolation': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'create_camera_dolly_animation',
  'order': 1290,
  'groups': ('animation', 'camera_render', 'advanced_create', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'set_scene_frame_range',
  'description': 'Set the scene timeline frame range, current frame, and optionally FPS. Applies immediately with '
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'current_frame': {'type': 'integer'},
                                  'fps': {'type': 'integer'},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Set timeline frame range, current frame, and FPS',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_scene_frame_range',
  'order': 1580,
  'groups': ('animation',),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'animate_selected_transform',
  'description': 'Create simple transform keyframes for selected objects using a preview action. Applies immediately '
                 'with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'location_start': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3},
                                  'location_end': {'type': 'array',
                                                   'items': {'type': 'number'},
                                                   'minItems': 3,
                                                   'maxItems': 3},
                                  'rotation_start': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3,
                                                     'description': 'Euler rotation in radians'},
                                  'rotation_end': {'type': 'array',
                                                   'items': {'type': 'number'},
                                                   'minItems': 3,
                                                   'maxItems': 3,
                                                   'description': 'Euler rotation in radians'},
                                  'scale_start': {'type': 'array',
                                                  'items': {'type': 'number'},
                                                  'minItems': 3,
                                                  'maxItems': 3},
                                  'scale_end': {'type': 'array',
                                                'items': {'type': 'number'},
                                                'minItems': 3,
                                                'maxItems': 3},
                                  'label': {'type': 'string'}},
                   'required': ['frame_start', 'frame_end'],
                   'additionalProperties': False},
  'contract': {'description': 'Create simple transform keyframes for selected objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'animate_selected_transform',
  'order': 1600,
  'groups': ('animation',),
  'exposure': 'catalog',
  'owner': 'animation'},
 {'name': 'create_camera_orbit',
  'description': 'Create a camera orbit rig around a target object and keyframe it over a frame range. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'radius': {'type': 'number'},
                                  'height': {'type': 'number'},
                                  'name': {'type': 'string'},
                                  'lens': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'required': ['target_name', 'frame_start', 'frame_end', 'radius', 'height', 'name'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a keyframed camera orbit rig around a target object',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_camera_orbit',
  'order': 1610,
  'groups': ('animation', 'camera_render'),
  'exposure': 'catalog',
  'owner': 'animation'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import animation

    animation.register(handler_registry, SPECS)
