"""Canonical tool specifications for the camera render evidence domain."""

from __future__ import annotations

from ..registry import ToolSpec


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'capture_viewport',
  'description': 'Capture the current Blender viewport/window and return visual context metadata plus a local artifact '
                 'path. Use when an external agent needs explicit screenshot evidence or MCP-readable image resources.',
  'input_schema': {'type': 'object',
                   'properties': {'max_bytes': {'type': 'integer',
                                                'description': 'Maximum PNG bytes to keep after resizing/compression. '
                                                               'Defaults to the add-on preference.'}},
                   'additionalProperties': False},
  'contract': {'description': 'Capture the current viewport/window and return visual metadata plus a local artifact '
                              'path',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['scene:read', 'files:write'],
               'supports_headless': False,
               'timeout_seconds': 30},
  'handler_key': 'capture_viewport',
  'order': 10,
  'groups': ('camera_render', 'deep_inspect', 'advanced_workflow'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'capture_animation_playblast',
  'description': 'Capture sampled low-resolution viewport frames across an animation range and return playblast '
                 'metadata plus MCP frame resource URIs for visual animation review. Defaults to preview quality '
                 'capped at 640x360; request quality/max_width/max_height only when higher fidelity is needed. '
                 'Requires an interactive Blender window and fails soft in background mode. This is synchronous and '
                 'roughly 1 second per sampled frame; if it times out, wait and check blender_bridge_status/latest '
                 'playblast metadata before recapturing.',
  'input_schema': {'type': 'object',
                   'properties': {'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'max_frames': {'type': 'integer',
                                                 'description': 'Maximum sampled frames to capture from the animation '
                                                                'range. Defaults to 12.'},
                                  'max_bytes': {'type': 'integer',
                                                'description': 'Maximum PNG bytes per sampled frame after '
                                                               'resizing/compression.'},
                                  'quality': {'type': 'string',
                                              'enum': ['preview',
                                                       'low',
                                                       'standard',
                                                       'medium',
                                                       'high',
                                                       'hd',
                                                       'source',
                                                       'original',
                                                       'full'],
                                              'description': 'Frame-size preset. Defaults to preview/low at 640x360; '
                                                             'source/original keeps viewport dimensions.'},
                                  'max_width': {'type': 'integer',
                                                'description': 'Optional maximum stored frame width. Overrides the '
                                                               'quality preset.'},
                                  'max_height': {'type': 'integer',
                                                 'description': 'Optional maximum stored frame height. Overrides the '
                                                                'quality preset.'},
                                  'brief': {'type': 'string',
                                            'description': 'Short animation intent or prompt contract to store with '
                                                           'the playblast metadata.'},
                                  'shading': {'type': 'string',
                                              'enum': ['WIREFRAME', 'SOLID', 'MATERIAL', 'RENDERED'],
                                              'description': 'Optional viewport shading for the capture. Defaults to '
                                                             'the current viewport; use MATERIAL or RENDERED to review '
                                                             'materials and lighting instead of flat solid shading.'}},
                   'additionalProperties': False},
  'contract': {'description': 'Capture sampled low-resolution viewport frames across an animation range for visual '
                              'review',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['scene:read', 'files:write'],
               'supports_headless': False,
               'long_running': True,
               'duration_hint': 'Synchronous viewport capture; rough estimate is about 1 second per sampled frame, '
                                'with the default 12 low-resolution preview frames often around 10-20 seconds on large '
                                'scenes.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'message': 'If the MCP client times out, the playblast may still finish. Wait, '
                                               'check bridge status, then read latest playblast metadata or audit logs '
                                               'before recapturing.'},
               'timeout_seconds': 120,
               'input_schema': {'type': 'object',
                                'properties': {'frame_start': {'type': 'integer'},
                                               'frame_end': {'type': 'integer'},
                                               'max_frames': {'type': 'integer'},
                                               'max_bytes': {'type': 'integer'},
                                               'quality': {'type': 'string',
                                                           'enum': ['preview',
                                                                    'low',
                                                                    'standard',
                                                                    'medium',
                                                                    'high',
                                                                    'hd',
                                                                    'source',
                                                                    'original',
                                                                    'full']},
                                               'max_width': {'type': 'integer'},
                                               'max_height': {'type': 'integer'},
                                               'brief': {'type': 'string'},
                                               'shading': {'type': 'string',
                                                           'enum': ['WIREFRAME', 'SOLID', 'MATERIAL', 'RENDERED'],
                                                           'description': 'Optional viewport shading for the capture. '
                                                                          'Defaults to the current viewport; use '
                                                                          'MATERIAL or RENDERED to review materials '
                                                                          'and lighting.'}},
                                'additionalProperties': False},
               'output_schema': {'type': 'object',
                                 'properties': {'ok': {'type': 'boolean'},
                                                'message': {'type': 'string'},
                                                'playblast': {'type': 'object',
                                                              'properties': {'ok': {'type': 'boolean'},
                                                                             'available': {'type': 'boolean'},
                                                                             'playblast_id': {'type': 'string'},
                                                                             'metadata_uri': {'type': 'string'},
                                                                             'latest_metadata_uri': {'type': 'string'},
                                                                             'frame_start': {'type': 'integer'},
                                                                             'frame_end': {'type': 'integer'},
                                                                             'frame_count': {'type': 'integer'},
                                                                             'requested_frame_count': {'type': 'integer'},
                                                                             'sampled_frames': {'type': 'array',
                                                                                                'items': {'type': 'integer'}},
                                                                             'quality': {'type': 'string'},
                                                                             'shading': {'type': 'string'},
                                                                             'frames': {'type': 'array',
                                                                                        'items': {'type': 'object'}}},
                                                              'required': ['ok', 'available'],
                                                              'additionalProperties': True}},
                                 'required': ['ok'],
                                 'additionalProperties': True}},
  'handler_key': 'capture_animation_playblast',
  'order': 20,
  'groups': ('animation', 'camera_render', 'deep_inspect', 'advanced_workflow', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'capture_object_inspection_renders',
  'description': 'Render diagnostic close-up PNGs of named objects from bounded inspection views, then return metadata '
                 'plus MCP image resource URIs. Use when visual object details need rendered evidence, such as '
                 'undersides, side views, occluded parts, or model defects. This is synchronous and may take a few '
                 'seconds per object/view; if it times out, wait and check blender_bridge_status/latest '
                 'inspection-render metadata before recapturing.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array',
                                                   'items': {'type': 'string'},
                                                   'description': 'Objects or root objects to render. Children are '
                                                                  'included when computing bounds.'},
                                  'views': {'type': 'array',
                                            'items': {'type': 'string',
                                                      'enum': ['front_below',
                                                               'underside',
                                                               'side',
                                                               'front',
                                                               'rear',
                                                               'top']},
                                            'description': 'Diagnostic view names. Defaults to front_below and side.'},
                                  'frame': {'type': 'integer',
                                            'description': 'Frame to render. Defaults to the current frame.'},
                                  'resolution_x': {'type': 'integer', 'description': 'PNG width. Defaults to 800.'},
                                  'resolution_y': {'type': 'integer', 'description': 'PNG height. Defaults to 600.'},
                                  'lens': {'type': 'number',
                                           'description': 'Temporary camera lens in mm. Defaults to 50.'},
                                  'distance_factor': {'type': 'number',
                                                      'description': 'Camera distance as a multiple of target bounding '
                                                                     'radius. Defaults to 3.'},
                                  'camera_name': {'type': 'string'},
                                  'note': {'type': 'string',
                                           'description': 'Short reason stored in the render metadata.'}},
                   'required': ['object_names'],
                   'additionalProperties': False},
  'contract': {'description': 'Render diagnostic close-up PNGs of named objects from bounded inspection views and '
                              'expose them as MCP resources',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['scene:read', 'files:write'],
               'supports_headless': True,
               'long_running': True,
               'duration_hint': 'Synchronous still renders; rough estimate is a few seconds per object/view at 800x600 '
                                'and more for heavy scenes or high resolutions.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'message': 'If the MCP client times out, inspection renders may still finish. '
                                               'Wait, check bridge status, then read latest inspection-render metadata '
                                               'or audit logs before rerendering.'},
               'timeout_seconds': 180},
  'handler_key': 'capture_object_inspection_renders',
  'order': 30,
  'groups': ('camera_render', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'get_visual_evidence_resources',
  'description': 'Return a compact inventory of latest MCP-readable viewport captures, playblasts, inspection renders, '
                 'render thumbnails, and render jobs. Use when an agent needs to know what visual/render evidence '
                 'exists and which resource URIs can be read.',
  'input_schema': {'type': 'object',
                   'properties': {'include_unavailable': {'type': 'boolean',
                                                          'description': 'Include resource families with no latest '
                                                                         'artifact yet. Defaults to true.'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return a compact inventory of latest viewport, playblast, inspection render, thumbnail, '
                              'and render-job MCP resources',
               'mutates_scene': False,
               'input_schema': {'type': 'object',
                                'properties': {'include_unavailable': {'type': 'boolean',
                                                                       'description': 'Include resource families with '
                                                                                      'no latest artifact yet. '
                                                                                      'Defaults to true.'}},
                                'additionalProperties': False}},
  'handler_key': 'get_visual_evidence_resources',
  'order': 100,
  'groups': ('camera_render', 'deep_inspect', 'advanced_workflow'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'render_scene_thumbnail',
  'description': 'Render a small PNG from the scene camera or a named camera, then return metadata plus exact MCP '
                 'image resource URIs. Use for render evidence, thumbnails, and client-readable still output. Large '
                 'synchronous renders are guarded; use start_render_job for timeout-safe high-resolution output.',
  'input_schema': {'type': 'object',
                   'properties': {'filepath': {'type': 'string',
                                               'description': 'Optional PNG output path. Defaults to the '
                                                              'project/session capture cache.'},
                                  'frame': {'type': 'integer',
                                            'description': 'Frame to render. Defaults to current frame.'},
                                  'resolution_x': {'type': 'integer', 'description': 'PNG width. Defaults to 512.'},
                                  'resolution_y': {'type': 'integer', 'description': 'PNG height. Defaults to 512.'},
                                  'camera_name': {'type': 'string',
                                                  'description': 'Optional camera object name. Defaults to active '
                                                                 'scene camera.'},
                                  'note': {'type': 'string',
                                           'description': 'Short reason stored in thumbnail metadata.'},
                                  'allow_blocking_render': {'type': 'boolean',
                                                            'description': 'Allow a large synchronous still render. '
                                                                           'Defaults to false; large previews should '
                                                                           'use start_render_job.'}},
                   'additionalProperties': False},
  'contract': {'description': 'Render a small PNG from the scene camera or named camera and expose it as an MCP image '
                              'resource',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['scene:read', 'files:write'],
               'supports_headless': True,
               'long_running': True,
               'duration_hint': 'Small guarded still renders are usually seconds. Large synchronous renders are '
                                'blocked by default; use start_render_job for timeout-safe high-resolution output.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'recommended_tool': 'start_render_job',
                                    'message': 'If the MCP client times out, wait, check bridge status, then inspect '
                                               'latest render-thumbnail metadata or use start_render_job for a '
                                               'timeout-safe rerun.'},
               'timeout_seconds': 180,
               'input_schema': {'type': 'object',
                                'properties': {'filepath': {'type': 'string',
                                                            'description': 'Optional PNG output path. Defaults to the '
                                                                           'project/session capture cache.'},
                                               'frame': {'type': 'integer',
                                                         'description': 'Frame to render. Defaults to current frame.'},
                                               'resolution_x': {'type': 'integer',
                                                                'description': 'PNG width. Defaults to 512.'},
                                               'resolution_y': {'type': 'integer',
                                                                'description': 'PNG height. Defaults to 512.'},
                                               'camera_name': {'type': 'string',
                                                               'description': 'Optional camera object name. Defaults '
                                                                              'to the active scene camera.'},
                                               'note': {'type': 'string',
                                                        'description': 'Short reason stored in thumbnail metadata.'},
                                               'allow_blocking_render': {'type': 'boolean',
                                                                         'description': 'Allow a large synchronous '
                                                                                        'still render. Defaults to '
                                                                                        'false; large previews should '
                                                                                        'use start_render_job.'}},
                                'additionalProperties': False}},
  'handler_key': 'render_scene_thumbnail',
  'order': 140,
  'groups': ('camera_render', 'deep_inspect', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'start_render_job',
  'description': 'Start a long-running render or playblast job in a background Blender process and return immediately '
                 'with a job id, rough ETA, and polling guidance. Auto quality keeps final renders high quality but '
                 'defaults playblast/preview/review/draft jobs to low resolution unless quality or resolution is '
                 'specified. Use for 1080p/4K, high-sample, full-frame-range renders, frame sequences, or MP4 quality '
                 'checks instead of blocking render tools or draft_script.',
  'input_schema': {'type': 'object',
                   'properties': {'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'resolution_x': {'type': 'integer',
                                                   'description': 'Output width. Defaults to auto quality profile: 640 '
                                                                  'for playblast/preview/review jobs, 1920 for final '
                                                                  'renders.'},
                                  'resolution_y': {'type': 'integer',
                                                   'description': 'Output height. Defaults to auto quality profile: '
                                                                  '360 for playblast/preview/review jobs, 1080 for '
                                                                  'final renders.'},
                                  'resolution_percentage': {'type': 'integer',
                                                            'description': 'Render percentage. Defaults to 100.'},
                                  'samples': {'type': 'integer',
                                              'description': 'Cycles/Eevee render samples. Defaults to auto quality '
                                                             'profile: low for playblast/preview/review jobs, higher '
                                                             'for final renders.'},
                                  'quality': {'type': 'string',
                                              'enum': ['auto',
                                                       'preview',
                                                       'low',
                                                       'standard',
                                                       'medium',
                                                       'high',
                                                       'hd',
                                                       'final',
                                                       'full',
                                                       'production',
                                                       '1080p'],
                                              'description': 'Defaulting profile when resolution/samples are omitted. '
                                                             'Auto uses low-res for playblast/preview/review/draft '
                                                             'jobs and final-quality defaults otherwise.'},
                                  'fps': {'type': 'integer'},
                                  'camera_name': {'type': 'string',
                                                  'description': 'Optional camera object to render from. Timeline '
                                                                 'camera markers still work when no camera is passed.'},
                                  'output_kind': {'type': 'string',
                                                  'enum': ['frames', 'video', 'mp4'],
                                                  'description': 'Use frames for PNG sequences with progress counts, '
                                                                 'or video/mp4 for direct MP4 output.'},
                                  'job_name': {'type': 'string'},
                                  'note': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Start a long-running background Blender render job and return immediately with a job '
                              'id, rough ETA, and status polling guidance. Auto quality keeps playblast/preview/review '
                              'jobs low-res unless quality/resolution is specified.',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['scene:read', 'files:write', 'process:start'],
               'supports_headless': True,
               'returns_background_job': True,
               'duration_hint': 'Returns quickly, then the background render may run from seconds to hours. Use the '
                                'returned estimated_duration and poll_after_seconds.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_visual_evidence_resources',
                                    'message': 'If startup times out, check bridge status and latest render-job '
                                               'metadata before starting another job.'},
               'timeout_seconds': 30,
               'input_schema': {'type': 'object',
                                'properties': {'frame_start': {'type': 'integer'},
                                               'frame_end': {'type': 'integer'},
                                               'resolution_x': {'type': 'integer'},
                                               'resolution_y': {'type': 'integer'},
                                               'resolution_percentage': {'type': 'integer'},
                                               'samples': {'type': 'integer'},
                                               'quality': {'type': 'string',
                                                           'enum': ['auto',
                                                                    'preview',
                                                                    'low',
                                                                    'standard',
                                                                    'medium',
                                                                    'high',
                                                                    'hd',
                                                                    'final',
                                                                    'full',
                                                                    'production',
                                                                    '1080p']},
                                               'fps': {'type': 'integer'},
                                               'camera_name': {'type': 'string'},
                                               'output_kind': {'type': 'string', 'enum': ['frames', 'video', 'mp4']},
                                               'job_name': {'type': 'string'},
                                               'note': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'start_render_job',
  'order': 150,
  'groups': ('camera_render', 'deep_inspect', 'two_d_storyboard'),
  'exposure': 'compact_direct',
  'owner': 'camera_render_evidence'},
 {'name': 'get_render_job_status',
  'description': 'Poll a background render job for status, frame progress, output paths, latest frame resource URI, '
                 'log tail, and completion state.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Poll an async render job for progress, output paths, frame resources, logs, and '
                              'completion state',
               'mutates_scene': False,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'get_render_job_status',
  'order': 160,
  'groups': ('camera_render', 'deep_inspect'),
  'exposure': 'compact_direct',
  'owner': 'camera_render_evidence'},
 {'name': 'cancel_render_job',
  'description': 'Cancel a tracked background render job started by this Blender bridge session.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Cancel a tracked async render job started by this Blender bridge session',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['process:terminate'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'cancel_render_job',
  'order': 170,
  'groups': ('camera_render', 'deep_inspect'),
  'exposure': 'compact_direct',
  'owner': 'camera_render_evidence'},
 {'name': 'assemble_render_job_video',
  'description': 'Assemble a completed PNG frame-sequence render job into an MP4 in a background Blender process, then '
                 'poll get_render_job_status for completion.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'},
                                  'fps': {'type': 'integer',
                                          'description': 'Optional output FPS. Defaults to the render job FPS.'},
                                  'output_path': {'type': 'string',
                                                  'description': 'Optional MP4 path. Relative paths resolve inside the '
                                                                 'render job folder.'},
                                  'quality': {'type': 'string',
                                              'enum': ['LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'PERC_LOSSLESS', 'LOSSLESS'],
                                              'description': 'Blender FFmpeg quality. Defaults to HIGH.'},
                                  'overwrite': {'type': 'boolean',
                                                'description': 'Overwrite an existing MP4. Defaults to true.'},
                                  'allow_partial': {'type': 'boolean',
                                                    'description': 'Allow assembly before every expected frame is '
                                                                   'present. Defaults to false.'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Assemble a completed PNG frame-sequence render job into an MP4 using a background '
                              'Blender process',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['files:read', 'files:write', 'process:start'],
               'supports_headless': True,
               'returns_background_job': True,
               'duration_hint': 'Returns quickly after starting MP4 assembly in a background Blender process. Poll '
                                'get_render_job_status until the render job returns to a terminal state with video '
                                'availability.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_render_job_status',
                                    'message': 'If startup times out, check bridge status and then poll '
                                               'get_render_job_status before starting another assembly job.'},
               'timeout_seconds': 30,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'},
                                               'fps': {'type': 'integer'},
                                               'output_path': {'type': 'string'},
                                               'quality': {'type': 'string',
                                                           'enum': ['LOWEST',
                                                                    'LOW',
                                                                    'MEDIUM',
                                                                    'HIGH',
                                                                    'PERC_LOSSLESS',
                                                                    'LOSSLESS']},
                                               'overwrite': {'type': 'boolean'},
                                               'allow_partial': {'type': 'boolean'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'assemble_render_job_video',
  'order': 180,
  'groups': ('camera_render', 'deep_inspect'),
  'exposure': 'compact_direct',
  'owner': 'camera_render_evidence'},
 {'name': 'validate_render_job_output',
  'description': 'Validate render job frame completeness, MP4 presence/size, and useful output resource URIs before '
                 'reporting a render as done.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'},
                                  'require_video': {'type': 'boolean',
                                                    'description': 'Require MP4 output. Defaults to true.'},
                                  'min_video_size_bytes': {'type': 'integer',
                                                           'description': 'Minimum acceptable MP4 size. Defaults to 1 '
                                                                          'byte.'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Validate render job frame sequence and MP4 output paths, sizes, resource URIs, and '
                              'completion health',
               'mutates_scene': False,
               'has_side_effects': False,
               'permissions': ['files:read'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'},
                                               'require_video': {'type': 'boolean'},
                                               'min_video_size_bytes': {'type': 'integer'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'validate_render_job_output',
  'order': 190,
  'groups': ('camera_render', 'deep_inspect'),
  'exposure': 'compact_direct',
  'owner': 'camera_render_evidence'},
 {'name': 'get_render_camera_compositor_details',
  'description': 'Fetch read-only render settings, active camera settings, world settings, and compositor node '
                 'summaries.',
  'input_schema': {'type': 'object', 'properties': {}, 'additionalProperties': False},
  'contract': {'description': 'Return render, camera, world, and compositor summaries', 'mutates_scene': False},
  'handler_key': 'get_render_camera_compositor_details',
  'order': 540,
  'groups': ('camera_render', 'deep_inspect', 'advanced_workflow'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'set_render_settings',
  'description': 'Set render engine, resolution, FPS, frame range, transparency, look-dev quality preset, samples, '
                 'denoise, and color management. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'engine': {'type': 'string'},
                                  'resolution': {'type': 'array',
                                                 'items': {'type': 'integer'},
                                                 'minItems': 2,
                                                 'maxItems': 2},
                                  'fps': {'type': 'integer'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'film_transparent': {'type': 'boolean'},
                                  'quality_preset': {'type': 'string', 'enum': ['preview', 'lookdev', 'final']},
                                  'samples': {'type': 'integer', 'minimum': 1, 'maximum': 4096},
                                  'denoise': {'type': 'boolean'},
                                  'view_transform': {'type': 'string'},
                                  'look': {'type': 'string'},
                                  'exposure': {'type': 'number'},
                                  'gamma': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Set render engine, resolution, FPS, frame range, transparency, look-dev quality preset, '
                              'samples, denoise, and color management',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'engine': {'type': 'string'},
                                               'resolution': {'type': 'array',
                                                              'items': {'type': 'integer'},
                                                              'minItems': 2,
                                                              'maxItems': 2},
                                               'fps': {'type': 'integer'},
                                               'frame_start': {'type': 'integer'},
                                               'frame_end': {'type': 'integer'},
                                               'film_transparent': {'type': 'boolean'},
                                               'quality_preset': {'type': 'string',
                                                                  'enum': ['preview', 'lookdev', 'final']},
                                               'samples': {'type': 'integer', 'minimum': 1, 'maximum': 4096},
                                               'denoise': {'type': 'boolean'},
                                               'view_transform': {'type': 'string'},
                                               'look': {'type': 'string'},
                                               'exposure': {'type': 'number'},
                                               'gamma': {'type': 'number'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'set_render_settings',
  'order': 1100,
  'groups': ('camera_render', 'product'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'set_render_engine',
  'description': 'Set the render engine plus optional look-dev preset, samples, denoise, and color-management '
                 'controls. Use this for explicit engine/quality requests; use set_render_settings when resolution or '
                 'timeline settings also change.',
  'input_schema': {'type': 'object',
                   'properties': {'engine': {'type': 'string'},
                                  'quality_preset': {'type': 'string', 'enum': ['preview', 'lookdev', 'final']},
                                  'samples': {'type': 'integer', 'minimum': 1, 'maximum': 4096},
                                  'denoise': {'type': 'boolean'},
                                  'view_transform': {'type': 'string'},
                                  'look': {'type': 'string'},
                                  'exposure': {'type': 'number'},
                                  'gamma': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Set render engine and optional look-dev preset, samples, denoise, and color-management '
                              'controls',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'engine': {'type': 'string'},
                                               'quality_preset': {'type': 'string',
                                                                  'enum': ['preview', 'lookdev', 'final']},
                                               'samples': {'type': 'integer', 'minimum': 1, 'maximum': 4096},
                                               'denoise': {'type': 'boolean'},
                                               'view_transform': {'type': 'string'},
                                               'look': {'type': 'string'},
                                               'exposure': {'type': 'number'},
                                               'gamma': {'type': 'number'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'set_render_engine',
  'order': 1110,
  'groups': ('camera_render', 'product'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'configure_render_outputs',
  'description': 'Enable or disable ViewLayer render passes and configure shader AOVs. Use this for render-pass, '
                 'cryptomatte, depth/normal/AO, or custom AOV requests before custom compositor/render Python. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'view_layer_name': {'type': 'string'},
                                  'enabled_passes': {'type': 'array',
                                                     'items': {'type': 'string'},
                                                     'description': 'Pass aliases such as normal, depth/z, '
                                                                    'ambient_occlusion/ao, cryptomatte_object, '
                                                                    'diffuse_color, vector, uv, shadow, emit, and '
                                                                    'environment.'},
                                  'disabled_passes': {'type': 'array',
                                                      'items': {'type': 'string'},
                                                      'description': 'Pass aliases to turn off; unsupported names are '
                                                                     'reported as warnings.'},
                                  'aovs': {'type': 'array',
                                           'items': {'type': 'object',
                                                     'properties': {'name': {'type': 'string',
                                                                             'minLength': 1,
                                                                             'maxLength': 64},
                                                                    'type': {'type': 'string',
                                                                             'enum': ['COLOR', 'VALUE']}},
                                                     'required': ['name'],
                                                     'additionalProperties': False}},
                                  'clear_existing_aovs': {'type': 'boolean'},
                                  'pass_alpha_threshold': {'type': 'number', 'minimum': 0.0, 'maximum': 1.0},
                                  'pass_cryptomatte_depth': {'type': 'integer', 'minimum': 2, 'maximum': 16},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Enable or disable ViewLayer render passes and configure shader AOVs',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'view_layer_name': {'type': 'string'},
                                               'enabled_passes': {'type': 'array', 'items': {'type': 'string'}},
                                               'disabled_passes': {'type': 'array', 'items': {'type': 'string'}},
                                               'aovs': {'type': 'array',
                                                        'items': {'type': 'object',
                                                                  'properties': {'name': {'type': 'string',
                                                                                          'minLength': 1,
                                                                                          'maxLength': 64},
                                                                                 'type': {'type': 'string',
                                                                                          'enum': ['COLOR', 'VALUE']}},
                                                                  'required': ['name'],
                                                                  'additionalProperties': False}},
                                               'clear_existing_aovs': {'type': 'boolean'},
                                               'pass_alpha_threshold': {'type': 'number',
                                                                        'minimum': 0.0,
                                                                        'maximum': 1.0},
                                               'pass_cryptomatte_depth': {'type': 'integer',
                                                                          'minimum': 2,
                                                                          'maximum': 16},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'configure_render_outputs',
  'order': 1120,
  'groups': (),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'set_camera_settings',
  'description': 'Set camera lens, sensor width, and depth-of-field settings. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'camera_name': {'type': 'string'},
                                  'lens': {'type': 'number'},
                                  'sensor_width': {'type': 'number'},
                                  'dof_enabled': {'type': 'boolean'},
                                  'focus_object_name': {'type': 'string'},
                                  'aperture_fstop': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Set active or named camera lens and depth-of-field settings',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_camera_settings',
  'order': 1130,
  'groups': ('camera_render', 'vehicle', 'product'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'set_world_background',
  'description': 'Set the scene world background color. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 3},
                                  'label': {'type': 'string'}},
                   'required': ['color'],
                   'additionalProperties': False},
  'contract': {'description': 'Set scene world background color', 'mutates_scene': True, 'requires_live_preview': True},
  'handler_key': 'set_world_background',
  'order': 1140,
  'groups': ('camera_render',),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'create_studio_product_stage',
  'description': 'Create a production-style product presentation stage around a target object: floor, backdrop, '
                 'key/fill/rim area lights, target empty, and optional camera. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'stage_name': {'type': 'string'},
                                  'floor': {'type': 'boolean'},
                                  'backdrop': {'type': 'boolean'},
                                  'lighting': {'type': 'boolean'},
                                  'camera': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create a bounded studio/product presentation stage around a target object',
               'mutates_scene': True,
               'requires_live_preview': True,
               'output_schema': {'type': 'object',
                                 'properties': {'ok': {'type': 'boolean',
                                                       'description': 'Whether the tool completed successfully'},
                                                'message': {'type': 'string',
                                                            'description': 'Human-readable status or error message'},
                                                'created_objects': {'type': 'array', 'items': {'type': 'string'}},
                                                'lights': {'type': 'array', 'items': {'type': 'string'}},
                                                'lighting_warning': {'type': 'string',
                                                                     'description': 'Set when stacking lights onto an '
                                                                                    'already-lit scene may over-expose '
                                                                                    'the render; empty otherwise.'},
                                                'warnings': {'type': 'array', 'items': {'type': 'string'}}},
                                 'required': ['ok'],
                                 'additionalProperties': True}},
  'handler_key': 'create_studio_product_stage',
  'order': 1470,
  'groups': ('camera_render', 'advanced_create', 'refinement', 'vehicle', 'product', 'character'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'apply_lighting_preset',
  'description': 'Create a bounded production lighting preset around a target object. Presets include product_softbox, '
                 'dramatic_rim, and gallery_even. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'preset': {'type': 'string',
                                             'enum': ['product_softbox', 'dramatic_rim', 'gallery_even']},
                                  'rig_name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create a bounded production lighting rig around a target object',
               'mutates_scene': True,
               'requires_live_preview': True,
               'output_schema': {'type': 'object',
                                 'properties': {'ok': {'type': 'boolean',
                                                       'description': 'Whether the tool completed successfully'},
                                                'message': {'type': 'string',
                                                            'description': 'Human-readable status or error message'},
                                                'created_objects': {'type': 'array', 'items': {'type': 'string'}},
                                                'lights': {'type': 'array', 'items': {'type': 'string'}},
                                                'lighting_warning': {'type': 'string',
                                                                     'description': 'Set when stacking lights onto an '
                                                                                    'already-lit scene may over-expose '
                                                                                    'the render; empty otherwise.'},
                                                'warnings': {'type': 'array', 'items': {'type': 'string'}}},
                                 'required': ['ok'],
                                 'additionalProperties': True}},
  'handler_key': 'apply_lighting_preset',
  'order': 1490,
  'groups': ('camera_render', 'advanced_create', 'refinement', 'vehicle', 'product', 'character'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'create_product_turntable_setup',
  'description': 'Create a product turntable setup around a target: optional stage, rotating target animation, and '
                 'orbit camera. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'revolutions': {'type': 'number'},
                                  'radius': {'type': 'number'},
                                  'height': {'type': 'number'},
                                  'setup_name': {'type': 'string'},
                                  'create_stage': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create product staging, turntable animation, and camera orbit around a target',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_product_turntable_setup',
  'order': 1510,
  'groups': ('camera_render', 'advanced_create', 'refinement', 'vehicle', 'product'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'create_lookdev_turntable_review',
  'description': 'Create a bounded look-dev review setup around a target: optional stage, turntable animation, render '
                 'engine/quality controls, inspection still capture, and artifact validation. Applies scene changes '
                 'with preview revert support while render evidence remains as MCP resources.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'revolutions': {'type': 'number'},
                                  'setup_name': {'type': 'string'},
                                  'create_stage': {'type': 'boolean'},
                                  'create_turntable': {'type': 'boolean'},
                                  'render_engine': {'type': 'string'},
                                  'quality_preset': {'type': 'string', 'enum': ['preview', 'lookdev', 'final']},
                                  'samples': {'type': 'integer', 'minimum': 1, 'maximum': 4096},
                                  'denoise': {'type': 'boolean'},
                                  'view_transform': {'type': 'string'},
                                  'look': {'type': 'string'},
                                  'exposure': {'type': 'number'},
                                  'gamma': {'type': 'number'},
                                  'capture_inspection': {'type': 'boolean'},
                                  'views': {'type': 'array', 'items': {'type': 'string'}},
                                  'resolution_x': {'type': 'integer', 'minimum': 64, 'maximum': 4096},
                                  'resolution_y': {'type': 'integer', 'minimum': 64, 'maximum': 4096},
                                  'distance_factor': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create a bounded look-dev stage/turntable, apply render quality controls, capture '
                              'inspection stills, and validate output artifacts',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'target_name': {'type': 'string'},
                                               'frame_start': {'type': 'integer'},
                                               'frame_end': {'type': 'integer'},
                                               'revolutions': {'type': 'number'},
                                               'setup_name': {'type': 'string'},
                                               'create_stage': {'type': 'boolean'},
                                               'create_turntable': {'type': 'boolean'},
                                               'render_engine': {'type': 'string'},
                                               'quality_preset': {'type': 'string',
                                                                  'enum': ['preview', 'lookdev', 'final']},
                                               'samples': {'type': 'integer', 'minimum': 1, 'maximum': 4096},
                                               'denoise': {'type': 'boolean'},
                                               'view_transform': {'type': 'string'},
                                               'look': {'type': 'string'},
                                               'exposure': {'type': 'number'},
                                               'gamma': {'type': 'number'},
                                               'capture_inspection': {'type': 'boolean'},
                                               'views': {'type': 'array', 'items': {'type': 'string'}},
                                               'resolution_x': {'type': 'integer', 'minimum': 64, 'maximum': 4096},
                                               'resolution_y': {'type': 'integer', 'minimum': 64, 'maximum': 4096},
                                               'distance_factor': {'type': 'number'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'create_lookdev_turntable_review',
  'order': 1520,
  'groups': ('camera_render', 'advanced_create', 'refinement', 'vehicle', 'product'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'add_light',
  'description': 'Add a light to the current Blender scene. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'light_type': {'type': 'string', 'enum': ['POINT', 'SUN', 'SPOT', 'AREA']},
                                  'name': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'energy': {'type': 'number'},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 3},
                                  'label': {'type': 'string'}},
                   'required': ['light_type', 'name', 'location', 'energy', 'color'],
                   'additionalProperties': False},
  'contract': {'description': 'Add a light object to the live scene',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_light',
  'order': 1560,
  'groups': ('camera_render', 'vehicle'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'add_camera',
  'description': 'Add a camera and make it the active scene camera. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'rotation': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3,
                                               'description': 'Euler rotation in radians'},
                                  'lens': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'location', 'rotation', 'lens'],
                   'additionalProperties': False},
  'contract': {'description': 'Add a camera object and set it as active',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_camera',
  'order': 1570,
  'groups': ('camera_render', 'vehicle'),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'},
 {'name': 'set_active_camera',
  'description': 'Set an existing camera object as the active scene camera. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'camera_name': {'type': 'string'}, 'label': {'type': 'string'}},
                   'required': ['camera_name'],
                   'additionalProperties': False},
  'contract': {'description': 'Set an existing camera object as the active scene camera',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_active_camera',
  'order': 1590,
  'groups': ('camera_render',),
  'exposure': 'catalog',
  'owner': 'camera_render_evidence'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import camera_render_evidence

    camera_render_evidence.register(handler_registry, SPECS)
