"""Canonical tool specifications for the external assets domain."""

from __future__ import annotations

from ..registry import ToolSpec


SKETCHFAB_PROVENANCE_SCHEMA = {
    'type': 'object',
    'properties': {
        'uid': {'type': 'string'},
        'model_name': {'type': 'string'},
        'author': {'type': 'string'},
        'license': {'type': 'string'},
        'model_url': {'type': 'string'},
    },
    'additionalProperties': False,
}


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'list_poly_haven_categories',
  'description': 'List Poly Haven catalog categories for HDRIs, textures, and models. Returns metadata only; it does '
                 'not download or import assets.',
  'input_schema': {'type': 'object',
                   'properties': {'asset_type': {'type': 'string', 'enum': ['all', 'hdris', 'textures', 'models']},
                                  'timeout': {'type': 'integer',
                                              'description': 'HTTP timeout in seconds. Defaults to 15.'}},
                   'additionalProperties': False},
  'contract': {'description': 'List Poly Haven catalog categories for HDRIs, textures, and models without importing '
                              'assets',
               'mutates_scene': False,
               'permissions': ['network'],
               'supports_headless': True,
               'timeout_seconds': 30,
               'input_schema': {'type': 'object',
                                'properties': {'asset_type': {'type': 'string',
                                                              'enum': ['all', 'hdris', 'textures', 'models']},
                                               'timeout': {'type': 'integer',
                                                           'description': 'HTTP timeout in seconds. Defaults to 15.'}},
                                'additionalProperties': False}},
  'handler_key': 'list_poly_haven_categories',
  'order': 1630,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'search_poly_haven_assets',
  'description': "Search Poly Haven's CC0 asset catalog and return source URLs plus API file URLs. Returns metadata "
                 'only; it does not download or import assets.',
  'input_schema': {'type': 'object',
                   'properties': {'query': {'type': 'string',
                                            'description': 'Optional local text filter over returned asset names, ids, '
                                                           'and categories.'},
                                  'asset_type': {'type': 'string', 'enum': ['all', 'hdris', 'textures', 'models']},
                                  'category': {'type': 'string', 'description': 'Optional Poly Haven category slug.'},
                                  'limit': {'type': 'integer',
                                            'description': 'Maximum assets to return. Defaults to 20, max 50.'},
                                  'timeout': {'type': 'integer',
                                              'description': 'HTTP timeout in seconds. Defaults to 15.'}},
                   'additionalProperties': False},
  'contract': {'description': "Search Poly Haven's CC0 asset catalog and return page/file API URLs without downloading "
                              'or importing assets',
               'mutates_scene': False,
               'permissions': ['network'],
               'supports_headless': True,
               'timeout_seconds': 30,
               'input_schema': {'type': 'object',
                                'properties': {'query': {'type': 'string',
                                                         'description': 'Optional local text filter over returned '
                                                                        'asset names, ids, and categories.'},
                                               'asset_type': {'type': 'string',
                                                              'enum': ['all', 'hdris', 'textures', 'models']},
                                               'category': {'type': 'string',
                                                            'description': 'Optional Poly Haven category slug.'},
                                               'limit': {'type': 'integer',
                                                         'description': 'Maximum assets to return. Defaults to 20, max '
                                                                        '50.'},
                                               'timeout': {'type': 'integer',
                                                           'description': 'HTTP timeout in seconds. Defaults to 15.'}},
                                'additionalProperties': False}},
  'handler_key': 'search_poly_haven_assets',
  'order': 1640,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'inspect_poly_haven_asset_files',
  'description': 'Fetch and summarize the available Poly Haven files for one asset, including resolutions, formats, '
                 'sizes, hashes, and include dependencies. Does not download or import.',
  'input_schema': {'type': 'object',
                   'properties': {'asset_id': {'type': 'string'}, 'timeout': {'type': 'integer'}},
                   'required': ['asset_id'],
                   'additionalProperties': False},
  'contract': {'description': "Fetch and summarize Poly Haven's file tree for one asset without downloading or "
                              'importing',
               'mutates_scene': False,
               'permissions': ['network'],
               'supports_headless': True,
               'timeout_seconds': 30,
               'input_schema': {'type': 'object',
                                'properties': {'asset_id': {'type': 'string'}, 'timeout': {'type': 'integer'}},
                                'required': ['asset_id'],
                                'additionalProperties': False}},
  'handler_key': 'inspect_poly_haven_asset_files',
  'order': 1650,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'download_poly_haven_asset',
  'description': 'Synchronous fallback: download and cache selected Poly Haven HDRI, texture, or model files with '
                 'checksum validation. Does not mutate the Blender scene. For normal client workflows, prefer '
                 'start_external_asset_download and poll get_external_asset_job_status.',
  'input_schema': {'type': 'object',
                   'properties': {'asset_id': {'type': 'string'},
                                  'asset_type': {'type': 'string', 'enum': ['', 'all', 'hdris', 'textures', 'models']},
                                  'resolution': {'type': 'string'},
                                  'file_format': {'type': 'string'},
                                  'map_types': {'type': 'array', 'items': {'type': 'string'}},
                                  'include_dependencies': {'type': 'boolean'},
                                  'cache_dir': {'type': 'string'},
                                  'timeout': {'type': 'integer'}},
                   'required': ['asset_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Synchronous fallback: download/cache selected Poly Haven HDRI, texture, or model files '
                              'plus dependencies with checksum validation. Prefer start_external_asset_download for '
                              'normal client workflows.',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['network', 'files:write'],
               'supports_headless': True,
               'timeout_seconds': 300,
               'input_schema': {'type': 'object',
                                'properties': {'asset_id': {'type': 'string'},
                                               'asset_type': {'type': 'string',
                                                              'enum': ['', 'all', 'hdris', 'textures', 'models']},
                                               'resolution': {'type': 'string'},
                                               'file_format': {'type': 'string'},
                                               'map_types': {'type': 'array', 'items': {'type': 'string'}},
                                               'include_dependencies': {'type': 'boolean'},
                                               'cache_dir': {'type': 'string'},
                                               'timeout': {'type': 'integer'}},
                                'required': ['asset_id'],
                                'additionalProperties': False}},
  'handler_key': 'download_poly_haven_asset',
  'order': 1660,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'import_poly_haven_asset',
  'description': 'Synchronous fallback: download/cache and import a Poly Haven asset into Blender preview. HDRIs '
                 'create a world, textures create/assign a material, and models use Blender importers. For normal '
                 'client workflows, use start_external_asset_download, poll get_external_asset_job_status, then '
                 'start_external_asset_import_job.',
  'input_schema': {'type': 'object',
                   'properties': {'asset_id': {'type': 'string'},
                                  'asset_type': {'type': 'string', 'enum': ['', 'all', 'hdris', 'textures', 'models']},
                                  'resolution': {'type': 'string'},
                                  'file_format': {'type': 'string'},
                                  'map_types': {'type': 'array', 'items': {'type': 'string'}},
                                  'target_object_name': {'type': 'string'},
                                  'cache_dir': {'type': 'string'},
                                  'timeout': {'type': 'integer'},
                                  'label': {'type': 'string'},
                                  'allow_duplicate': {'type': 'boolean',
                                                      'description': 'Allow another overlapping copy when this asset is already present.'}},
                   'required': ['asset_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Synchronous fallback: download/cache and import a Poly Haven asset into Blender. For '
                              'normal client workflows, use start_external_asset_download, poll '
                              'get_external_asset_job_status, then start_external_asset_import_job.',
               'mutates_scene': True,
               'requires_live_preview': True,
               'has_side_effects': True,
               'permissions': ['network', 'files:write', 'scene:mutate', 'preview:write'],
               'supports_headless': True,
               'timeout_seconds': 300,
               'input_schema': {'type': 'object',
                                'properties': {'asset_id': {'type': 'string'},
                                               'asset_type': {'type': 'string',
                                                              'enum': ['', 'all', 'hdris', 'textures', 'models']},
                                               'resolution': {'type': 'string'},
                                               'file_format': {'type': 'string'},
                                               'map_types': {'type': 'array', 'items': {'type': 'string'}},
                                               'target_object_name': {'type': 'string'},
                                               'cache_dir': {'type': 'string'},
                                               'timeout': {'type': 'integer'},
                                               'label': {'type': 'string'}},
                                'required': ['asset_id'],
                                'additionalProperties': False}},
  'handler_key': 'import_poly_haven_asset',
  'order': 1670,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'search_sketchfab_models',
  'description': "Search Sketchfab's public model catalog and return viewer, author, license, thumbnail, and "
                 'downloadability metadata. Returns metadata only; it does not download or import assets.',
  'input_schema': {'type': 'object',
                   'properties': {'query': {'type': 'string'},
                                  'downloadable': {'type': 'boolean',
                                                   'description': 'Filter for downloadable models. Defaults to true.'},
                                  'staffpicked': {'type': 'boolean'},
                                  'animated': {'type': 'boolean'},
                                  'limit': {'type': 'integer',
                                            'description': 'Maximum models to return. Defaults to 20, max 50.'},
                                  'timeout': {'type': 'integer',
                                              'description': 'HTTP timeout in seconds. Defaults to 15.'}},
                   'required': ['query'],
                   'additionalProperties': False},
  'contract': {'description': "Search Sketchfab's public model catalog and return viewer/license metadata without "
                              'downloading or importing assets',
               'mutates_scene': False,
               'permissions': ['network'],
               'supports_headless': True,
               'timeout_seconds': 30,
               'input_schema': {'type': 'object',
                                'properties': {'query': {'type': 'string'},
                                               'downloadable': {'type': 'boolean',
                                                                'description': 'Filter for downloadable models. '
                                                                               'Defaults to true.'},
                                               'staffpicked': {'type': 'boolean'},
                                               'animated': {'type': 'boolean'},
                                               'limit': {'type': 'integer',
                                                         'description': 'Maximum models to return. Defaults to 20, max '
                                                                        '50.'},
                                               'timeout': {'type': 'integer',
                                                           'description': 'HTTP timeout in seconds. Defaults to 15.'}},
                                'required': ['query'],
                                'additionalProperties': False}},
  'handler_key': 'search_sketchfab_models',
  'order': 1680,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'download_sketchfab_model',
  'description': 'Synchronous fallback: use a Sketchfab API token to fetch temporary GLTF download info, cache the '
                 'archive, and extract an importable model file. Does not mutate the Blender scene. For normal client '
                 'workflows, prefer start_external_asset_download and poll get_external_asset_job_status.',
  'input_schema': {'type': 'object',
                   'properties': {'uid': {'type': 'string'},
                                  'api_token': {'type': 'string',
                                                'description': 'Optional per-call Sketchfab API token. Redacted in '
                                                               'audit logs.'},
                                  'token_env_var': {'type': 'string',
                                                    'enum': ['SKETCHFAB_API_TOKEN',
                                                             'BLENDER_AGENT_BRIDGE_SKETCHFAB_API_TOKEN'],
                                                    'description': 'Sketchfab API token environment variable to read '
                                                                   'when api_token is omitted. Defaults to '
                                                                   'SKETCHFAB_API_TOKEN and falls back to the '
                                                                   'bridge-specific name.'},
                                  'model_password': {'type': 'string'},
                                  'provenance': SKETCHFAB_PROVENANCE_SCHEMA,
                                  'cache_dir': {'type': 'string'},
                                  'timeout': {'type': 'integer'}},
                   'required': ['uid'],
                   'additionalProperties': False},
  'contract': {'description': 'Synchronous fallback: use a Sketchfab API token to fetch temporary GLTF download info, '
                              'cache the archive, and extract an importable model file. Prefer '
                              'start_external_asset_download for normal client workflows.',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['network', 'files:write'],
               'supports_headless': True,
               'timeout_seconds': 300,
               'input_schema': {'type': 'object',
                                'properties': {'uid': {'type': 'string'},
                                               'api_token': {'type': 'string',
                                                             'description': 'Optional per-call Sketchfab API token. '
                                                                            'Redacted in audit logs.'},
                                               'token_env_var': {'type': 'string',
                                                                 'enum': ['SKETCHFAB_API_TOKEN',
                                                                          'BLENDER_AGENT_BRIDGE_SKETCHFAB_API_TOKEN'],
                                                                 'description': 'Sketchfab API token environment '
                                                                                'variable to read when api_token is '
                                                                                'omitted. Defaults to '
                                                                                'SKETCHFAB_API_TOKEN and falls back to '
                                                                                'the bridge-specific name.'},
                                               'model_password': {'type': 'string'},
                                               'cache_dir': {'type': 'string'},
                                               'timeout': {'type': 'integer'}},
                                'required': ['uid'],
                                'additionalProperties': False}},
  'handler_key': 'download_sketchfab_model',
  'order': 1690,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'import_sketchfab_model',
  'description': 'Synchronous fallback: use a Sketchfab API token to cache a downloadable model archive and import the '
                 'extracted GLTF/GLB file into Blender preview. For normal client workflows, use '
                 'start_external_asset_download, poll get_external_asset_job_status, then '
                 'start_external_asset_import_job.',
  'input_schema': {'type': 'object',
                   'properties': {'uid': {'type': 'string'},
                                  'api_token': {'type': 'string',
                                                'description': 'Optional per-call Sketchfab API token. Redacted in '
                                                               'audit logs.'},
                                  'token_env_var': {'type': 'string',
                                                    'enum': ['SKETCHFAB_API_TOKEN',
                                                             'BLENDER_AGENT_BRIDGE_SKETCHFAB_API_TOKEN'],
                                                    'description': 'Sketchfab API token environment variable to read '
                                                                   'when api_token is omitted. Defaults to '
                                                                   'SKETCHFAB_API_TOKEN and falls back to the '
                                                                   'bridge-specific name.'},
                                  'model_password': {'type': 'string'},
                                  'provenance': SKETCHFAB_PROVENANCE_SCHEMA,
                                  'cache_dir': {'type': 'string'},
                                  'timeout': {'type': 'integer'},
                                  'label': {'type': 'string'},
                                  'allow_duplicate': {'type': 'boolean',
                                                      'description': 'Allow another overlapping copy when this asset is already present.'}},
                   'required': ['uid'],
                   'additionalProperties': False},
  'contract': {'description': 'Synchronous fallback: use a Sketchfab API token to cache a downloadable model archive '
                              'and import the extracted GLTF/GLB file into Blender preview. For normal client '
                              'workflows, use start_external_asset_download, poll get_external_asset_job_status, then '
                              'start_external_asset_import_job.',
               'mutates_scene': True,
               'requires_live_preview': True,
               'has_side_effects': True,
               'permissions': ['network', 'files:write', 'scene:mutate', 'preview:write'],
               'supports_headless': True,
               'timeout_seconds': 300,
               'input_schema': {'type': 'object',
                                'properties': {'uid': {'type': 'string'},
                                               'api_token': {'type': 'string',
                                                             'description': 'Optional per-call Sketchfab API token. '
                                                                            'Redacted in audit logs.'},
                                               'token_env_var': {'type': 'string',
                                                                 'enum': ['SKETCHFAB_API_TOKEN',
                                                                          'BLENDER_AGENT_BRIDGE_SKETCHFAB_API_TOKEN'],
                                                                 'description': 'Sketchfab API token environment '
                                                                                'variable to read when api_token is '
                                                                                'omitted. Defaults to '
                                                                                'SKETCHFAB_API_TOKEN and falls back to '
                                                                                'the bridge-specific name.'},
                                               'model_password': {'type': 'string'},
                                               'cache_dir': {'type': 'string'},
                                               'timeout': {'type': 'integer'},
                                               'label': {'type': 'string'}},
                                'required': ['uid'],
                                'additionalProperties': False}},
  'handler_key': 'import_sketchfab_model',
  'order': 1700,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'start_external_asset_download',
  'description': 'Default client path: start an asynchronous external asset download/cache job for Poly Haven or '
                 'Sketchfab. Use this for any normal asset download/cache or import request. Returns immediately with '
                 'a job id; poll get_external_asset_job_status until completed or failed, then queue scene import with '
                 'start_external_asset_import_job.',
  'input_schema': {'type': 'object',
                   'properties': {'provider': {'type': 'string', 'enum': ['poly_haven', 'sketchfab']},
                                  'asset_id': {'type': 'string', 'description': 'Poly Haven asset id.'},
                                  'uid': {'type': 'string', 'description': 'Sketchfab model uid.'},
                                  'asset_type': {'type': 'string', 'enum': ['', 'all', 'hdris', 'textures', 'models']},
                                  'resolution': {'type': 'string'},
                                  'file_format': {'type': 'string'},
                                  'map_types': {'type': 'array', 'items': {'type': 'string'}},
                                  'include_dependencies': {'type': 'boolean'},
                                  'api_token': {'type': 'string',
                                                'description': 'Optional per-call Sketchfab API token. Redacted in '
                                                               'audit logs and not persisted to job metadata.'},
                                  'token_env_var': {'type': 'string',
                                                    'enum': ['SKETCHFAB_API_TOKEN',
                                                             'BLENDER_AGENT_BRIDGE_SKETCHFAB_API_TOKEN'],
                                                    'description': 'Sketchfab API token environment variable to read '
                                                                   'when api_token is omitted.'},
                                  'model_password': {'type': 'string'},
                                  'provenance': SKETCHFAB_PROVENANCE_SCHEMA,
                                  'cache_dir': {'type': 'string'},
                                  'timeout': {'type': 'integer'},
                                  'job_name': {'type': 'string'},
                                  'note': {'type': 'string'}},
                   'required': ['provider'],
                   'additionalProperties': False},
  'contract': {'description': 'Default client path for asset downloads/imports: start an asynchronous external asset '
                              'download/cache job for Poly Haven or Sketchfab and return immediately with a job id',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['network', 'files:write'],
               'supports_headless': True,
               'returns_background_job': True,
               'timeout_seconds': 30,
               'duration_hint': 'Returns quickly; the background asset job may continue downloading, extracting, and '
                                'validating cache files. Poll get_external_asset_job_status until completed or failed '
                                'before starting a queued import.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 2,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_external_asset_job_status',
                                    'message': 'If startup times out, check bridge status and then poll '
                                               'get_external_asset_job_status before starting another asset job.'},
               'input_schema': {'type': 'object',
                                'properties': {'provider': {'type': 'string', 'enum': ['poly_haven', 'sketchfab']},
                                               'asset_id': {'type': 'string', 'description': 'Poly Haven asset id.'},
                                               'uid': {'type': 'string', 'description': 'Sketchfab model uid.'},
                                               'asset_type': {'type': 'string',
                                                              'enum': ['', 'all', 'hdris', 'textures', 'models']},
                                               'resolution': {'type': 'string'},
                                               'file_format': {'type': 'string'},
                                               'map_types': {'type': 'array', 'items': {'type': 'string'}},
                                               'include_dependencies': {'type': 'boolean'},
                                               'api_token': {'type': 'string',
                                                             'description': 'Optional per-call Sketchfab API token. '
                                                                            'Redacted in audit logs and not persisted '
                                                                            'to job metadata.'},
                                               'token_env_var': {'type': 'string',
                                                                 'enum': ['SKETCHFAB_API_TOKEN',
                                                                          'BLENDER_AGENT_BRIDGE_SKETCHFAB_API_TOKEN'],
                                                                 'description': 'Sketchfab API token environment '
                                                                                'variable to read when api_token is '
                                                                                'omitted.'},
                                               'model_password': {'type': 'string'},
                                               'cache_dir': {'type': 'string'},
                                               'timeout': {'type': 'integer'},
                                               'job_name': {'type': 'string'},
                                               'note': {'type': 'string'}},
                                'required': ['provider'],
                                'additionalProperties': False}},
  'handler_key': 'start_external_asset_download',
  'order': 1710,
  'groups': ('external_assets',),
  'exposure': 'compact_direct',
  'owner': 'external_assets'},
 {'name': 'get_external_asset_job_status',
  'description': 'Poll an asynchronous external asset download/cache job for status, progress, cached manifest path, '
                 'and import readiness. When completed and the user wants scene import, call '
                 'start_external_asset_import_job.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Poll an asynchronous external asset download/cache job for status, progress, cached '
                              'manifest path, and import readiness; when completed, use '
                              'start_external_asset_import_job for scene import',
               'mutates_scene': False,
               'permissions': ['files:read'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'get_external_asset_job_status',
  'order': 1720,
  'groups': ('external_assets',),
  'exposure': 'compact_direct',
  'owner': 'external_assets'},
 {'name': 'cancel_external_asset_job',
  'description': 'Cancel an asynchronous external asset download/cache job. Subprocess jobs are terminated; in-process '
                 'compatibility jobs stop cooperatively.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Cancel an asynchronous external asset download/cache job; subprocess jobs are '
                              'terminated and in-process compatibility jobs stop cooperatively',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['files:write'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'cancel_external_asset_job',
  'order': 1730,
  'groups': ('external_assets',),
  'exposure': 'compact_direct',
  'owner': 'external_assets'},
 {'name': 'import_external_asset_job_result',
  'description': 'Synchronous fallback: import a completed external asset download/cache job result into Blender '
                 'preview using the cached manifest. For normal client workflows, prefer '
                 'start_external_asset_import_job and poll get_external_asset_import_job_status.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'},
                                  'target_object_name': {'type': 'string'},
                                  'label': {'type': 'string'},
                                  'allow_duplicate': {'type': 'boolean'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Synchronous fallback: import a completed external asset download/cache job result into '
                              'Blender preview using the cached manifest. Prefer start_external_asset_import_job for '
                              'normal client workflows.',
               'mutates_scene': True,
               'requires_live_preview': True,
               'has_side_effects': True,
               'permissions': ['scene:read', 'scene:mutate', 'preview:write', 'files:read'],
               'supports_headless': True,
               'timeout_seconds': 300,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'},
                                               'target_object_name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'import_external_asset_job_result',
  'order': 1740,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'start_external_asset_import_job',
  'description': 'Default client path after a completed asset download/cache job: queue Blender main-thread import and '
                 'return immediately with a pollable import job id. Poll get_external_asset_import_job_status until '
                 'completed or failed.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string', 'description': 'Legacy alias for source_job_id.'},
                                  'source_job_id': {'type': 'string',
                                                    'description': 'Completed external asset download/cache job id.'},
                                  'manifest_path': {'type': 'string',
                                                    'description': 'Optional cached asset manifest path when no '
                                                                   'source_job_id is supplied.'},
                                  'target_object_name': {'type': 'string'},
                                  'label': {'type': 'string'},
                                  'allow_duplicate': {'type': 'boolean'}},
                   'anyOf': [{'required': ['source_job_id']},
                             {'required': ['job_id']},
                             {'required': ['manifest_path']}],
                   'additionalProperties': False},
  'contract': {'description': 'Default client path after asset download completion: queue a completed external asset '
                              'download/cache job result for main-thread Blender import and return immediately with a '
                              'pollable import job id',
               'mutates_scene': True,
               'requires_live_preview': True,
               'has_side_effects': True,
               'returns_background_job': True,
               'permissions': ['scene:read', 'scene:mutate', 'preview:write', 'files:read', 'files:write'],
               'supports_headless': True,
               'timeout_seconds': 30,
               'duration_hint': "Returns quickly; the queued import runs later on Blender's main thread and may "
                                'briefly keep Blender busy while importers execute. Poll '
                                'get_external_asset_import_job_status until completed or failed before reporting '
                                'success.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 2,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_external_asset_import_job_status',
                                    'message': 'If startup times out, check bridge status and then poll '
                                               'get_external_asset_import_job_status before starting another import '
                                               'job.'},
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string',
                                                          'description': 'Legacy alias for source_job_id.'},
                                               'source_job_id': {'type': 'string',
                                                                 'description': 'Completed external asset '
                                                                                'download/cache job id.'},
                                               'manifest_path': {'type': 'string',
                                                                 'description': 'Optional cached asset manifest path '
                                                                                'when no source_job_id is supplied.'},
                                               'target_object_name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'anyOf': [{'required': ['source_job_id']},
                                          {'required': ['job_id']},
                                          {'required': ['manifest_path']}],
                                'additionalProperties': False}},
  'handler_key': 'start_external_asset_import_job',
  'order': 1750,
  'groups': ('external_assets',),
  'exposure': 'compact_direct',
  'owner': 'external_assets'},
 {'name': 'get_external_asset_import_job_status',
  'description': 'Poll a queued external asset import job for queued/running/completed/failed/cancelled status and '
                 'import result details. Use this after start_external_asset_import_job before reporting import '
                 'success.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Poll a queued external asset import job for queued, running, completed, failed, or '
                              'cancelled status and import result details',
               'mutates_scene': False,
               'permissions': ['files:read'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'get_external_asset_import_job_status',
  'order': 1760,
  'groups': ('external_assets',),
  'exposure': 'compact_direct',
  'owner': 'external_assets'},
 {'name': 'cancel_external_asset_import_job',
  'description': "Cancel a queued external asset import job. Imports already running on Blender's main thread cannot "
                 'be interrupted safely.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': "Cancel a queued external asset import job; imports already running on Blender's main "
                              'thread cannot be interrupted safely',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['files:write'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'cancel_external_asset_import_job',
  'order': 1770,
  'groups': ('external_assets',),
  'exposure': 'compact_direct',
  'owner': 'external_assets'},
 {'name': 'delete_external_asset_job',
  'description': 'Delete completed, failed, or cancelled external asset job metadata/log files. Dry-run by default.',
  'input_schema': {'type': 'object',
                   'properties': {'job_id': {'type': 'string'}, 'dry_run': {'type': 'boolean'}},
                   'required': ['job_id'],
                   'additionalProperties': False},
  'contract': {'description': 'Delete completed, failed, or cancelled external asset job metadata/log files; dry-run '
                              'by default',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['files:write'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'job_id': {'type': 'string'}, 'dry_run': {'type': 'boolean'}},
                                'required': ['job_id'],
                                'additionalProperties': False}},
  'handler_key': 'delete_external_asset_job',
  'order': 1780,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'get_external_asset_cache_diagnostics',
  'description': 'Report cached/imported external assets, providers, licenses, source URLs, files, and imported '
                 'Blender data-block names.',
  'input_schema': {'type': 'object',
                   'properties': {'cache_dir': {'type': 'string'}, 'max_assets': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Report cached/imported external assets, providers, licenses, source URLs, files, and '
                              'imported Blender data-block names',
               'mutates_scene': False,
               'permissions': ['files:read'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'cache_dir': {'type': 'string'}, 'max_assets': {'type': 'integer'}},
                                'additionalProperties': False}},
  'handler_key': 'get_external_asset_cache_diagnostics',
  'order': 1790,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'},
 {'name': 'prune_external_asset_cache',
  'description': 'Preview or delete old/excess external asset cache directories by age or total size. Dry-run by '
                 'default.',
  'input_schema': {'type': 'object',
                   'properties': {'cache_dir': {'type': 'string'},
                                  'max_age_days': {'type': 'integer'},
                                  'max_total_bytes': {'type': 'integer'},
                                  'dry_run': {'type': 'boolean'},
                                  'include_imported': {'type': 'boolean'}},
                   'additionalProperties': False},
  'contract': {'description': 'Preview or delete old/excess external asset cache directories by age or total size; '
                              'dry-run by default',
               'mutates_scene': False,
               'has_side_effects': True,
               'destructive': True,
               'risk_level': 'destructive',
               'permissions': ['files:read', 'files:write'],
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'cache_dir': {'type': 'string'},
                                               'max_age_days': {'type': 'integer'},
                                               'max_total_bytes': {'type': 'integer'},
                                               'dry_run': {'type': 'boolean'},
                                               'include_imported': {'type': 'boolean'}},
                                'additionalProperties': False}},
  'handler_key': 'prune_external_asset_cache',
  'order': 1800,
  'groups': ('external_assets',),
  'exposure': 'catalog',
  'owner': 'external_assets'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import external_assets

    external_assets.register(handler_registry, SPECS)
