"""Canonical tool specifications for the materials nodes domain."""

from __future__ import annotations

from ..registry import ToolSpec


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'get_material_node_details',
  'description': 'Fetch read-only material node and link details for named or selected-object materials.',
  'input_schema': {'type': 'object',
                   'properties': {'material_names': {'type': 'array',
                                                     'items': {'type': 'string'},
                                                     'description': 'Optional material names to inspect'},
                                  'selected_only': {'type': 'boolean',
                                                    'description': 'Use materials on selected objects when '
                                                                   'material_names is empty'},
                                  'max_materials': {'type': 'integer', 'description': 'Maximum materials to return'},
                                  'max_nodes': {'type': 'integer', 'description': 'Maximum nodes per material'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return material node, socket, and link details', 'mutates_scene': False},
  'handler_key': 'get_material_node_details',
  'order': 440,
  'groups': ('materials',),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'get_geometry_nodes_details',
  'description': 'Fetch read-only Geometry Nodes modifier and node-group summaries for named objects or all objects '
                 'with Geometry Nodes.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'max_objects': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return Geometry Nodes modifier and node-group summaries', 'mutates_scene': False},
  'handler_key': 'get_geometry_nodes_details',
  'order': 450,
  'groups': ('deep_inspect', 'advanced_workflow', 'procedural_3d', 'geometry_nodes'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'get_shader_nodes_details',
  'description': 'Fetch read-only shader node-tree, node, link, and driver summaries for materials.',
  'input_schema': {'type': 'object',
                   'properties': {'material_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'max_materials': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return shader node tree, node, link, and driver summaries', 'mutates_scene': False},
  'handler_key': 'get_shader_nodes_details',
  'order': 460,
  'groups': ('materials', 'deep_inspect'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'assign_material_to_selected',
  'description': 'Create or update a material and assign it to selected mesh objects. Applies immediately with preview '
                 'revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string', 'description': 'Material name'},
                                  'color': {'type': 'array',
                                            'items': {'type': 'number'},
                                            'minItems': 3,
                                            'maxItems': 4,
                                            'description': 'RGBA color components from 0 to 1'},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'color'],
                   'additionalProperties': False},
  'contract': {'description': 'Create or update a material and assign it to selected mesh objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'assign_material_to_selected',
  'order': 600,
  'groups': ('basic_edit', 'materials'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'assign_emission_material_to_selected',
  'description': 'Create a new emission material node setup and assign it to selected mesh objects. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string', 'description': 'Material name'},
                                  'color': {'type': 'array',
                                            'items': {'type': 'number'},
                                            'minItems': 3,
                                            'maxItems': 4,
                                            'description': 'RGBA color components from 0 to 1'},
                                  'strength': {'type': 'number', 'description': 'Emission strength'},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'color', 'strength'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a new emission material node setup and assign it to selected mesh objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'assign_emission_material_to_selected',
  'order': 610,
  'groups': ('materials',),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'create_shader_material',
  'description': 'Create or update a Principled BSDF material from explicit values or bounded presets such as brushed '
                 'metal, brushed chrome, painted enamel, matte plastic, clear glass, emissive accent, or matte '
                 'ceramic. Optionally assigns it to selected mesh objects and applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'preset': {'type': 'string',
                                             'enum': ['custom',
                                                      'brushed_metal',
                                                      'brushed_chrome',
                                                      'painted_enamel',
                                                      'matte_plastic',
                                                      'clear_glass',
                                                      'emissive_accent',
                                                      'matte_ceramic',
                                                      'rubber_black',
                                                      'warm_wood',
                                                      'screen_glow']},
                                  'base_color': {'type': 'array',
                                                 'items': {'type': 'number'},
                                                 'minItems': 3,
                                                 'maxItems': 4},
                                  'metallic': {'type': 'number'},
                                  'roughness': {'type': 'number'},
                                  'alpha': {'type': 'number'},
                                  'emission_color': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 4},
                                  'emission_strength': {'type': 'number'},
                                  'assign_to_selected': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create or update a Principled BSDF material from explicit values or bounded presets and '
                              'optionally assign it',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'name': {'type': 'string'},
                                               'preset': {'type': 'string',
                                                          'enum': ['custom',
                                                                   'brushed_metal',
                                                                   'brushed_chrome',
                                                                   'painted_enamel',
                                                                   'matte_plastic',
                                                                   'clear_glass',
                                                                   'emissive_accent',
                                                                   'matte_ceramic',
                                                                   'rubber_black',
                                                                   'warm_wood',
                                                                   'screen_glow']},
                                               'base_color': {'type': 'array',
                                                              'items': {'type': 'number'},
                                                              'minItems': 3,
                                                              'maxItems': 4},
                                               'metallic': {'type': 'number'},
                                               'roughness': {'type': 'number'},
                                               'alpha': {'type': 'number'},
                                               'emission_color': {'type': 'array',
                                                                  'items': {'type': 'number'},
                                                                  'minItems': 3,
                                                                  'maxItems': 4},
                                               'emission_strength': {'type': 'number'},
                                               'assign_to_selected': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'create_shader_material',
  'order': 680,
  'groups': ('materials', 'advanced_create', 'vehicle'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'create_image_texture_material',
  'description': 'Create or update a Principled BSDF material from exact local image/PBR map paths such as base color, '
                 'roughness, metallic, normal, alpha, emission, AO, packed ARM/ORM, or bump. Optionally assigns it to '
                 'selected or named mesh objects and applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'base_color_path': {'type': 'string'},
                                  'roughness_path': {'type': 'string'},
                                  'metallic_path': {'type': 'string'},
                                  'normal_path': {'type': 'string'},
                                  'alpha_path': {'type': 'string'},
                                  'emission_path': {'type': 'string'},
                                  'ambient_occlusion_path': {'type': 'string'},
                                  'arm_path': {'type': 'string'},
                                  'orm_path': {'type': 'string'},
                                  'bump_path': {'type': 'string'},
                                  'displacement_path': {'type': 'string'},
                                  'base_color': {'type': 'array',
                                                 'items': {'type': 'number'},
                                                 'minItems': 3,
                                                 'maxItems': 4},
                                  'metallic': {'type': 'number'},
                                  'roughness': {'type': 'number'},
                                  'alpha': {'type': 'number'},
                                  'emission_strength': {'type': 'number'},
                                  'normal_strength': {'type': 'number'},
                                  'bump_strength': {'type': 'number'},
                                  'bump_distance': {'type': 'number'},
                                  'uv_map_name': {'type': 'string'},
                                  'replace_existing_links': {'type': 'boolean'},
                                  'assign_to_objects': {'type': 'boolean'},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create or update a Principled material from local image/PBR maps, packed ARM/ORM maps, '
                              'AO, and bump maps and optionally assign it',
               'mutates_scene': True,
               'requires_live_preview': True,
               'requires_user_path': True,
               'path_policy': 'Use exact local image paths supplied by the user, a file picker, or a prior asset/cache '
                              'tool; do not invent paths.',
               'input_schema': {'type': 'object',
                                'properties': {'name': {'type': 'string'},
                                               'base_color_path': {'type': 'string'},
                                               'roughness_path': {'type': 'string'},
                                               'metallic_path': {'type': 'string'},
                                               'normal_path': {'type': 'string'},
                                               'alpha_path': {'type': 'string'},
                                               'emission_path': {'type': 'string'},
                                               'ambient_occlusion_path': {'type': 'string'},
                                               'arm_path': {'type': 'string'},
                                               'orm_path': {'type': 'string'},
                                               'bump_path': {'type': 'string'},
                                               'displacement_path': {'type': 'string'},
                                               'base_color': {'type': 'array',
                                                              'items': {'type': 'number'},
                                                              'minItems': 3,
                                                              'maxItems': 4},
                                               'metallic': {'type': 'number'},
                                               'roughness': {'type': 'number'},
                                               'alpha': {'type': 'number'},
                                               'emission_strength': {'type': 'number'},
                                               'normal_strength': {'type': 'number'},
                                               'bump_strength': {'type': 'number'},
                                               'bump_distance': {'type': 'number'},
                                               'uv_map_name': {'type': 'string'},
                                               'replace_existing_links': {'type': 'boolean'},
                                               'assign_to_objects': {'type': 'boolean'},
                                               'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'create_image_texture_material',
  'order': 690,
  'groups': ('materials',),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'inspect_material_setup',
  'description': 'Read-only material quality gate for texture image files, PBR map color spaces, shader graph links, '
                 'and UV map assignments. Use before repair or render signoff for textured materials.',
  'input_schema': {'type': 'object',
                   'properties': {'material_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'require_uv_maps': {'type': 'boolean'},
                                  'expected_uv_map_name': {'type': 'string'},
                                  'max_materials': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Read-only material quality gate for texture image files, PBR map color spaces, shader '
                              'links, and UV map assignments',
               'mutates_scene': False,
               'input_schema': {'type': 'object',
                                'properties': {'material_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'require_uv_maps': {'type': 'boolean'},
                                               'expected_uv_map_name': {'type': 'string'},
                                               'max_materials': {'type': 'integer'}},
                                'additionalProperties': False}},
  'handler_key': 'inspect_material_setup',
  'order': 700,
  'groups': ('materials',),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'repair_material_setup',
  'description': 'Repair bounded material setup issues by fixing image texture color spaces and relinking image '
                 'texture vector inputs to a known UV map. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'material_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'uv_map_name': {'type': 'string'},
                                  'fix_color_spaces': {'type': 'boolean'},
                                  'reconnect_uv_maps': {'type': 'boolean'},
                                  'max_materials': {'type': 'integer'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Repair bounded material setup issues by fixing image color spaces and relinking image '
                              'texture vectors to a UV map',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'material_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'uv_map_name': {'type': 'string'},
                                               'fix_color_spaces': {'type': 'boolean'},
                                               'reconnect_uv_maps': {'type': 'boolean'},
                                               'max_materials': {'type': 'integer'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'repair_material_setup',
  'order': 710,
  'groups': ('materials',),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'bake_maps',
  'description': 'Bake bounded material maps such as ambient occlusion, normal, and base color/diffuse to PNG files '
                 'from selected or named mesh objects. Use after UV unwrap/material setup and before custom bake '
                 'Python.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'map_types': {'type': 'array',
                                                'items': {'type': 'string',
                                                          'enum': ['ambient_occlusion',
                                                                   'ao',
                                                                   'normal',
                                                                   'base_color',
                                                                   'diffuse',
                                                                   'albedo']}},
                                  'output_dir': {'type': 'string',
                                                 'description': 'Optional exact local output directory from the user, '
                                                                'file picker, or prior artifact. Omit to write under '
                                                                'the project/session capture directory; do not invent '
                                                                'custom paths.'},
                                  'resolution': {'type': 'integer', 'minimum': 16, 'maximum': 4096},
                                  'margin': {'type': 'integer', 'minimum': 0, 'maximum': 128},
                                  'samples': {'type': 'integer', 'minimum': 1, 'maximum': 4096},
                                  'uv_map_name': {'type': 'string'},
                                  'overwrite': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Bake bounded texture maps such as AO, normal, and base color from mesh materials to PNG '
                              'files',
               'mutates_scene': True,
               'requires_live_preview': True,
               'requires_user_path': True,
               'path_policy': 'Omit output_dir to write under the project/session capture directory. If output_dir is '
                              'supplied, it must be an exact local directory from the user, a file picker, or a prior '
                              'artifact; do not invent paths.',
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'map_types': {'type': 'array',
                                                             'items': {'type': 'string',
                                                                       'enum': ['ambient_occlusion',
                                                                                'ao',
                                                                                'normal',
                                                                                'base_color',
                                                                                'diffuse',
                                                                                'albedo']}},
                                               'output_dir': {'type': 'string',
                                                              'description': 'Optional exact local output directory. '
                                                                             'Omit to use the project/session capture '
                                                                             'directory; do not invent custom paths.'},
                                               'resolution': {'type': 'integer', 'minimum': 16, 'maximum': 4096},
                                               'margin': {'type': 'integer', 'minimum': 0, 'maximum': 128},
                                               'samples': {'type': 'integer', 'minimum': 1, 'maximum': 4096},
                                               'uv_map_name': {'type': 'string'},
                                               'overwrite': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'bake_maps',
  'order': 720,
  'groups': ('materials',),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'create_procedural_texture_material',
  'description': 'Create or update a bounded procedural Principled material using noise, voronoi, wave, or checker '
                 'texture nodes with optional ColorRamp and bump. Use this for procedural stone, marble, wood, '
                 'cellular, fabric, or musgrave-style texture requests before custom shader-node Python.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'preset': {'type': 'string',
                                             'enum': ['custom',
                                                      'stone_noise',
                                                      'marble_noise',
                                                      'wood_wave',
                                                      'cellular_voronoi',
                                                      'fabric_checker']},
                                  'texture_type': {'type': 'string', 'enum': ['noise', 'voronoi', 'wave', 'checker']},
                                  'color_a': {'type': 'array',
                                              'items': {'type': 'number'},
                                              'minItems': 3,
                                              'maxItems': 4},
                                  'color_b': {'type': 'array',
                                              'items': {'type': 'number'},
                                              'minItems': 3,
                                              'maxItems': 4},
                                  'scale': {'type': 'number'},
                                  'detail': {'type': 'number'},
                                  'texture_roughness': {'type': 'number'},
                                  'distortion': {'type': 'number'},
                                  'randomness': {'type': 'number'},
                                  'metallic': {'type': 'number'},
                                  'material_roughness': {'type': 'number'},
                                  'alpha': {'type': 'number'},
                                  'bump_strength': {'type': 'number'},
                                  'bump_distance': {'type': 'number'},
                                  'wave_type': {'type': 'string', 'enum': ['BANDS', 'RINGS']},
                                  'replace_existing_links': {'type': 'boolean'},
                                  'assign_to_objects': {'type': 'boolean'},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create or update a bounded procedural Principled material from noise, voronoi, wave, or '
                              'checker texture nodes',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'name': {'type': 'string'},
                                               'preset': {'type': 'string',
                                                          'enum': ['custom',
                                                                   'stone_noise',
                                                                   'marble_noise',
                                                                   'wood_wave',
                                                                   'cellular_voronoi',
                                                                   'fabric_checker']},
                                               'texture_type': {'type': 'string',
                                                                'enum': ['noise', 'voronoi', 'wave', 'checker']},
                                               'color_a': {'type': 'array',
                                                           'items': {'type': 'number'},
                                                           'minItems': 3,
                                                           'maxItems': 4},
                                               'color_b': {'type': 'array',
                                                           'items': {'type': 'number'},
                                                           'minItems': 3,
                                                           'maxItems': 4},
                                               'scale': {'type': 'number'},
                                               'detail': {'type': 'number'},
                                               'texture_roughness': {'type': 'number'},
                                               'distortion': {'type': 'number'},
                                               'randomness': {'type': 'number'},
                                               'metallic': {'type': 'number'},
                                               'material_roughness': {'type': 'number'},
                                               'alpha': {'type': 'number'},
                                               'bump_strength': {'type': 'number'},
                                               'bump_distance': {'type': 'number'},
                                               'wave_type': {'type': 'string', 'enum': ['BANDS', 'RINGS']},
                                               'replace_existing_links': {'type': 'boolean'},
                                               'assign_to_objects': {'type': 'boolean'},
                                               'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'create_procedural_texture_material',
  'order': 730,
  'groups': ('materials', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'uv_unwrap',
  'description': 'Create or update preview-safe UV coordinate maps on mesh objects using bounded deterministic smart, '
                 'cube, or planar projection. Applies immediately with mesh-data preview rollback.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'method': {'type': 'string',
                                             'enum': ['smart_project', 'cube_project', 'planar_project']},
                                  'uv_map_name': {'type': 'string'},
                                  'replace_existing': {'type': 'boolean'},
                                  'margin': {'type': 'number'},
                                  'pack_islands': {'type': 'boolean'},
                                  'projection_axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create or update preview-safe UV coordinate maps on mesh objects using bounded '
                              'deterministic projection',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'method': {'type': 'string',
                                                          'enum': ['smart_project', 'cube_project', 'planar_project']},
                                               'uv_map_name': {'type': 'string'},
                                               'replace_existing': {'type': 'boolean'},
                                               'margin': {'type': 'number'},
                                               'pack_islands': {'type': 'boolean'},
                                               'projection_axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'uv_unwrap',
  'order': 740,
  'groups': ('basic_edit', 'materials', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'mark_uv_seams',
  'description': 'Mark or clear preview-safe UV seams on mesh objects using bounded boundary and face-angle rules. Use '
                 'before uv_unwrap when the user asks for seams, hard-edge seams, or texture-ready unwrap preparation.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'mode': {'type': 'string',
                                           'enum': ['sharp_angle', 'boundary', 'sharp_and_boundary', 'clear']},
                                  'angle_degrees': {'type': 'number'},
                                  'include_boundary': {'type': 'boolean'},
                                  'clear_existing': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Mark or clear bounded UV seams on mesh objects by boundary edges or face-angle '
                              'threshold',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'mode': {'type': 'string',
                                                        'enum': ['sharp_angle',
                                                                 'boundary',
                                                                 'sharp_and_boundary',
                                                                 'clear']},
                                               'angle_degrees': {'type': 'number'},
                                               'include_boundary': {'type': 'boolean'},
                                               'clear_existing': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'mark_uv_seams',
  'order': 750,
  'groups': ('basic_edit', 'materials', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'inspect_uv_layout',
  'description': 'Read-only UV layout quality gate for missing UVs, near-zero area, possible overlapping face bounds, '
                 'seam counts, layout stats, and unapplied-scale warnings. max_overlap_pairs=0 disables the overlap '
                 'heuristic.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'include_children': {'type': 'boolean'},
                                  'uv_map_name': {'type': 'string'},
                                  'max_objects': {'type': 'integer'},
                                  'max_overlap_pairs': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Inspect mesh UV maps for missing coordinates, near-zero area, possible overlap bounds, '
                              'seam counts, layout stats, and scale warnings. max_overlap_pairs=0 disables overlap '
                              'scanning',
               'mutates_scene': False,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'include_children': {'type': 'boolean'},
                                               'uv_map_name': {'type': 'string'},
                                               'max_objects': {'type': 'integer'},
                                               'max_overlap_pairs': {'type': 'integer'}},
                                'additionalProperties': False}},
  'handler_key': 'inspect_uv_layout',
  'order': 760,
  'groups': ('basic_edit', 'materials', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'add_geometry_nodes_modifier',
  'description': 'Add a valid Geometry Nodes modifier and starter node group to selected mesh objects. Templates '
                 'include passthrough, transform, join geometry, set position, and subdivide mesh. Applies immediately '
                 'with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'node_group_name': {'type': 'string'},
                                  'template': {'type': 'string',
                                               'enum': ['passthrough',
                                                        'transform',
                                                        'join_geometry',
                                                        'set_position',
                                                        'subdivide_mesh']},
                                  'selected_only': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add a valid Geometry Nodes modifier and starter node group',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'name': {'type': 'string'},
                                               'node_group_name': {'type': 'string'},
                                               'template': {'type': 'string',
                                                            'enum': ['passthrough',
                                                                     'transform',
                                                                     'join_geometry',
                                                                     'set_position',
                                                                     'subdivide_mesh']},
                                               'selected_only': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'add_geometry_nodes_modifier',
  'order': 770,
  'groups': ('advanced_create', 'procedural_3d', 'geometry_nodes'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'add_window_materials',
  'description': 'Create/update a translucent glass material, assign it to window-like objects, and optionally create '
                 'simple window panels around a target mesh. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'material_name': {'type': 'string'},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 4},
                                  'create_panels': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': "Create glass material and optional window panels for a mesh object's bounds",
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_window_materials',
  'order': 1430,
  'groups': ('materials', 'refinement', 'vehicle'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'},
 {'name': 'create_material_palette',
  'description': 'Create a bounded production material palette, optional swatch cubes, and optional assignment to '
                 'selected mesh objects. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'palette_name': {'type': 'string'},
                                  'palette': {'type': 'string', 'enum': ['product_neutral', 'automotive', 'cinematic']},
                                  'create_swatches': {'type': 'boolean'},
                                  'assign_to_selected': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create a bounded material palette and optional swatch objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_material_palette',
  'order': 1500,
  'groups': ('advanced_create', 'refinement', 'vehicle', 'product'),
  'exposure': 'catalog',
  'owner': 'materials_nodes'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import materials_nodes

    materials_nodes.register(handler_registry, SPECS)
