"""Canonical tool specifications for the modeling domain."""

from __future__ import annotations

from ..registry import ToolSpec


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'edit_mesh',
  'description': 'Apply one bounded destructive mesh edit to selected or named single-user mesh objects with mesh-data '
                 'snapshot rollback. Supports face extrusion, face inset, bounded planar loop cut, planar knife cut, '
                 'boundary-loop bridge, dissolve-degenerate, merge-by-distance, and proportional vertex edit.',
  'input_schema': {'type': 'object',
                   'properties': {'operation': {'type': 'string',
                                                'enum': ['extrude_faces',
                                                         'inset_faces',
                                                         'merge_by_distance',
                                                         'dissolve_degenerate',
                                                         'bridge_boundary_loops',
                                                         'loop_cut',
                                                         'knife_cut',
                                                         'proportional_edit']},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'face_scope': {'type': 'string',
                                                 'enum': ['ALL', 'TOP', 'BOTTOM', 'LEFT', 'RIGHT', 'FRONT', 'BACK']},
                                  'direction': {'type': 'string', 'enum': ['NORMAL', 'AXIS', 'X', 'Y', 'Z']},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'distance': {'type': 'number'},
                                  'inset_thickness': {'type': 'number'},
                                  'inset_depth': {'type': 'number'},
                                  'merge_distance': {'type': 'number'},
                                  'loop_cuts': {'type': 'integer',
                                                'minimum': 1,
                                                'maximum': 32,
                                                'description': 'Number of evenly spaced loop planes for loop_cut.'},
                                  'cut_axis': {'type': 'string',
                                               'enum': ['X', 'Y', 'Z'],
                                               'description': 'Plane normal axis for knife_cut and loop_cut.'},
                                  'cut_position': {'type': 'number',
                                                   'description': 'Explicit plane position for knife_cut.'},
                                  'proportional_center': {'type': 'array',
                                                          'items': {'type': 'number'},
                                                          'minItems': 3,
                                                          'maxItems': 3},
                                  'proportional_radius': {'type': 'number'},
                                  'proportional_falloff': {'type': 'string',
                                                           'enum': ['SMOOTH',
                                                                    'LINEAR',
                                                                    'CONSTANT',
                                                                    'SHARP',
                                                                    'ROOT',
                                                                    'SPHERE']},
                                  'allow_shape_keys': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Apply one bounded destructive mesh edit, including bounded planar loop cuts, with '
                              'mesh-data snapshot rollback',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'operation': {'type': 'string',
                                                             'enum': ['extrude_faces',
                                                                      'inset_faces',
                                                                      'merge_by_distance',
                                                                      'dissolve_degenerate',
                                                                      'bridge_boundary_loops',
                                                                      'loop_cut',
                                                                      'knife_cut',
                                                                      'proportional_edit']},
                                               'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'face_scope': {'type': 'string',
                                                              'enum': ['ALL',
                                                                       'TOP',
                                                                       'BOTTOM',
                                                                       'LEFT',
                                                                       'RIGHT',
                                                                       'FRONT',
                                                                       'BACK']},
                                               'direction': {'type': 'string',
                                                             'enum': ['NORMAL', 'AXIS', 'X', 'Y', 'Z']},
                                               'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                               'distance': {'type': 'number'},
                                               'inset_thickness': {'type': 'number'},
                                               'inset_depth': {'type': 'number'},
                                               'merge_distance': {'type': 'number'},
                                               'loop_cuts': {'type': 'integer',
                                                             'minimum': 1,
                                                             'maximum': 32,
                                                             'description': 'Number of evenly spaced loop planes for '
                                                                            'loop_cut.'},
                                               'cut_axis': {'type': 'string',
                                                            'enum': ['X', 'Y', 'Z'],
                                                            'description': 'Plane normal axis for knife_cut and '
                                                                           'loop_cut.'},
                                               'cut_position': {'type': 'number',
                                                                'description': 'Explicit plane position for '
                                                                               'knife_cut.'},
                                               'proportional_center': {'type': 'array',
                                                                       'items': {'type': 'number'},
                                                                       'minItems': 3,
                                                                       'maxItems': 3},
                                               'proportional_radius': {'type': 'number'},
                                               'proportional_falloff': {'type': 'string',
                                                                        'enum': ['SMOOTH',
                                                                                 'LINEAR',
                                                                                 'CONSTANT',
                                                                                 'SHARP',
                                                                                 'ROOT',
                                                                                 'SPHERE']},
                                               'allow_shape_keys': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'edit_mesh',
  'order': 650,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'inspect_modeling_quality',
  'description': 'Read-only modeling quality diagnostic for mesh objects. Reports topology, loose/non-manifold '
                 'geometry, material readiness, modifier seed warnings, unapplied scale warnings, and pass/fail '
                 'status. Use before custom modeling repair scripts or as an exit-test gate.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'include_children': {'type': 'boolean'},
                                  'require_materials': {'type': 'boolean'},
                                  'allow_modifier_seed_boundaries': {'type': 'boolean'},
                                  'scale_tolerance': {'type': 'number'},
                                  'max_objects': {'type': 'integer', 'minimum': 1, 'maximum': 256}},
                   'additionalProperties': False},
  'contract': {'description': 'Read-only modeling quality diagnostic for mesh topology, material readiness, modifier '
                              'seed warnings, and scale warnings',
               'mutates_scene': False,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'include_children': {'type': 'boolean'},
                                               'require_materials': {'type': 'boolean'},
                                               'allow_modifier_seed_boundaries': {'type': 'boolean'},
                                               'scale_tolerance': {'type': 'number'},
                                               'max_objects': {'type': 'integer', 'minimum': 1, 'maximum': 256}},
                                'additionalProperties': False}},
  'handler_key': 'inspect_modeling_quality',
  'order': 660,
  'groups': ('basic_edit', 'deep_inspect', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'curve_to_mesh',
  'description': 'Create mesh-copy objects from selected or named Curve/Text objects without destroying the source. '
                 'Optionally hides the source. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'name_prefix': {'type': 'string'},
                                  'hide_original': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create preview-safe mesh-copy objects from Curve/Text sources',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'name_prefix': {'type': 'string'},
                                               'hide_original': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'curve_to_mesh',
  'order': 670,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'create_text_object',
  'description': 'Create a text object with transform, alignment, size, and optional simple material. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'body': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'rotation': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'scale': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 3},
                                  'size': {'type': 'number'},
                                  'align_x': {'type': 'string',
                                              'enum': ['LEFT', 'CENTER', 'RIGHT', 'JUSTIFY', 'FLUSH']},
                                  'align_y': {'type': 'string', 'enum': ['CENTER', 'TOP', 'BOTTOM']},
                                  'material_name': {'type': 'string'},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 4},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'body', 'location', 'rotation', 'scale'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a text object with transform and optional material',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_text_object',
  'order': 1050,
  'groups': ('advanced_create', 'character', 'curves_text', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'create_curve_path',
  'description': 'Create a 3D poly curve path from points with optional bevel and material. Applies immediately with '
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'points': {'type': 'array',
                                             'items': {'type': 'array',
                                                       'items': {'type': 'number'},
                                                       'minItems': 3,
                                                       'maxItems': 3}},
                                  'bevel_depth': {'type': 'number'},
                                  'cyclic': {'type': 'boolean'},
                                  'material_name': {'type': 'string'},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 4},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'points'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a 3D curve path from points',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_curve_path',
  'order': 1060,
  'groups': ('advanced_create', 'character', 'curves_text', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'apply_procedural_array_stack',
  'description': 'Apply a bounded procedural modeling stack to mesh objects: array, bevel, and optional weighted '
                 'normals. Use before custom geometry-node or mesh-edit scripts. Applies immediately with preview '
                 'revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'count': {'type': 'integer', 'minimum': 1, 'maximum': 1000},
                                  'relative_offset': {'type': 'array',
                                                      'items': {'type': 'number'},
                                                      'minItems': 3,
                                                      'maxItems': 3},
                                  'bevel_width': {'type': 'number'},
                                  'bevel_segments': {'type': 'integer', 'minimum': 1, 'maximum': 32},
                                  'add_weighted_normals': {'type': 'boolean'},
                                  'name_prefix': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Apply a bounded procedural array, bevel, and weighted-normal modeling stack',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'count': {'type': 'integer', 'minimum': 1, 'maximum': 1000},
                                               'relative_offset': {'type': 'array',
                                                                   'items': {'type': 'number'},
                                                                   'minItems': 3,
                                                                   'maxItems': 3},
                                               'bevel_width': {'type': 'number'},
                                               'bevel_segments': {'type': 'integer', 'minimum': 1, 'maximum': 32},
                                               'add_weighted_normals': {'type': 'boolean'},
                                               'name_prefix': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'apply_procedural_array_stack',
  'order': 1220,
  'groups': ('advanced_create', 'refinement', 'procedural_3d', 'geometry_nodes'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'boolean_op',
  'description': 'Add non-destructive Boolean modifiers to a target mesh using named cutter meshes or selected '
                 'cutters. Use for difference, union, and intersect cuts before custom mesh scripts. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_object_name': {'type': 'string'},
                                  'cutter_object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'operation': {'type': 'string', 'enum': ['DIFFERENCE', 'UNION', 'INTERSECT']},
                                  'solver': {'type': 'string', 'enum': ['FAST', 'FLOAT', 'EXACT', 'MANIFOLD']},
                                  'name_prefix': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add non-destructive Boolean modifiers to a target mesh using cutter meshes',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'target_object_name': {'type': 'string'},
                                               'cutter_object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'operation': {'type': 'string',
                                                             'enum': ['DIFFERENCE', 'UNION', 'INTERSECT']},
                                               'solver': {'type': 'string',
                                                          'enum': ['FAST', 'FLOAT', 'EXACT', 'MANIFOLD']},
                                               'name_prefix': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'boolean_op',
  'order': 1230,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'mirror_model',
  'description': 'Add non-destructive Mirror modifiers to selected or named mesh objects, with optional mirror object, '
                 'bisect axes, clipping, and merge settings. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'use_axis': {'type': 'array',
                                               'items': {'type': 'boolean'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'mirror_object_name': {'type': 'string'},
                                  'bisect_axis': {'type': 'array',
                                                  'items': {'type': 'boolean'},
                                                  'minItems': 3,
                                                  'maxItems': 3},
                                  'flip_axis': {'type': 'array',
                                                'items': {'type': 'boolean'},
                                                'minItems': 3,
                                                'maxItems': 3},
                                  'use_clip': {'type': 'boolean'},
                                  'use_mirror_merge': {'type': 'boolean'},
                                  'merge_threshold': {'type': 'number'},
                                  'name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add non-destructive Mirror modifiers with optional mirror object, bisect, clipping, and '
                              'merge settings',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'use_axis': {'type': 'array',
                                                            'items': {'type': 'boolean'},
                                                            'minItems': 3,
                                                            'maxItems': 3},
                                               'mirror_object_name': {'type': 'string'},
                                               'bisect_axis': {'type': 'array',
                                                               'items': {'type': 'boolean'},
                                                               'minItems': 3,
                                                               'maxItems': 3},
                                               'flip_axis': {'type': 'array',
                                                             'items': {'type': 'boolean'},
                                                             'minItems': 3,
                                                             'maxItems': 3},
                                               'use_clip': {'type': 'boolean'},
                                               'use_mirror_merge': {'type': 'boolean'},
                                               'merge_threshold': {'type': 'number'},
                                               'name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'mirror_model',
  'order': 1240,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'symmetrize_model',
  'description': 'Add a non-destructive symmetry Mirror modifier to selected or named mesh objects on one axis. Use '
                 'for quick left/right, front/back, or top/bottom symmetry before destructive mesh scripts. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'direction': {'type': 'string',
                                                'enum': ['POSITIVE_TO_NEGATIVE', 'NEGATIVE_TO_POSITIVE']},
                                  'merge_threshold': {'type': 'number'},
                                  'name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add a non-destructive symmetry Mirror modifier on one axis',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                               'direction': {'type': 'string',
                                                             'enum': ['POSITIVE_TO_NEGATIVE', 'NEGATIVE_TO_POSITIVE']},
                                               'merge_threshold': {'type': 'number'},
                                               'name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'symmetrize_model',
  'order': 1250,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'solidify_model',
  'description': 'Add non-destructive Solidify modifiers to selected or named mesh objects for wall thickness, shells, '
                 'panels, or flat cutout depth. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'thickness': {'type': 'number'},
                                  'offset': {'type': 'number'},
                                  'use_even_offset': {'type': 'boolean'},
                                  'name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add non-destructive Solidify modifiers for thickness and shell modeling',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'thickness': {'type': 'number'},
                                               'offset': {'type': 'number'},
                                               'use_even_offset': {'type': 'boolean'},
                                               'name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'solidify_model',
  'order': 1260,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'screw_model',
  'description': 'Add non-destructive Screw modifiers to selected or named mesh objects for rotational forms, spirals, '
                 'springs, threads, and screw-depth modeling. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'angle': {'type': 'number'},
                                  'screw_offset': {'type': 'number'},
                                  'iterations': {'type': 'integer', 'minimum': 1, 'maximum': 256},
                                  'steps': {'type': 'integer', 'minimum': 1, 'maximum': 512},
                                  'render_steps': {'type': 'integer', 'minimum': 1, 'maximum': 1024},
                                  'use_merge_vertices': {'type': 'boolean'},
                                  'merge_threshold': {'type': 'number'},
                                  'use_smooth_shade': {'type': 'boolean'},
                                  'name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add non-destructive Screw modifiers for rotational forms, spirals, springs, threads, '
                              'and screw-depth modeling',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                               'angle': {'type': 'number'},
                                               'screw_offset': {'type': 'number'},
                                               'iterations': {'type': 'integer', 'minimum': 1, 'maximum': 256},
                                               'steps': {'type': 'integer', 'minimum': 1, 'maximum': 512},
                                               'render_steps': {'type': 'integer', 'minimum': 1, 'maximum': 1024},
                                               'use_merge_vertices': {'type': 'boolean'},
                                               'merge_threshold': {'type': 'number'},
                                               'use_smooth_shade': {'type': 'boolean'},
                                               'name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'screw_model',
  'order': 1270,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import modeling

    modeling.register(handler_registry, SPECS)
