"""Canonical tool specifications for the modeling domain."""

from __future__ import annotations

from ..registry import ToolSpec


_MULTIVIEW_VIEW_SCHEMA = {
    'type': 'object',
    'properties': {
        'name': {'type': 'string'},
        'image_path': {
            'type': 'string',
            'description': 'Local reference image path supplied by the user or another trusted local source.',
        },
        'axis': {
            'type': 'string',
            'enum': ['FRONT', 'BACK', 'LEFT', 'RIGHT', 'TOP', 'BOTTOM', 'CUSTOM'],
        },
        'view_direction': {
            'type': 'array',
            'items': {'type': 'number'},
            'minItems': 3,
            'maxItems': 3,
            'description': 'Required with CUSTOM: world-space direction from camera toward the subject.',
        },
        'up_direction': {
            'type': 'array',
            'items': {'type': 'number'},
            'minItems': 3,
            'maxItems': 3,
            'description': 'Required with CUSTOM: approximate world-space image-up direction.',
        },
        'annotations': {
            'type': 'object',
            'description': 'Annotation schema v1 object. Supply exactly one annotation source per view.',
            'additionalProperties': True,
        },
        'annotations_json': {
            'type': 'string',
            'description': 'Annotation schema v1 as JSON text.',
        },
        'annotations_path': {
            'type': 'string',
            'description': 'Local UTF-8 annotation JSON path supplied by the user or another trusted local source.',
        },
        'default_coordinate_space': {
            'type': 'string',
            'enum': ['pixel', 'normalized'],
        },
        'default_origin': {
            'type': 'string',
            'enum': ['top_left', 'bottom_left'],
        },
        'plane_height': {'type': 'number', 'minimum': 0.01, 'maximum': 100.0},
        'camera_margin': {'type': 'number', 'minimum': 0.0, 'maximum': 1.0},
        'guide_offset': {'type': 'number', 'minimum': -10.0, 'maximum': 10.0},
        'include_image_plane': {'type': 'boolean'},
        'image_alpha': {'type': 'number', 'minimum': 0.0, 'maximum': 1.0},
    },
    'required': ['name', 'image_path', 'axis'],
    'additionalProperties': False,
}


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'edit_mesh',
  'description': 'Apply one bounded destructive mesh edit to selected or named single-user mesh objects with mesh-data '
                 'snapshot rollback. Supports face extrusion, face inset, bounded planar loop cut, planar knife cut, '
                 'boundary-loop bridge, dissolve-degenerate, merge-by-distance, and proportional vertex edit.',
  'input_schema': {'type': 'object',
                   'properties': {'operation': {'type': 'string',
                                                'enum': ['extrude_faces',
                                                         'inset_faces',
                                                         'merge_by_distance',
                                                         'dissolve_degenerate',
                                                         'bridge_boundary_loops',
                                                         'loop_cut',
                                                         'knife_cut',
                                                         'proportional_edit']},
                                  'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'face_scope': {'type': 'string',
                                                 'enum': ['ALL', 'TOP', 'BOTTOM', 'LEFT', 'RIGHT', 'FRONT', 'BACK']},
                                  'direction': {'type': 'string', 'enum': ['NORMAL', 'AXIS', 'X', 'Y', 'Z']},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'distance': {'type': 'number'},
                                  'inset_thickness': {'type': 'number'},
                                  'inset_depth': {'type': 'number'},
                                  'merge_distance': {'type': 'number'},
                                  'loop_cuts': {'type': 'integer',
                                                'minimum': 1,
                                                'maximum': 32,
                                                'description': 'Number of evenly spaced loop planes for loop_cut.'},
                                  'cut_axis': {'type': 'string',
                                               'enum': ['X', 'Y', 'Z'],
                                               'description': 'Plane normal axis for knife_cut and loop_cut.'},
                                  'cut_position': {'type': 'number',
                                                   'description': 'Explicit plane position for knife_cut.'},
                                  'proportional_center': {'type': 'array',
                                                          'items': {'type': 'number'},
                                                          'minItems': 3,
                                                          'maxItems': 3},
                                  'proportional_radius': {'type': 'number'},
                                  'proportional_falloff': {'type': 'string',
                                                           'enum': ['SMOOTH',
                                                                    'LINEAR',
                                                                    'CONSTANT',
                                                                    'SHARP',
                                                                    'ROOT',
                                                                    'SPHERE']},
                                  'allow_shape_keys': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Apply one bounded destructive mesh edit, including bounded planar loop cuts, with '
                              'mesh-data snapshot rollback',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'operation': {'type': 'string',
                                                             'enum': ['extrude_faces',
                                                                      'inset_faces',
                                                                      'merge_by_distance',
                                                                      'dissolve_degenerate',
                                                                      'bridge_boundary_loops',
                                                                      'loop_cut',
                                                                      'knife_cut',
                                                                      'proportional_edit']},
                                               'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'face_scope': {'type': 'string',
                                                              'enum': ['ALL',
                                                                       'TOP',
                                                                       'BOTTOM',
                                                                       'LEFT',
                                                                       'RIGHT',
                                                                       'FRONT',
                                                                       'BACK']},
                                               'direction': {'type': 'string',
                                                             'enum': ['NORMAL', 'AXIS', 'X', 'Y', 'Z']},
                                               'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                               'distance': {'type': 'number'},
                                               'inset_thickness': {'type': 'number'},
                                               'inset_depth': {'type': 'number'},
                                               'merge_distance': {'type': 'number'},
                                               'loop_cuts': {'type': 'integer',
                                                             'minimum': 1,
                                                             'maximum': 32,
                                                             'description': 'Number of evenly spaced loop planes for '
                                                                            'loop_cut.'},
                                               'cut_axis': {'type': 'string',
                                                            'enum': ['X', 'Y', 'Z'],
                                                            'description': 'Plane normal axis for knife_cut and '
                                                                           'loop_cut.'},
                                               'cut_position': {'type': 'number',
                                                                'description': 'Explicit plane position for '
                                                                               'knife_cut.'},
                                               'proportional_center': {'type': 'array',
                                                                       'items': {'type': 'number'},
                                                                       'minItems': 3,
                                                                       'maxItems': 3},
                                               'proportional_radius': {'type': 'number'},
                                               'proportional_falloff': {'type': 'string',
                                                                        'enum': ['SMOOTH',
                                                                                 'LINEAR',
                                                                                 'CONSTANT',
                                                                                 'SHARP',
                                                                                 'ROOT',
                                                                                 'SPHERE']},
                                               'allow_shape_keys': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'edit_mesh',
  'order': 650,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'inspect_modeling_quality',
  'description': 'Read-only modeling quality diagnostic for mesh objects. Reports topology, loose/non-manifold '
                 'geometry, material readiness, modifier seed warnings, unapplied scale warnings, and pass/fail '
                 'status. Use before custom modeling repair scripts or as an exit-test gate.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'include_children': {'type': 'boolean'},
                                  'require_materials': {'type': 'boolean'},
                                  'allow_modifier_seed_boundaries': {'type': 'boolean'},
                                  'scale_tolerance': {'type': 'number'},
                                  'max_objects': {'type': 'integer', 'minimum': 1, 'maximum': 256}},
                   'additionalProperties': False},
  'contract': {'description': 'Read-only modeling quality diagnostic for mesh topology, material readiness, modifier '
                              'seed warnings, and scale warnings',
               'mutates_scene': False,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'include_children': {'type': 'boolean'},
                                               'require_materials': {'type': 'boolean'},
                                               'allow_modifier_seed_boundaries': {'type': 'boolean'},
                                               'scale_tolerance': {'type': 'number'},
                                               'max_objects': {'type': 'integer', 'minimum': 1, 'maximum': 256}},
                                'additionalProperties': False}},
  'handler_key': 'inspect_modeling_quality',
  'order': 660,
  'groups': ('basic_edit', 'deep_inspect', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'curve_to_mesh',
  'description': 'Create mesh-copy objects from selected or named Curve/Text objects without destroying the source. '
                 'Optionally hides the source. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'name_prefix': {'type': 'string'},
                                  'hide_original': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create preview-safe mesh-copy objects from Curve/Text sources',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'name_prefix': {'type': 'string'},
                                               'hide_original': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'curve_to_mesh',
  'order': 670,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'create_text_object',
  'description': 'Create a text object with transform, alignment, size, and optional simple material. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'body': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'rotation': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'scale': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 3},
                                  'size': {'type': 'number'},
                                  'align_x': {'type': 'string',
                                              'enum': ['LEFT', 'CENTER', 'RIGHT', 'JUSTIFY', 'FLUSH']},
                                  'align_y': {'type': 'string', 'enum': ['CENTER', 'TOP', 'BOTTOM']},
                                  'material_name': {'type': 'string'},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 4},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'body', 'location', 'rotation', 'scale'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a text object with transform and optional material',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_text_object',
  'order': 1050,
  'groups': ('advanced_create', 'character', 'curves_text', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'create_curve_path',
  'description': 'Create a 3D poly curve path from points with optional bevel and material. Applies immediately with '
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'points': {'type': 'array',
                                             'items': {'type': 'array',
                                                       'items': {'type': 'number'},
                                                       'minItems': 3,
                                                       'maxItems': 3}},
                                  'bevel_depth': {'type': 'number'},
                                  'cyclic': {'type': 'boolean'},
                                  'material_name': {'type': 'string'},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 4},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'points'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a 3D curve path from points',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_curve_path',
  'order': 1060,
  'groups': ('advanced_create', 'character', 'curves_text', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'create_reference_modeling_guides',
  'description': 'Create preview-safe Blender guide geometry from a reference image and structured 2D annotations: '
                 'image plane, landmark empties, outline curves, mass ellipses, measurement guides, and a '
                 'reference_brief seed for script-first sculpt/modeling work. Use before authored reference modeling '
                 'scripts when image matching, landmarks, or proportions matter.',
  'input_schema': {'type': 'object',
                   'properties': {'image_path': {'type': 'string',
                                                 'description': 'Optional local reference image path supplied by the '
                                                                'user, file picker, or prior capture.'},
                                  'image_size': {'type': 'array',
                                                 'items': {'type': 'number'},
                                                 'minItems': 2,
                                                 'maxItems': 2,
                                                 'description': 'Image size [width, height]. Required for pixel '
                                                                'coordinates when image_path is omitted.'},
                                  'coordinate_space': {'type': 'string', 'enum': ['normalized', 'pixel']},
                                  'subject': {'type': 'string'},
                                  'collection_name': {'type': 'string'},
                                  'plane_height': {'type': 'number'},
                                  'plane_location': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3},
                                  'guide_offset_y': {'type': 'number'},
                                  'include_image_plane': {'type': 'boolean'},
                                  'image_alpha': {'type': 'number', 'minimum': 0.0, 'maximum': 1.0},
                                  'landmarks': {'type': 'array',
                                                'items': {'type': 'object',
                                                          'properties': {'name': {'type': 'string'},
                                                                         'point': {'type': 'array',
                                                                                   'items': {'type': 'number'},
                                                                                   'minItems': 2,
                                                                                   'maxItems': 2},
                                                                         'center': {'type': 'array',
                                                                                    'items': {'type': 'number'},
                                                                                    'minItems': 2,
                                                                                    'maxItems': 2},
                                                                         'position': {'type': 'array',
                                                                                      'items': {'type': 'number'},
                                                                                      'minItems': 2,
                                                                                      'maxItems': 2},
                                                                         'size': {'type': 'number'},
                                                                         'note': {'type': 'string'}},
                                                          'additionalProperties': False},
                                                'maxItems': 128},
                                  'curves': {'type': 'array',
                                             'items': {'type': 'object',
                                                       'properties': {'name': {'type': 'string'},
                                                                      'points': {'type': 'array',
                                                                                 'items': {'type': 'array',
                                                                                           'items': {'type': 'number'},
                                                                                           'minItems': 2,
                                                                                           'maxItems': 2}},
                                                                      'cyclic': {'type': 'boolean'},
                                                                      'bevel_depth': {'type': 'number'},
                                                                      'color': {'type': 'array',
                                                                                'items': {'type': 'number'},
                                                                                'minItems': 3,
                                                                                'maxItems': 4}},
                                                       'required': ['points'],
                                                       'additionalProperties': False},
                                             'maxItems': 64},
                                  'masses': {'type': 'array',
                                             'items': {'type': 'object',
                                                       'properties': {'name': {'type': 'string'},
                                                                      'center': {'type': 'array',
                                                                                 'items': {'type': 'number'},
                                                                                 'minItems': 2,
                                                                                 'maxItems': 2},
                                                                      'radius': {'type': 'array',
                                                                                 'items': {'type': 'number'},
                                                                                 'minItems': 2,
                                                                                 'maxItems': 2},
                                                                      'radii': {'type': 'array',
                                                                                'items': {'type': 'number'},
                                                                                'minItems': 2,
                                                                                'maxItems': 2},
                                                                      'bevel_depth': {'type': 'number'},
                                                                      'color': {'type': 'array',
                                                                                'items': {'type': 'number'},
                                                                                'minItems': 3,
                                                                                'maxItems': 4}},
                                                       'required': ['center'],
                                                       'additionalProperties': False},
                                             'maxItems': 64},
                                  'measurements': {'type': 'array',
                                                   'items': {'type': 'object',
                                                             'properties': {'name': {'type': 'string'},
                                                                            'from': {'type': 'string'},
                                                                            'to': {'type': 'string'},
                                                                            'from_point': {'type': 'array',
                                                                                           'items': {'type': 'number'},
                                                                                           'minItems': 2,
                                                                                           'maxItems': 2},
                                                                            'to_point': {'type': 'array',
                                                                                         'items': {'type': 'number'},
                                                                                         'minItems': 2,
                                                                                         'maxItems': 2},
                                                                            'bevel_depth': {'type': 'number'},
                                                                            'color': {'type': 'array',
                                                                                      'items': {'type': 'number'},
                                                                                      'minItems': 3,
                                                                                      'maxItems': 4}},
                                                             'additionalProperties': False},
                                                   'maxItems': 64},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create reference-image modeling guide geometry and a reference_brief seed from '
                              'structured 2D annotations',
               'mutates_scene': True,
               'requires_live_preview': True,
               'requires_user_path': True,
               'permissions': ['scene:read', 'scene:mutate', 'preview:write', 'files:read'],
               'path_policy': 'image_path must be a local reference image path supplied by the user, a file picker, a '
                              'prior capture, or another trusted local source. Omit image_path to create guides from '
                              'image_size and annotations only.'},
 'handler_key': 'create_reference_modeling_guides',
  'order': 1070,
  'groups': ('advanced_create', 'procedural_3d', 'model_quality', 'reference_modeling'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'create_reference_guides_from_annotations',
  'description': 'Create a calibrated, preview-safe Blender guide scene from a local reference image plus '
                 'client-neutral landmark/outline JSON. Accepts an annotation object, JSON text, or a user-supplied '
                 'JSON path; normalizes pixel or normalized coordinates, corrects top-left or bottom-left origins and '
                 'optional image rectangles, creates landmarks/outlines/masses/measurements, and adds an orthographic '
                 'reference camera with deterministic calibration metadata.',
  'input_schema': {'type': 'object',
                   'properties': {'image_path': {'type': 'string',
                                                 'description': 'Local reference image path supplied by the user, a '
                                                                'file picker, a prior capture, or another trusted '
                                                                'local source.'},
                                  'annotations': {'type': 'object',
                                                  'description': 'Annotation schema v1 object. Supply exactly one of '
                                                                 'annotations, annotations_json, or annotations_path.',
                                                  'properties': {'version': {'type': 'integer', 'enum': [1]},
                                                                 'subject': {'type': 'string'},
                                                                 'coordinate_space': {'type': 'string',
                                                                                      'enum': ['pixel', 'normalized']},
                                                                 'origin': {'type': 'string',
                                                                            'enum': ['top_left', 'bottom_left']},
                                                                 'image_size': {'type': 'array',
                                                                                'items': {'type': 'number'},
                                                                                'minItems': 2,
                                                                                'maxItems': 2},
                                                                 'image_rect': {'type': 'array',
                                                                                'items': {'type': 'number'},
                                                                                'minItems': 4,
                                                                                'maxItems': 4,
                                                                                'description': 'Image bounds as '
                                                                                               '[x, y, width, height] '
                                                                                               'in the declared '
                                                                                               'coordinate space.'},
                                                                 'image': {'type': 'object',
                                                                           'description': 'Optional nested image '
                                                                                          'size, coordinate-space, '
                                                                                          'origin, or rect metadata.'},
                                                                 'landmarks': {'description': 'Landmark array or '
                                                                                              'name-to-point object '
                                                                                              'map.'},
                                                                 'outlines': {'description': 'Outline array, point '
                                                                                             'array, or name-to-outline '
                                                                                             'object map.'},
                                                                 'curves': {'description': 'Alias for outlines.'},
                                                                 'masses': {'description': 'Mass ellipse array or '
                                                                                           'name-to-mass object map.'},
                                                                 'measurements': {'description': 'Measurement array or '
                                                                                                 'name-to-measurement '
                                                                                                 'object map.'}},
                                                  'additionalProperties': True},
                                  'annotations_json': {'type': 'string',
                                                       'description': 'Annotation schema v1 as JSON text. Supply '
                                                                      'exactly one annotation source.'},
                                  'annotations_path': {'type': 'string',
                                                       'description': 'Local UTF-8 annotation JSON path supplied by '
                                                                      'the user or another trusted local source.'},
                                  'default_coordinate_space': {'type': 'string',
                                                               'enum': ['pixel', 'normalized'],
                                                               'description': 'Fallback when the annotation document '
                                                                              'does not declare coordinate_space.'},
                                  'default_origin': {'type': 'string',
                                                     'enum': ['top_left', 'bottom_left'],
                                                     'description': 'Fallback when the annotation document does not '
                                                                    'declare origin.'},
                                  'subject': {'type': 'string'},
                                  'collection_name': {'type': 'string'},
                                  'plane_height': {'type': 'number', 'minimum': 0.01, 'maximum': 100.0},
                                  'plane_location': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3},
                                  'guide_offset_y': {'type': 'number', 'minimum': -10.0, 'maximum': 10.0},
                                  'include_image_plane': {'type': 'boolean'},
                                  'image_alpha': {'type': 'number', 'minimum': 0.0, 'maximum': 1.0},
                                  'create_camera': {'type': 'boolean'},
                                  'camera_name': {'type': 'string'},
                                  'camera_margin': {'type': 'number', 'minimum': 0.0, 'maximum': 1.0},
                                  'activate_camera': {'type': 'boolean'},
                                  'match_render_aspect': {'type': 'boolean',
                                                          'description': 'Match the scene render dimensions to the '
                                                                         'reference aspect while the preview is '
                                                                         'pending. Revert restores the prior render '
                                                                         'dimensions.'},
                                  'label': {'type': 'string'}},
                   'required': ['image_path'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a calibrated reference guide collection and optional orthographic camera from '
                              'a local image and bounded client-neutral annotation JSON',
               'mutates_scene': True,
               'requires_live_preview': True,
               'requires_user_path': True,
               'permissions': ['scene:read', 'scene:mutate', 'preview:write', 'files:read'],
               'path_policy': 'image_path and annotations_path must be local paths explicitly supplied by the user, a '
                              'file picker, a prior capture, or another trusted local source. Annotation objects and '
                              'JSON text are parsed in memory. Exactly one annotation source is required.'},
  'handler_key': 'create_reference_guides_from_annotations',
  'order': 1072,
  'groups': ('advanced_create', 'procedural_3d', 'model_quality', 'reference_modeling'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'create_multiview_reference_guides',
  'description': 'Create two to six calibrated reference-image guide collections and reconstruct shared landmark names '
                 'as 3D empties. Supports front/back/left/right/top/bottom presets or custom orthographic bases, keeps '
                 'each image, outline, and camera isolated by view, solves landmark rays by least squares, reports '
                 'residual and view-angle quality, and can add hidden reconstruction connectors. Applies immediately '
                 'with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'views': {'type': 'array',
                                            'items': _MULTIVIEW_VIEW_SCHEMA,
                                            'minItems': 2,
                                            'maxItems': 6},
                                  'subject': {'type': 'string'},
                                  'collection_name': {'type': 'string'},
                                  'subject_center': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3},
                                  'active_view': {'type': 'string'},
                                  'include_image_planes': {'type': 'boolean'},
                                  'image_alpha': {'type': 'number', 'minimum': 0.0, 'maximum': 1.0},
                                  'guide_offset': {'type': 'number', 'minimum': -10.0, 'maximum': 10.0},
                                  'create_connectors': {'type': 'boolean'},
                                  'require_reconstruction': {'type': 'boolean'},
                                  'minimum_views_per_landmark': {'type': 'integer',
                                                                 'minimum': 2,
                                                                 'maximum': 6},
                                  'minimum_ray_angle_degrees': {'type': 'number',
                                                                'minimum': 0.0,
                                                                'maximum': 90.0},
                                  'max_landmark_residual': {'type': 'number',
                                                            'minimum': 0.0,
                                                            'maximum': 1000.0},
                                  'match_render_aspect': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'required': ['views'],
                   'additionalProperties': False},
  'contract': {'description': 'Create calibrated multi-view guide collections and least-squares 3D landmarks',
               'mutates_scene': True,
               'requires_live_preview': True,
               'requires_user_path': True,
               'permissions': ['scene:read', 'scene:mutate', 'preview:write', 'files:read'],
               'path_policy': 'Every view image_path and optional annotations_path must be a local path explicitly '
                              'supplied by the user, a file picker, a prior capture, or another trusted local source. '
                              'Annotation objects and JSON text are parsed in memory.'},
  'handler_key': 'create_multiview_reference_guides',
  'order': 1073,
  'groups': ('advanced_create', 'procedural_3d', 'model_quality', 'reference_modeling'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'inspect_reference_modeling_guides',
  'description': 'Inspect reference modeling guide collections created by create_reference_modeling_guides. Returns '
                 'image-plane metadata, 2D and reconstructed 3D landmarks, reconstruction rays, curves, mass ellipses, '
                 'measurements, and the saved reference_brief seed so agents can hand exact guide facts into authored '
                 'modeling scripts.',
  'input_schema': {'type': 'object',
                   'properties': {'collection_name': {'type': 'string',
                                                      'description': 'Optional exact guide collection name. Omit to '
                                                                     'inspect tagged guide collections.'},
                                  'include_points': {'type': 'boolean',
                                                     'description': 'Include sampled world-space curve points. Keep '
                                                                    'false for compact script handoff unless points '
                                                                    'are needed.'},
                                  'max_points_per_curve': {'type': 'integer', 'minimum': 2, 'maximum': 512},
                                  'max_collections': {'type': 'integer', 'minimum': 1, 'maximum': 64}},
                   'additionalProperties': False},
  'contract': {'description': 'Read reference guide metadata without mutating the scene',
               'mutates_scene': False,
               'permissions': ['scene:read'],
               'supports_headless': True},
  'handler_key': 'inspect_reference_modeling_guides',
  'order': 1075,
  'groups': ('deep_inspect', 'model_quality', 'reference_modeling'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'compare_model_to_reference',
  'description': 'Render named model targets through a calibrated reference-guide camera, compare their binary '
                 'silhouette with an annotated outline or useful reference alpha, measure overlap, edge distance, '
                 'centroid and optional landmark errors, and publish model-mask, reference-mask, and redline PNG '
                 'resources. Use after each broad construction or repair pass so the next edit is driven by named '
                 'image-space errors instead of an unmeasured visual impression.',
  'input_schema': {'type': 'object',
                   'properties': {'collection_name': {'type': 'string',
                                                      'description': 'Exact calibrated reference-guide collection. '
                                                                     'May be omitted only when exactly one tagged '
                                                                     'guide collection exists.'},
                                  'camera_name': {'type': 'string',
                                                  'description': 'Optional calibrated camera override.'},
                                  'object_names': {'type': 'array',
                                                   'items': {'type': 'string'},
                                                   'maxItems': 64,
                                                   'description': 'Renderable model roots. Their descendants are '
                                                                  'included in the silhouette.'},
                                  'selected_only': {'type': 'boolean',
                                                    'description': 'Use selected renderable objects when object_names '
                                                                   'is empty. Defaults to true.'},
                                  'outline_name': {'type': 'string',
                                                   'description': 'Optional exact reference curve name. Defaults to '
                                                                  'the first cyclic outline.'},
                                  'reference_mask_source': {'type': 'string',
                                                            'enum': ['auto', 'outline', 'alpha'],
                                                            'description': 'Auto prefers a calibrated outline and '
                                                                           'falls back to non-trivial image alpha.'},
                                  'landmark_targets': {'type': 'array',
                                                       'items': {'type': 'object',
                                                                 'properties': {'name': {'type': 'string'},
                                                                                'object_name': {'type': 'string'},
                                                                                'location': {'type': 'array',
                                                                                             'items': {'type': 'number'},
                                                                                             'minItems': 3,
                                                                                             'maxItems': 3}},
                                                                 'required': ['name'],
                                                                 'additionalProperties': False},
                                                       'maxItems': 128,
                                                       'description': 'Optional mappings from reference landmark name '
                                                                      'to a target object origin or world location.'},
                                  'max_axis': {'type': 'integer',
                                               'minimum': 64,
                                               'maximum': 1024,
                                               'description': 'Maximum comparison image axis. Defaults to 512.'},
                                  'mask_threshold': {'type': 'number',
                                                     'minimum': 0.01,
                                                     'maximum': 0.99,
                                                     'description': 'Alpha threshold for model/reference masks. '
                                                                    'Defaults to 0.5.'}},
                   'additionalProperties': False},
  'contract': {'description': 'Render and compare a model silhouette against calibrated reference guides, then '
                              'publish durable redline evidence',
               'mutates_scene': False,
               'has_side_effects': True,
               'permissions': ['scene:read', 'files:read', 'files:write'],
               'supports_headless': True,
               'long_running': True,
               'duration_hint': 'One bounded still render plus image-space comparison, normally a few seconds at '
                                '512px but dependent on scene/render complexity.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 5,
                                    'status_tool': 'blender_bridge_status',
                                    'evidence_resource': 'blender://inspection-renders/latest/metadata'}},
  'handler_key': 'compare_model_to_reference',
  'order': 1077,
  'groups': ('deep_inspect', 'model_quality', 'reference_modeling', 'camera_render'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'create_reference_blockout',
  'description': 'Create editable camera-oriented soft forms from calibrated reference mass ellipses, or from the '
                 'primary outline when no masses exist. Supports per-mass depth, scale, offset, and bounded local '
                 'deformation controls, then optionally builds a non-destructive voxel-remesh union. Use for primary '
                 'mass and silhouette blockout before authored secondary forms, features, fur, or surface detail.',
  'input_schema': {'type': 'object',
                   'properties': {'collection_name': {'type': 'string',
                                                      'description': 'Exact calibrated reference-guide collection. '
                                                                     'May be omitted only when exactly one exists.'},
                                  'camera_name': {'type': 'string',
                                                  'description': 'Optional calibrated camera override.'},
                                  'mass_names': {'type': 'array',
                                                 'items': {'type': 'string'},
                                                 'maxItems': 32,
                                                 'description': 'Optional exact guide-mass names. Empty uses all '
                                                                'masses or one cyclic-outline fallback.'},
                                  'mass_settings': {'type': 'array',
                                                    'items': {'type': 'object',
                                                              'properties': {'name': {'type': 'string'},
                                                                             'depth_ratio': {'type': 'number',
                                                                                             'minimum': 0.05,
                                                                                             'maximum': 3.0},
                                                                             'scale': {'type': 'array',
                                                                                       'items': {'type': 'number'},
                                                                                       'minItems': 3,
                                                                                       'maxItems': 3},
                                                                             'offset': {'type': 'array',
                                                                                        'items': {'type': 'number'},
                                                                                        'minItems': 3,
                                                                                        'maxItems': 3,
                                                                                        'description': 'Camera-local '
                                                                                                       '[right, depth, '
                                                                                                       'up] offset in '
                                                                                                       'Blender units.'},
                                                                             'controls': {'type': 'array',
                                                                                          'items': {'type': 'object',
                                                                                                    'properties': {'direction': {'type': 'array',
                                                                                                                                 'items': {'type': 'number'},
                                                                                                                                 'minItems': 3,
                                                                                                                                 'maxItems': 3},
                                                                                                                   'offset': {'type': 'number',
                                                                                                                              'minimum': -2.0,
                                                                                                                              'maximum': 2.0},
                                                                                                                   'falloff': {'type': 'number',
                                                                                                                               'minimum': 0.01,
                                                                                                                               'maximum': 2.0}},
                                                                                                    'required': ['direction',
                                                                                                                 'offset'],
                                                                                                    'additionalProperties': False},
                                                                                          'maxItems': 32}},
                                                              'required': ['name'],
                                                              'additionalProperties': False},
                                                    'maxItems': 64},
                                  'name_prefix': {'type': 'string'},
                                  'depth_ratio': {'type': 'number',
                                                  'minimum': 0.05,
                                                  'maximum': 3.0,
                                                  'description': 'Default depth relative to geometric mean of guide '
                                                                 'width and height radii.'},
                                  'segments': {'type': 'integer', 'minimum': 8, 'maximum': 128},
                                  'rings': {'type': 'integer', 'minimum': 4, 'maximum': 64},
                                  'max_forms': {'type': 'integer', 'minimum': 1, 'maximum': 32},
                                  'blend_mode': {'type': 'string', 'enum': ['voxel', 'separate']},
                                  'voxel_size': {'type': 'number', 'minimum': 0.001, 'maximum': 10.0},
                                  'smooth_iterations': {'type': 'integer', 'minimum': 0, 'maximum': 20},
                                  'show_components': {'type': 'boolean'},
                                  'color': {'type': 'array',
                                            'items': {'type': 'number'},
                                            'minItems': 3,
                                            'maxItems': 4},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create reference-derived soft blockout geometry with preview revert support',
               'mutates_scene': True,
               'requires_live_preview': True,
               'permissions': ['scene:read', 'scene:mutate', 'preview:write'],
               'supports_headless': True},
  'handler_key': 'create_reference_blockout',
  'order': 1080,
  'groups': ('advanced_create', 'procedural_3d', 'model_quality', 'reference_modeling'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'apply_procedural_array_stack',
  'description': 'Apply a bounded procedural modeling stack to mesh objects: array, bevel, and optional weighted '
                 'normals. Use when helpers were requested or this isolated stack exactly fits the task. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'count': {'type': 'integer', 'minimum': 1, 'maximum': 1000},
                                  'relative_offset': {'type': 'array',
                                                      'items': {'type': 'number'},
                                                      'minItems': 3,
                                                      'maxItems': 3},
                                  'bevel_width': {'type': 'number'},
                                  'bevel_segments': {'type': 'integer', 'minimum': 1, 'maximum': 32},
                                  'add_weighted_normals': {'type': 'boolean'},
                                  'name_prefix': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Apply a bounded procedural array, bevel, and weighted-normal modeling stack',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'count': {'type': 'integer', 'minimum': 1, 'maximum': 1000},
                                               'relative_offset': {'type': 'array',
                                                                   'items': {'type': 'number'},
                                                                   'minItems': 3,
                                                                   'maxItems': 3},
                                               'bevel_width': {'type': 'number'},
                                               'bevel_segments': {'type': 'integer', 'minimum': 1, 'maximum': 32},
                                               'add_weighted_normals': {'type': 'boolean'},
                                               'name_prefix': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'apply_procedural_array_stack',
  'order': 1220,
  'groups': ('advanced_create', 'refinement', 'procedural_3d', 'geometry_nodes'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'boolean_op',
  'description': 'Add non-destructive Boolean modifiers to a target mesh using named cutter meshes or selected '
                 'cutters. Use for an explicitly isolated difference, union, or intersect operation. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_object_name': {'type': 'string'},
                                  'cutter_object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'operation': {'type': 'string', 'enum': ['DIFFERENCE', 'UNION', 'INTERSECT']},
                                  'solver': {'type': 'string', 'enum': ['FAST', 'FLOAT', 'EXACT', 'MANIFOLD']},
                                  'name_prefix': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add non-destructive Boolean modifiers to a target mesh using cutter meshes',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'target_object_name': {'type': 'string'},
                                               'cutter_object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'operation': {'type': 'string',
                                                             'enum': ['DIFFERENCE', 'UNION', 'INTERSECT']},
                                               'solver': {'type': 'string',
                                                          'enum': ['FAST', 'FLOAT', 'EXACT', 'MANIFOLD']},
                                               'name_prefix': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'boolean_op',
  'order': 1230,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'mirror_model',
  'description': 'Add non-destructive Mirror modifiers to selected or named mesh objects, with optional mirror object, '
                 'bisect axes, clipping, and merge settings. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'use_axis': {'type': 'array',
                                               'items': {'type': 'boolean'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'mirror_object_name': {'type': 'string'},
                                  'bisect_axis': {'type': 'array',
                                                  'items': {'type': 'boolean'},
                                                  'minItems': 3,
                                                  'maxItems': 3},
                                  'flip_axis': {'type': 'array',
                                                'items': {'type': 'boolean'},
                                                'minItems': 3,
                                                'maxItems': 3},
                                  'use_clip': {'type': 'boolean'},
                                  'use_mirror_merge': {'type': 'boolean'},
                                  'merge_threshold': {'type': 'number'},
                                  'name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add non-destructive Mirror modifiers with optional mirror object, bisect, clipping, and '
                              'merge settings',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'use_axis': {'type': 'array',
                                                            'items': {'type': 'boolean'},
                                                            'minItems': 3,
                                                            'maxItems': 3},
                                               'mirror_object_name': {'type': 'string'},
                                               'bisect_axis': {'type': 'array',
                                                               'items': {'type': 'boolean'},
                                                               'minItems': 3,
                                                               'maxItems': 3},
                                               'flip_axis': {'type': 'array',
                                                             'items': {'type': 'boolean'},
                                                             'minItems': 3,
                                                             'maxItems': 3},
                                               'use_clip': {'type': 'boolean'},
                                               'use_mirror_merge': {'type': 'boolean'},
                                               'merge_threshold': {'type': 'number'},
                                               'name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'mirror_model',
  'order': 1240,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'symmetrize_model',
  'description': 'Add a non-destructive symmetry Mirror modifier to selected or named mesh objects on one axis. Use '
                 'for quick left/right, front/back, or top/bottom symmetry before destructive mesh scripts. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'direction': {'type': 'string',
                                                'enum': ['POSITIVE_TO_NEGATIVE', 'NEGATIVE_TO_POSITIVE']},
                                  'merge_threshold': {'type': 'number'},
                                  'name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add a non-destructive symmetry Mirror modifier on one axis',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                               'direction': {'type': 'string',
                                                             'enum': ['POSITIVE_TO_NEGATIVE', 'NEGATIVE_TO_POSITIVE']},
                                               'merge_threshold': {'type': 'number'},
                                               'name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'symmetrize_model',
  'order': 1250,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'solidify_model',
  'description': 'Add non-destructive Solidify modifiers to selected or named mesh objects for wall thickness, shells, '
                 'panels, or flat cutout depth. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'thickness': {'type': 'number'},
                                  'offset': {'type': 'number'},
                                  'use_even_offset': {'type': 'boolean'},
                                  'name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add non-destructive Solidify modifiers for thickness and shell modeling',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'thickness': {'type': 'number'},
                                               'offset': {'type': 'number'},
                                               'use_even_offset': {'type': 'boolean'},
                                               'name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'solidify_model',
  'order': 1260,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'},
 {'name': 'screw_model',
  'description': 'Add non-destructive Screw modifiers to selected or named mesh objects for rotational forms, spirals, '
                 'springs, threads, and screw-depth modeling. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'angle': {'type': 'number'},
                                  'screw_offset': {'type': 'number'},
                                  'iterations': {'type': 'integer', 'minimum': 1, 'maximum': 256},
                                  'steps': {'type': 'integer', 'minimum': 1, 'maximum': 512},
                                  'render_steps': {'type': 'integer', 'minimum': 1, 'maximum': 1024},
                                  'use_merge_vertices': {'type': 'boolean'},
                                  'merge_threshold': {'type': 'number'},
                                  'use_smooth_shade': {'type': 'boolean'},
                                  'name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add non-destructive Screw modifiers for rotational forms, spirals, springs, threads, '
                              'and screw-depth modeling',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                               'angle': {'type': 'number'},
                                               'screw_offset': {'type': 'number'},
                                               'iterations': {'type': 'integer', 'minimum': 1, 'maximum': 256},
                                               'steps': {'type': 'integer', 'minimum': 1, 'maximum': 512},
                                               'render_steps': {'type': 'integer', 'minimum': 1, 'maximum': 1024},
                                               'use_merge_vertices': {'type': 'boolean'},
                                               'merge_threshold': {'type': 'number'},
                                               'use_smooth_shade': {'type': 'boolean'},
                                               'name': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'screw_model',
  'order': 1270,
  'groups': ('basic_edit', 'advanced_create', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'modeling'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import modeling

    modeling.register(handler_registry, SPECS)
