"""Canonical tool specifications for the rigging simulation domain."""

from __future__ import annotations

from ..registry import ToolSpec


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'get_rigging_details',
  'description': 'Fetch read-only armature, bone, pose-bone, constraint, and driver summaries.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'max_objects': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return armature, bone, pose, constraint, and driver summaries', 'mutates_scene': False},
  'handler_key': 'get_rigging_details',
  'order': 470,
  'groups': ('deep_inspect', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'get_shape_key_details',
  'description': 'Fetch read-only mesh shape key blocks, values, ranges, relative keys, and shape-key drivers.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'max_objects': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return mesh shape key block, value, range, and driver summaries',
               'mutates_scene': False},
  'handler_key': 'get_shape_key_details',
  'order': 480,
  'groups': ('deep_inspect',),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'get_curve_text_details',
  'description': 'Fetch read-only curve and text object data including splines, bevels, text body preview, alignment, '
                 'and materials.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'max_objects': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return curve spline and text object summaries', 'mutates_scene': False},
  'handler_key': 'get_curve_text_details',
  'order': 490,
  'groups': ('deep_inspect', 'curves_text'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'get_simulation_details',
  'description': 'Fetch read-only rigid-body, particle, point-cache, and simulation bake summaries for cloth, fluid, '
                 'soft body, dynamic paint, and particles.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'max_objects': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Return rigid-body, particle, point-cache, and simulation bake summaries',
               'mutates_scene': False},
  'handler_key': 'get_simulation_details',
  'order': 500,
  'groups': ('deep_inspect', 'advanced_workflow', 'simulation_setup', 'particles'),
  'exposure': 'compact_direct',
  'owner': 'rigging_simulation'},
 {'name': 'inspect_simulation_bake',
  'description': 'Sample evaluated simulation state across a bounded frame range and report cache/bake readiness '
                 'without mutating persistent point caches.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'sample_count': {'type': 'integer'},
                                  'max_objects': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Sample evaluated simulation state across frames and report cache/bake readiness without '
                              'mutating persistent caches',
               'mutates_scene': False},
  'handler_key': 'inspect_simulation_bake',
  'order': 510,
  'groups': ('animation', 'deep_inspect', 'simulation_setup', 'particles'),
  'exposure': 'compact_direct',
  'owner': 'rigging_simulation'},
 {'name': 'stage_persistent_simulation_bake',
  'description': 'Inspect the requested simulation scope, then run a fixed-template scene-wide persistent point-cache '
                 'bake when Blender-side session script trust is active. Trust off refuses without staging.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'clear_existing': {'type': 'boolean'},
                                   'include_scene_rigid_body_world': {'type': 'boolean'},
                                   'auto_run_if_trusted': {'type': 'boolean',
                                                           'description': 'Deprecated compatibility option. Active '
                                                                          'session trust always runs immediately; '
                                                                          'trust off always refuses.'},
                                  'max_objects': {'type': 'integer'}},
                   'additionalProperties': False},
  'contract': {'description': 'Run a fixed-template scene-wide persistent point-cache bake under active binary session trust',
               'mutates_scene': True,
               'has_side_effects': True,
               'requires_approval': False,
               'explicit_approval_required': False,
               'trust_window_auto_run_allowed': True,
               'approval_policy': 'Requires active binary session trust and then runs immediately.',
               'authorization_model': 'blender_run_script_equivalent',
               'permissions': ['blender:full', 'filesystem:full'],
               'long_running': True,
               'destructive_hint': True,
               'timeout_seconds': 300,
               'duration_hint': 'Synchronous scene-wide simulation baking may take from seconds to hours and can keep '
                                'Blender unavailable while it runs.',
               'timeout_recovery': {'recoverable': True,
                                    'poll_after_seconds': 10,
                                    'status_tool': 'blender_bridge_status',
                                    'resource_tool': 'get_blend_file_diagnostics',
                                    'message': 'If baking times out, wait before calling blender_bridge_status and '
                                               'get_blend_file_diagnostics; do not rerun while the original bake may '
                                               'still be active.'},
               'recovery_hint': 'If Blender becomes unreachable after a trusted bake, wait, call '
                                'blender_bridge_status, then use get_blend_file_diagnostics before reporting any '
                                'checkpoint path.',
               'output_schema': {'type': 'object',
                                 'properties': {'ok': {'type': 'boolean'},
                                                'message': {'type': 'string'},
                                                'requires_user_approval': {'type': 'boolean'},
                                                'requires_explicit_one_time_approval': {'type': 'boolean'},
                                                'trust_window_auto_run_allowed': {'type': 'boolean'},
                                                'approval_policy': {'type': 'string'},
                                                'user_action_required': {'type': 'string'},
                                                'recommended_next_step': {'type': 'string'},
                                                'auto_run_attempted': {'type': 'boolean'},
                                                'auto_ran': {'type': 'boolean'},
                                                'auto_run_skipped_reason': {'type': 'string'},
                                                'frame_range': {'type': 'array', 'items': {'type': 'integer'}},
                                                'inspection': {'type': 'object',
                                                               'properties': {'ok': {'type': 'boolean',
                                                                                     'description': 'Whether the tool '
                                                                                                    'completed '
                                                                                                    'successfully'},
                                                                              'message': {'type': 'string',
                                                                                          'description': 'Human-readable '
                                                                                                         'status or '
                                                                                                         'error '
                                                                                                         'message'}},
                                                               'additionalProperties': True},
                                                'staged': {'type': 'object',
                                                           'properties': {'ok': {'type': 'boolean',
                                                                                 'description': 'Whether the tool '
                                                                                                'completed '
                                                                                                'successfully'},
                                                                          'message': {'type': 'string',
                                                                                      'description': 'Human-readable '
                                                                                                     'status or error '
                                                                                                     'message'}},
                                                           'additionalProperties': True}},
                                 'required': ['ok'],
                                 'additionalProperties': True}},
  'handler_key': 'stage_persistent_simulation_bake',
  'order': 520,
  'groups': ('animation', 'deep_inspect', 'simulation_setup', 'particles'),
  'exposure': 'compact_direct',
  'owner': 'rigging_simulation'},
 {'name': 'set_rig_pose_hold',
  'description': 'Duplicate pose-bone transforms on named armature control bones for a hold. Use for rig-driven '
                 'characters/props after inspecting rig controls. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'armature_name': {'type': 'string'},
                                  'bone_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'frame': {'type': 'integer'},
                                  'hold_frames': {'type': 'integer'},
                                  'paths': {'type': 'array',
                                            'items': {'type': 'string',
                                                      'enum': ['location',
                                                               'rotation_euler',
                                                               'rotation_quaternion',
                                                               'rotation_axis_angle',
                                                               'scale']}},
                                  'interpolation': {'type': 'string',
                                                    'enum': ['CONSTANT',
                                                             'LINEAR',
                                                             'BEZIER',
                                                             'SINE',
                                                             'QUAD',
                                                             'CUBIC',
                                                             'QUART',
                                                             'QUINT',
                                                             'EXPO',
                                                             'CIRC',
                                                             'BACK',
                                                             'BOUNCE',
                                                             'ELASTIC']},
                                  'label': {'type': 'string'}},
                   'required': ['armature_name', 'frame'],
                   'additionalProperties': False},
  'contract': {'description': 'Duplicate pose-bone transforms on named rig control bones for a readable hold',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_rig_pose_hold',
  'order': 970,
  'groups': ('animation', 'advanced_create', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'set_rig_custom_property_keyframes',
  'description': 'Key existing scalar rig custom properties, such as IK/FK or space switches, over a short hold '
                 'window. Use only for properties found by rig inspection or repair metadata. Applies immediately with '
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'armature_name': {'type': 'string'},
                                  'property_targets': {'type': 'array',
                                                       'items': {'type': 'object',
                                                                 'properties': {'owner_type': {'type': 'string',
                                                                                               'enum': ['object',
                                                                                                        'armature_data',
                                                                                                        'pose_bone']},
                                                                                'owner_name': {'type': 'string'},
                                                                                'property_name': {'type': 'string'},
                                                                                'value': {'type': ['number',
                                                                                                   'boolean']}},
                                                                 'required': ['owner_type', 'property_name'],
                                                                 'additionalProperties': False}},
                                  'frame': {'type': 'integer'},
                                  'hold_frames': {'type': 'integer'},
                                  'interpolation': {'type': 'string',
                                                    'enum': ['CONSTANT',
                                                             'LINEAR',
                                                             'BEZIER',
                                                             'SINE',
                                                             'QUAD',
                                                             'CUBIC',
                                                             'QUART',
                                                             'QUINT',
                                                             'EXPO',
                                                             'CIRC',
                                                             'BACK',
                                                             'BOUNCE',
                                                             'ELASTIC']},
                                  'label': {'type': 'string'}},
                   'required': ['armature_name', 'property_targets', 'frame'],
                   'additionalProperties': False},
  'contract': {'description': 'Key existing scalar rig custom properties such as IK/FK or space switches with preview '
                              'rollback',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_rig_custom_property_keyframes',
  'order': 980,
  'groups': ('animation', 'advanced_create', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'get_rig_pose_library_details',
  'description': 'Inspect rig-compatible pose-library/action candidates for an armature, including pose markers, '
                 'matched bones/channels, frame ranges, and suggested apply calls. Use before applying production rig '
                 'poses or clips.',
  'input_schema': {'type': 'object',
                   'properties': {'armature_name': {'type': 'string'},
                                  'action_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'bone_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'paths': {'type': 'array',
                                            'items': {'type': 'string',
                                                      'enum': ['location',
                                                               'rotation_euler',
                                                               'rotation_quaternion',
                                                               'rotation_axis_angle',
                                                               'scale']}},
                                  'max_actions': {'type': 'integer'}},
                   'required': ['armature_name'],
                   'additionalProperties': False},
  'contract': {'description': 'Inspect rig-compatible pose-library/action candidates, markers, matched bones, '
                              'channels, and suggested application calls',
               'mutates_scene': False},
  'handler_key': 'get_rig_pose_library_details',
  'order': 990,
  'groups': ('animation', 'advanced_create', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'apply_rig_pose_from_action',
  'description': 'Sample an existing rig action or pose-library marker and apply/key that pose onto matching armature '
                 'controls. Use for production rigs after get_rigging_details surfaces pose_library_candidates. '
                 'Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'armature_name': {'type': 'string'},
                                  'action_name': {'type': 'string'},
                                  'pose_marker': {'type': 'string'},
                                  'source_frame': {'type': 'integer'},
                                  'target_frame': {'type': 'integer'},
                                  'frame': {'type': 'integer'},
                                  'hold_frames': {'type': 'integer'},
                                  'bone_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'paths': {'type': 'array',
                                            'items': {'type': 'string',
                                                      'enum': ['location',
                                                               'rotation_euler',
                                                               'rotation_quaternion',
                                                               'rotation_axis_angle',
                                                               'scale']}},
                                  'key_pose': {'type': 'boolean'},
                                  'interpolation': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'required': ['armature_name', 'action_name'],
                   'additionalProperties': False},
  'contract': {'description': 'Apply/key a sampled pose from an existing rig action or pose-library marker with '
                              'preview rollback',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'apply_rig_pose_from_action',
  'order': 1000,
  'groups': ('animation', 'advanced_create', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'apply_rig_pose_marker',
  'description': 'Resolve a rig pose-library marker to the best matching source action, then apply/key it onto '
                 'matching armature controls. Use when the marker name is known but the source action may be '
                 'ambiguous. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'armature_name': {'type': 'string'},
                                  'action_name': {'type': 'string'},
                                  'pose_marker': {'type': 'string'},
                                  'target_frame': {'type': 'integer'},
                                  'frame': {'type': 'integer'},
                                  'hold_frames': {'type': 'integer'},
                                  'bone_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'paths': {'type': 'array',
                                            'items': {'type': 'string',
                                                      'enum': ['location',
                                                               'rotation_euler',
                                                               'rotation_quaternion',
                                                               'rotation_axis_angle',
                                                               'scale']}},
                                  'key_pose': {'type': 'boolean'},
                                  'interpolation': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'required': ['armature_name'],
                   'additionalProperties': False},
  'contract': {'description': 'Resolve and apply/key a named rig pose-library marker, optionally without requiring the '
                              'source action name',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'apply_rig_pose_marker',
  'order': 1010,
  'groups': ('animation', 'advanced_create', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'apply_rig_action_clip',
  'description': 'Copy an existing rig action, retime it to a target frame range, and assign the copy to an armature '
                 'without editing the source action. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'armature_name': {'type': 'string'},
                                  'action_name': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'source_frame_start': {'type': 'integer'},
                                  'source_frame_end': {'type': 'integer'},
                                  'interpolation': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'required': ['armature_name', 'action_name'],
                   'additionalProperties': False},
  'contract': {'description': 'Copy and assign an existing rig action clip to an armature with preview rollback',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'apply_rig_action_clip',
  'order': 1020,
  'groups': ('animation', 'advanced_create', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'offset_rig_limb_controls',
  'description': 'Apply small keyed offsets to named IK/FK/pole limb controls and optionally key existing space-switch '
                 'properties. Use for targeted rig contact, support, and limb-space repair after rig inspection. '
                 'Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'armature_name': {'type': 'string'},
                                  'control_offsets': {'type': 'array',
                                                      'items': {'type': 'object',
                                                                'properties': {'bone_name': {'type': 'string'},
                                                                               'location_delta': {'type': 'array',
                                                                                                  'items': {'type': 'number'},
                                                                                                  'minItems': 3,
                                                                                                  'maxItems': 3},
                                                                               'rotation_delta': {'type': 'array',
                                                                                                  'items': {'type': 'number'},
                                                                                                  'minItems': 3,
                                                                                                  'maxItems': 3},
                                                                               'scale_multiplier': {'type': 'array',
                                                                                                    'items': {'type': 'number'},
                                                                                                    'minItems': 3,
                                                                                                    'maxItems': 3}},
                                                                'required': ['bone_name'],
                                                                'additionalProperties': False}},
                                  'bone_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'location_delta': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3},
                                  'rotation_delta': {'type': 'array',
                                                     'items': {'type': 'number'},
                                                     'minItems': 3,
                                                     'maxItems': 3},
                                  'scale_multiplier': {'type': 'array',
                                                       'items': {'type': 'number'},
                                                       'minItems': 3,
                                                       'maxItems': 3},
                                  'property_targets': {'type': 'array', 'items': {'type': 'object'}},
                                  'frame': {'type': 'integer'},
                                  'hold_frames': {'type': 'integer'},
                                  'interpolation': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'required': ['armature_name', 'frame'],
                   'additionalProperties': False},
  'contract': {'description': 'Apply keyed limb-control offsets and optional space-switch keys with preview rollback',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'offset_rig_limb_controls',
  'order': 1030,
  'groups': ('animation', 'advanced_create', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'add_particle_system_to_selected',
  'description': 'Add a bounded particle system to selected mesh objects. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'count': {'type': 'integer'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'lifetime': {'type': 'number'},
                                  'particle_size': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'required': ['name'],
                   'additionalProperties': False},
  'contract': {'description': 'Add a bounded particle system to selected mesh objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_particle_system_to_selected',
  'order': 1070,
  'groups': ('advanced_create', 'simulation_setup', 'particles'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'create_basic_armature',
  'description': 'Create a simple one-bone armature object. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'rotation': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'show_in_front': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'location', 'rotation'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a simple one-bone armature object',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_basic_armature',
  'order': 1080,
  'groups': ('advanced_create', 'character', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'add_copy_transform_constraint',
  'description': 'Add a Copy Location/Rotation/Scale/Transforms constraint from selected object(s) to a target. '
                 'Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'constraint_type': {'type': 'string',
                                                      'enum': ['COPY_LOCATION',
                                                               'COPY_ROTATION',
                                                               'COPY_SCALE',
                                                               'COPY_TRANSFORMS']},
                                  'name': {'type': 'string'},
                                  'influence': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'required': ['target_name', 'constraint_type'],
                   'additionalProperties': False},
  'contract': {'description': 'Add a copy transform-style constraint to selected objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_copy_transform_constraint',
  'order': 1090,
  'groups': ('advanced_create', 'character', 'rigging'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'add_cloth_simulation_to_selected',
  'description': 'Add a bounded Cloth simulation modifier to selected or named mesh objects without baking caches. '
                 'Inspect and bake explicitly after setup. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'name': {'type': 'string'},
                                  'quality': {'type': 'integer', 'minimum': 1, 'maximum': 30},
                                  'mass': {'type': 'number'},
                                  'tension_stiffness': {'type': 'number'},
                                  'compression_stiffness': {'type': 'number'},
                                  'shear_stiffness': {'type': 'number'},
                                  'air_damping': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add a bounded Cloth simulation modifier without baking caches',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_cloth_simulation_to_selected',
  'order': 1310,
  'groups': ('advanced_create', 'simulation_setup', 'particles'),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'},
 {'name': 'add_track_to_constraint',
  'description': 'Add a Track To constraint from selected object(s) to a target object. Useful for cameras/lights '
                 'looking at a target. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'name': {'type': 'string'},
                                  'track_axis': {'type': 'string',
                                                 'enum': ['TRACK_X',
                                                          'TRACK_Y',
                                                          'TRACK_Z',
                                                          'TRACK_NEGATIVE_X',
                                                          'TRACK_NEGATIVE_Y',
                                                          'TRACK_NEGATIVE_Z']},
                                  'up_axis': {'type': 'string', 'enum': ['UP_X', 'UP_Y', 'UP_Z']},
                                  'influence': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'required': ['target_name'],
                   'additionalProperties': False},
  'contract': {'description': 'Add a Track To constraint from selected object(s) to a target object',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_track_to_constraint',
  'order': 1550,
  'groups': ('rigging',),
  'exposure': 'catalog',
  'owner': 'rigging_simulation'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import rigging_simulation

    rigging_simulation.register(handler_registry, SPECS)
