"""Canonical tool specifications for the scene editing domain."""

from __future__ import annotations

from ..registry import ToolSpec


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'set_selected_location_delta',
  'description': 'Move selected Blender objects by a delta in Blender units. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'delta': {'type': 'array',
                                            'items': {'type': 'number'},
                                            'minItems': 3,
                                            'maxItems': 3,
                                            'description': '[x, y, z] movement delta in Blender units'},
                                  'label': {'type': 'string'}},
                   'required': ['delta'],
                   'additionalProperties': False},
  'contract': {'description': 'Move selected Blender objects by a delta with rollback state',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_selected_location_delta',
  'order': 550,
  'groups': ('basic_edit',),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'select_objects',
  'description': 'Select named objects and optionally set the active object. Use before selected-object helper tools '
                 'when needed.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array',
                                                   'items': {'type': 'string'},
                                                   'description': 'Object names to select'},
                                  'active_object_name': {'type': 'string',
                                                         'description': 'Optional object to make active'},
                                  'extend': {'type': 'boolean',
                                             'description': 'Keep existing selection instead of replacing it'}},
                   'required': ['object_names'],
                   'additionalProperties': False},
  'contract': {'description': 'Select named objects and optionally set the active object', 'mutates_scene': True},
  'handler_key': 'select_objects',
  'order': 560,
  'groups': ('selection', 'basic_edit'),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'set_current_frame',
  'description': 'Set the current scene frame/playhead for inspection or preview.',
  'input_schema': {'type': 'object',
                   'properties': {'frame': {'type': 'integer'}},
                   'required': ['frame'],
                   'additionalProperties': False},
  'contract': {'description': 'Set the current scene frame/playhead', 'mutates_scene': True},
  'handler_key': 'set_current_frame',
  'order': 570,
  'groups': ('selection', 'animation'),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'set_selected_transform',
  'description': 'Set absolute transform values on selected Blender objects. Applies immediately with preview revert '
                 'support.',
  'input_schema': {'type': 'object',
                   'properties': {'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3,
                                               'description': 'Optional absolute [x, y, z] location in Blender units'},
                                  'rotation': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3,
                                               'description': 'Optional absolute Euler rotation in radians'},
                                  'scale': {'type': 'array',
                                            'items': {'type': 'number'},
                                            'minItems': 3,
                                            'maxItems': 3,
                                            'description': 'Optional absolute [x, y, z] scale'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Set absolute location, rotation, and/or scale for selected objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_selected_transform',
  'order': 580,
  'groups': ('basic_edit',),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'create_primitive',
  'description': 'Create a mesh primitive in the current scene. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'primitive_type': {'type': 'string',
                                                     'enum': ['CUBE',
                                                              'UV_SPHERE',
                                                              'ICO_SPHERE',
                                                              'CYLINDER',
                                                              'CONE',
                                                              'PLANE',
                                                              'TORUS']},
                                  'name': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'rotation': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3,
                                               'description': 'Euler rotation in radians'},
                                  'scale': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 3},
                                  'label': {'type': 'string'}},
                   'required': ['primitive_type', 'name', 'location', 'rotation', 'scale'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a mesh primitive with transform values',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_primitive',
  'order': 590,
  'groups': ('basic_edit',),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'create_collection',
  'description': 'Create or find a collection in the current scene. Applies immediately with preview revert support '
                 'for newly created collections.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'}, 'label': {'type': 'string'}},
                   'required': ['name'],
                   'additionalProperties': False},
  'contract': {'description': 'Create or find a collection in the current scene',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_collection',
  'order': 620,
  'groups': ('basic_edit',),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'link_selected_to_collection',
  'description': 'Link selected objects to a named collection without deleting existing links. Applies immediately '
                 'with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'collection_name': {'type': 'string'}, 'label': {'type': 'string'}},
                   'required': ['collection_name'],
                   'additionalProperties': False},
  'contract': {'description': 'Link selected objects to a named collection without deleting existing links',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'link_selected_to_collection',
  'order': 630,
  'groups': ('basic_edit',),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'add_modifier_to_selected',
  'description': 'Add a bounded common modifier to selected mesh objects. Supports BEVEL, SUBSURF, SOLIDIFY, and '
                 'ARRAY. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'modifier_type': {'type': 'string',
                                                    'enum': ['BEVEL', 'SUBSURF', 'SOLIDIFY', 'ARRAY']},
                                  'name': {'type': 'string'},
                                  'amount': {'type': 'number',
                                             'description': 'Width/thickness value for BEVEL or SOLIDIFY'},
                                  'segments': {'type': 'integer', 'description': 'Bevel segments'},
                                  'levels': {'type': 'integer', 'description': 'Subdivision levels'},
                                  'count': {'type': 'integer', 'description': 'Array count'},
                                  'relative_offset': {'type': 'array',
                                                      'items': {'type': 'number'},
                                                      'minItems': 3,
                                                      'maxItems': 3,
                                                      'description': 'Array relative offset [x, y, z]'},
                                  'label': {'type': 'string'}},
                   'required': ['modifier_type', 'name'],
                   'additionalProperties': False},
  'contract': {'description': 'Add a bounded common modifier to selected mesh objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_modifier_to_selected',
  'order': 640,
  'groups': ('basic_edit',),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'create_empty',
  'description': 'Create an empty helper object with transform and display settings. Applies immediately with preview '
                 'revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'rotation': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3,
                                               'description': 'Euler rotation in radians'},
                                  'scale': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 3},
                                  'empty_display_type': {'type': 'string',
                                                         'enum': ['PLAIN_AXES',
                                                                  'ARROWS',
                                                                  'SINGLE_ARROW',
                                                                  'CIRCLE',
                                                                  'CUBE',
                                                                  'SPHERE',
                                                                  'CONE',
                                                                  'IMAGE']},
                                  'empty_display_size': {'type': 'number'},
                                  'select_new': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'required': ['name'],
                   'additionalProperties': False},
  'contract': {'description': 'Create an empty helper object with transform and display settings',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_empty',
  'order': 1320,
  'groups': ('basic_edit', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'set_object_visibility',
  'description': 'Set viewport, render, or selection visibility flags for named or selected objects. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'hide_viewport': {'type': 'boolean'},
                                  'hide_render': {'type': 'boolean'},
                                  'hide_select': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Set viewport, render, or selection visibility flags for named or selected objects',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_object_visibility',
  'order': 1330,
  'groups': ('basic_edit',),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'set_object_display',
  'description': 'Set object viewport display type, name/wire/in-front flags, display color, and empty display '
                 'settings. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'display_type': {'type': 'string', 'enum': ['TEXTURED', 'SOLID', 'WIRE', 'BOUNDS']},
                                  'show_name': {'type': 'boolean'},
                                  'show_wire': {'type': 'boolean'},
                                  'show_in_front': {'type': 'boolean'},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 4},
                                  'empty_display_type': {'type': 'string',
                                                         'enum': ['PLAIN_AXES',
                                                                  'ARROWS',
                                                                  'SINGLE_ARROW',
                                                                  'CIRCLE',
                                                                  'CUBE',
                                                                  'SPHERE',
                                                                  'CONE',
                                                                  'IMAGE']},
                                  'empty_display_size': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Set object viewport display type, name/wire/in-front flags, display color, and empty '
                              'display settings',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'set_object_display',
  'order': 1340,
  'groups': ('basic_edit',),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'duplicate_selected_objects',
  'description': 'Duplicate selected objects with optional unique data, offset, animation copy, and selecting the new '
                 'duplicates. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name_prefix': {'type': 'string'},
                                  'offset': {'type': 'array',
                                             'items': {'type': 'number'},
                                             'minItems': 3,
                                             'maxItems': 3},
                                  'linked_data': {'type': 'boolean'},
                                  'copy_animation': {'type': 'boolean'},
                                  'select_new': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Duplicate selected objects with optional unique data, offset, animation copy, and '
                              'selecting the duplicates',
               'mutates_scene': True,
               'requires_live_preview': True,
               'requires_selection': True},
  'handler_key': 'duplicate_selected_objects',
  'order': 1350,
  'groups': ('basic_edit', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'parent_selected_to_empty',
  'description': "Create an empty at named or selected objects' center or a provided location, then parent those "
                 'objects to it while preserving world transforms. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'selected_only': {'type': 'boolean'},
                                  'name': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'empty_display_type': {'type': 'string',
                                                         'enum': ['PLAIN_AXES', 'ARROWS', 'CUBE', 'SPHERE']},
                                  'keep_transform': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create an empty and parent named or selected objects to it while preserving world '
                              'transforms',
               'mutates_scene': True,
               'requires_live_preview': True,
               'input_schema': {'type': 'object',
                                'properties': {'object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'selected_only': {'type': 'boolean'},
                                               'name': {'type': 'string'},
                                               'location': {'type': 'array',
                                                            'items': {'type': 'number'},
                                                            'minItems': 3,
                                                            'maxItems': 3},
                                               'empty_display_type': {'type': 'string',
                                                                      'enum': ['PLAIN_AXES',
                                                                               'ARROWS',
                                                                               'CUBE',
                                                                               'SPHERE']},
                                               'keep_transform': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'parent_selected_to_empty',
  'order': 1360,
  'groups': ('basic_edit', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'align_selected_objects',
  'description': 'Align selected object locations on one axis using the active object, min, max, center, or an '
                 'explicit value. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'mode': {'type': 'string', 'enum': ['ACTIVE', 'MIN', 'MAX', 'CENTER', 'VALUE']},
                                  'value': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Align selected object locations on one axis using active, min, max, center, or explicit '
                              'value',
               'mutates_scene': True,
               'requires_live_preview': True,
               'requires_selection': True},
  'handler_key': 'align_selected_objects',
  'order': 1370,
  'groups': ('basic_edit', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'scene_editing'},
 {'name': 'distribute_selected_objects',
  'description': 'Evenly distribute selected object locations along one axis between existing or provided start/end '
                 'positions. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'start': {'type': 'number'},
                                  'end': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Evenly distribute selected object locations along one axis',
               'mutates_scene': True,
               'requires_live_preview': True,
               'requires_selection': True},
  'handler_key': 'distribute_selected_objects',
  'order': 1380,
  'groups': ('basic_edit', 'advanced_create'),
  'exposure': 'catalog',
  'owner': 'scene_editing'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import scene_editing

    scene_editing.register(handler_registry, SPECS)
