"""Canonical tool specifications for the workflows refinement domain."""

from __future__ import annotations

from ..registry import ToolSpec


SPECS = tuple(ToolSpec(**payload) for payload in [{'name': 'plan_advanced_scene_workflow',
  'description': 'Plan a helper-first workflow for advanced 3D, 2D/storyboard, animation, simulation, asset import, '
                 'compositor/render, and script-fallback work. Does not mutate the scene.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string'},
                                  'domains': {'type': 'array',
                                              'items': {'type': 'string',
                                                        'enum': ['2d_storyboard',
                                                                 'procedural_3d',
                                                                 'advanced_animation',
                                                                 'simulation_setup',
                                                                 'asset_import',
                                                                 'compositor_render']}},
                                  'target_objects': {'type': 'array', 'items': {'type': 'string'}},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Plan helper-first workflows for advanced 3D, 2D/storyboard, animation, simulation, '
                              'asset import, compositor/render, and script-fallback work',
               'mutates_scene': False,
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'prompt': {'type': 'string'},
                                               'domains': {'type': 'array',
                                                           'items': {'type': 'string',
                                                                     'enum': ['2d_storyboard',
                                                                              'procedural_3d',
                                                                              'advanced_animation',
                                                                              'simulation_setup',
                                                                              'asset_import',
                                                                              'compositor_render']}},
                                               'target_objects': {'type': 'array', 'items': {'type': 'string'}},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'plan_advanced_scene_workflow',
  'order': 1150,
  'groups': ('animation',
             'deep_inspect',
             'advanced_create',
             'advanced_workflow',
             'two_d_storyboard',
             'procedural_3d',
             'simulation_setup',
             'geometry_nodes'),
  'exposure': 'compact_direct',
  'owner': 'workflows_refinement'},
 {'name': 'plan_object_design',
  'description': 'Map a natural-language object design brief to object family, creation strategy, bounded object-kit '
                 'arguments, helper tools, asset-reference boundaries, and script fallback policy. Use before choosing '
                 'procedural kits or custom scripts for open-ended object creation. Does not mutate the scene.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string'},
                                  'object_family': {'type': 'string',
                                                    'enum': ['',
                                                             'lighting',
                                                             'furniture',
                                                             'appliance',
                                                             'vehicle',
                                                             'architecture',
                                                             'mechanical',
                                                             'electronics',
                                                             'product_display',
                                                             'character',
                                                             'abstract_prop',
                                                             'unknown']},
                                  'target_objects': {'type': 'array', 'items': {'type': 'string'}},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Map a natural-language object design brief to object family, creation strategy, bounded '
                              'kit arguments, helper tools, asset-reference boundaries, and script fallback policy',
               'mutates_scene': False,
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'prompt': {'type': 'string'},
                                               'object_family': {'type': 'string',
                                                                 'enum': ['',
                                                                          'lighting',
                                                                          'furniture',
                                                                          'appliance',
                                                                          'vehicle',
                                                                          'architecture',
                                                                          'mechanical',
                                                                          'electronics',
                                                                          'product_display',
                                                                          'character',
                                                                          'abstract_prop',
                                                                          'unknown']},
                                               'target_objects': {'type': 'array', 'items': {'type': 'string'}},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'plan_object_design',
  'order': 1160,
  'groups': ('deep_inspect', 'advanced_create', 'advanced_workflow', 'procedural_3d'),
  'exposure': 'compact_direct',
  'owner': 'workflows_refinement'},
 {'name': 'plan_asset_import_workflow',
  'description': 'Plan the async external-asset discovery, download/cache, queued import, post-import organization, '
                 'staging, and visual-evidence workflow. Does not mutate the scene.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string'},
                                  'provider': {'type': 'string', 'enum': ['', 'poly_haven', 'sketchfab']},
                                  'asset_id': {'type': 'string'},
                                  'uid': {'type': 'string'},
                                  'target_object_name': {'type': 'string'},
                                  'presentation_preset': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Plan async external-asset discovery, download/cache, queued import, post-import '
                              'staging, and visual-evidence workflow',
               'mutates_scene': False,
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'prompt': {'type': 'string'},
                                               'provider': {'type': 'string', 'enum': ['', 'poly_haven', 'sketchfab']},
                                               'asset_id': {'type': 'string'},
                                               'uid': {'type': 'string'},
                                               'target_object_name': {'type': 'string'},
                                               'presentation_preset': {'type': 'string'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'plan_asset_import_workflow',
  'order': 1170,
  'groups': ('external_assets', 'advanced_create', 'advanced_workflow'),
  'exposure': 'compact_direct',
  'owner': 'workflows_refinement'},
 {'name': 'plan_director_workflow',
  'description': 'Plan a multi-step director workflow across inspection, optional asset import, creation, '
                 'animation/review/repair, evidence capture, and commit/revert decision points. Does not mutate the '
                 'scene.',
  'input_schema': {'type': 'object',
                   'properties': {'prompt': {'type': 'string'},
                                  'target_objects': {'type': 'array', 'items': {'type': 'string'}},
                                  'deliverables': {'type': 'array', 'items': {'type': 'string'}},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Plan a multi-step director workflow across inspection, asset import, creation, '
                              'animation/review/repair, evidence, and preview decisions',
               'mutates_scene': False,
               'supports_headless': True,
               'input_schema': {'type': 'object',
                                'properties': {'prompt': {'type': 'string'},
                                               'target_objects': {'type': 'array', 'items': {'type': 'string'}},
                                               'deliverables': {'type': 'array', 'items': {'type': 'string'}},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'plan_director_workflow',
  'order': 1180,
  'groups': ('external_assets', 'advanced_create', 'advanced_workflow'),
  'exposure': 'compact_direct',
  'owner': 'workflows_refinement'},
 {'name': 'get_2d_animation_details',
  'description': 'Inspect 2D/storyboard context: Grease Pencil-like objects, text, curves, flat mesh layers, camera, '
                 'timeline, render, and compositor status. Does not mutate the scene.',
  'input_schema': {'type': 'object', 'properties': {'max_items': {'type': 'integer'}}, 'additionalProperties': False},
  'contract': {'description': 'Inspect 2D/storyboard, Grease Pencil-like, cutout, camera, render, and compositor '
                              'context',
               'mutates_scene': False,
               'supports_headless': True},
  'handler_key': 'get_2d_animation_details',
  'order': 1190,
  'groups': ('deep_inspect', 'advanced_create', 'advanced_workflow', 'two_d_storyboard'),
  'exposure': 'compact_direct',
  'owner': 'workflows_refinement'},
 {'name': 'create_storyboard_panels',
  'description': 'Create a reversible 2D storyboard/animatic board with panel cards, borders, shot labels, frame '
                 'ranges, and optional orthographic camera. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'panel_count': {'type': 'integer', 'minimum': 1, 'maximum': 24},
                                  'columns': {'type': 'integer', 'minimum': 1, 'maximum': 24},
                                  'panel_width': {'type': 'number'},
                                  'panel_height': {'type': 'number'},
                                  'gap': {'type': 'number'},
                                  'name_prefix': {'type': 'string'},
                                  'frame_start': {'type': 'integer'},
                                  'frame_step': {'type': 'integer'},
                                  'background_color': {'type': 'array',
                                                       'items': {'type': 'number'},
                                                       'minItems': 3,
                                                       'maxItems': 4},
                                  'border_color': {'type': 'array',
                                                   'items': {'type': 'number'},
                                                   'minItems': 3,
                                                   'maxItems': 4},
                                  'text_color': {'type': 'array',
                                                 'items': {'type': 'number'},
                                                 'minItems': 3,
                                                 'maxItems': 4},
                                  'create_camera': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create reversible storyboard/animatic panels with labels and optional orthographic '
                              'camera',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_storyboard_panels',
  'order': 1200,
  'groups': ('advanced_create', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'create_2d_cutout_layer',
  'description': 'Create a flat 2D cutout layer with optional transform keyframes and label text. Use for motion '
                 'graphics, animatics, and cutout animation. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'size': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 2, 'maxItems': 2},
                                  'color': {'type': 'array', 'items': {'type': 'number'}, 'minItems': 3, 'maxItems': 4},
                                  'frame_start': {'type': 'integer'},
                                  'frame_end': {'type': 'integer'},
                                  'location_end': {'type': 'array',
                                                   'items': {'type': 'number'},
                                                   'minItems': 3,
                                                   'maxItems': 3},
                                  'rotation_end': {'type': 'array',
                                                   'items': {'type': 'number'},
                                                   'minItems': 3,
                                                   'maxItems': 3},
                                  'scale_end': {'type': 'array',
                                                'items': {'type': 'number'},
                                                'minItems': 3,
                                                'maxItems': 3},
                                  'text': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Create a reversible flat 2D cutout layer with optional transform animation',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_2d_cutout_layer',
  'order': 1210,
  'groups': ('animation', 'advanced_create', 'two_d_storyboard'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'shade_smooth_selected',
  'description': 'Shade selected mesh polygons smooth and optionally add a Weighted Normal modifier. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'add_weighted_normals': {'type': 'boolean'}, 'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Shade selected mesh polygons smooth and optionally add weighted normals',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'shade_smooth_selected',
  'order': 1390,
  'groups': ('refinement', 'vehicle', 'product', 'character', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'add_bevel_and_subsurf',
  'description': 'Add a bounded bevel, optional subdivision, and optional weighted-normal stack to selected mesh '
                 'objects. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'bevel_width': {'type': 'number'},
                                  'bevel_segments': {'type': 'integer'},
                                  'subsurf_levels': {'type': 'integer'},
                                  'weighted_normals': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Add a bounded bevel/subdivision/weighted-normal refinement stack',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_bevel_and_subsurf',
  'order': 1400,
  'groups': ('refinement', 'vehicle', 'product', 'character', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'create_wheel_assembly',
  'description': 'Create a tire and rim wheel assembly at a location. Useful for vehicle detailing. Applies '
                 'immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'name': {'type': 'string'},
                                  'location': {'type': 'array',
                                               'items': {'type': 'number'},
                                               'minItems': 3,
                                               'maxItems': 3},
                                  'radius': {'type': 'number'},
                                  'tire_thickness': {'type': 'number'},
                                  'axis': {'type': 'string', 'enum': ['X', 'Y', 'Z']},
                                  'tire_material_name': {'type': 'string'},
                                  'rim_material_name': {'type': 'string'},
                                  'label': {'type': 'string'}},
                   'required': ['name', 'location'],
                   'additionalProperties': False},
  'contract': {'description': 'Create a tire/rim wheel assembly from primitives',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'create_wheel_assembly',
  'order': 1410,
  'groups': ('vehicle',),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'add_panel_seams',
  'description': "Add simple dark curve panel seams around a target mesh object's bounds. Applies immediately with "
                 'preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'seam_material_name': {'type': 'string'},
                                  'bevel_depth': {'type': 'number'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': "Add simple curve panel seams around a mesh object's bounds",
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_panel_seams',
  'order': 1420,
  'groups': ('refinement', 'vehicle'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'apply_vehicle_refinement_template',
  'description': 'Apply a bounded vehicle detail kit around a target mesh: smoothing, bevels, wheels, window panels, '
                 'seams, headlights, and taillights. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'detail_level': {'type': 'string', 'enum': ['low', 'medium', 'high']},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Apply a bounded vehicle detail kit with wheels, windows, seams, lights, and smoothing',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'apply_vehicle_refinement_template',
  'order': 1440,
  'groups': ('vehicle',),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'apply_product_refinement_template',
  'description': 'Apply a bounded product presentation kit around a target: material polish, smoothing/bevels, '
                 'optional studio stage, dimension callouts, and optional turntable. Applies immediately with preview '
                 'revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'style': {'type': 'string', 'enum': ['studio', 'catalog', 'premium']},
                                  'include_stage': {'type': 'boolean'},
                                  'include_callouts': {'type': 'boolean'},
                                  'include_turntable': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Apply a bounded product presentation kit with material polish, smoothing, staging, '
                              'callouts, and optional turntable',
               'mutates_scene': True,
               'requires_live_preview': True,
               'output_schema': {'type': 'object',
                                 'properties': {'ok': {'type': 'boolean',
                                                       'description': 'Whether the tool completed successfully'},
                                                'message': {'type': 'string',
                                                            'description': 'Human-readable status or error message'},
                                                'created_objects': {'type': 'array', 'items': {'type': 'string'}},
                                                'lights': {'type': 'array', 'items': {'type': 'string'}},
                                                'lighting_warning': {'type': 'string',
                                                                     'description': 'Set when stacking lights onto an '
                                                                                    'already-lit scene may over-expose '
                                                                                    'the render; empty otherwise.'},
                                                'warnings': {'type': 'array', 'items': {'type': 'string'}}},
                                 'required': ['ok'],
                                 'additionalProperties': True}},
  'handler_key': 'apply_product_refinement_template',
  'order': 1450,
  'groups': ('advanced_create', 'refinement', 'product'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'apply_character_refinement_template',
  'description': 'Apply a bounded character presentation kit around a target mesh: body polish, simple head/neck/eyes, '
                 'shoulder marker, and optional gesture guides. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'character_style': {'type': 'string', 'enum': ['neutral', 'toon']},
                                  'detail_level': {'type': 'string', 'enum': ['low', 'medium', 'high']},
                                  'create_guides': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Apply a bounded character blockout/detail kit with body polish, head, eyes, shoulder '
                              'marker, and optional guides',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'apply_character_refinement_template',
  'order': 1460,
  'groups': ('advanced_create', 'refinement', 'character'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'add_dimension_callouts',
  'description': "Add non-destructive dimension/ruler callouts around a target object's bounds for width, depth, and "
                 'height. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'target_name': {'type': 'string'},
                                  'unit_label': {'type': 'string'},
                                  'include_width': {'type': 'boolean'},
                                  'include_depth': {'type': 'boolean'},
                                  'include_height': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': "Add non-destructive dimension/ruler callouts around a target object's bounds",
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'add_dimension_callouts',
  'order': 1480,
  'groups': ('advanced_create', 'refinement', 'vehicle', 'product'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'},
 {'name': 'prepare_imported_asset_presentation',
  'description': 'Organize imported asset objects, fill missing mesh materials without overwriting imported materials, '
                 'create a bounded studio/turntable presentation setup, and leave the result in preview. Use after an '
                 'external asset import job completes.',
  'input_schema': {'type': 'object',
                   'properties': {'imported_object_names': {'type': 'array', 'items': {'type': 'string'}},
                                  'target_object_name': {'type': 'string'},
                                  'selected_only': {'type': 'boolean'},
                                  'use_active_fallback': {'type': 'boolean'},
                                  'collection_prefix': {'type': 'string'},
                                  'presentation_preset': {'type': 'string',
                                                          'enum': ['studio', 'catalog', 'turntable', 'lookdev']},
                                  'assign_material_if_missing': {'type': 'boolean'},
                                  'create_stage': {'type': 'boolean'},
                                  'create_turntable': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Organize imported asset objects, fill missing mesh materials, and create a bounded '
                              'studio/turntable presentation setup after an import job completes',
               'mutates_scene': True,
               'requires_live_preview': True,
               'output_schema': {'type': 'object',
                                 'properties': {'ok': {'type': 'boolean',
                                                       'description': 'Whether the tool completed successfully'},
                                                'message': {'type': 'string',
                                                            'description': 'Human-readable status or error message'},
                                                'created_objects': {'type': 'array', 'items': {'type': 'string'}},
                                                'lights': {'type': 'array', 'items': {'type': 'string'}},
                                                'lighting_warning': {'type': 'string',
                                                                     'description': 'Set when stacking lights onto an '
                                                                                    'already-lit scene may over-expose '
                                                                                    'the render; empty otherwise.'},
                                                'warnings': {'type': 'array', 'items': {'type': 'string'}}},
                                 'required': ['ok'],
                                 'additionalProperties': True},
               'input_schema': {'type': 'object',
                                'properties': {'imported_object_names': {'type': 'array', 'items': {'type': 'string'}},
                                               'target_object_name': {'type': 'string'},
                                               'selected_only': {'type': 'boolean'},
                                               'use_active_fallback': {'type': 'boolean'},
                                               'collection_prefix': {'type': 'string'},
                                               'presentation_preset': {'type': 'string',
                                                                       'enum': ['studio',
                                                                                'catalog',
                                                                                'turntable',
                                                                                'lookdev']},
                                               'assign_material_if_missing': {'type': 'boolean'},
                                               'create_stage': {'type': 'boolean'},
                                               'create_turntable': {'type': 'boolean'},
                                               'label': {'type': 'string'}},
                                'additionalProperties': False}},
  'handler_key': 'prepare_imported_asset_presentation',
  'order': 1530,
  'groups': ('camera_render', 'external_assets', 'advanced_create', 'refinement', 'product'),
  'exposure': 'compact_direct',
  'owner': 'workflows_refinement'},
 {'name': 'organize_scene_for_production',
  'description': 'Link scene or selected objects into production-oriented type collections without deleting original '
                 'links. Applies immediately with preview revert support.',
  'input_schema': {'type': 'object',
                   'properties': {'collection_prefix': {'type': 'string'},
                                  'selected_only': {'type': 'boolean'},
                                  'label': {'type': 'string'}},
                   'additionalProperties': False},
  'contract': {'description': 'Link scene objects into production-oriented collections without deleting source links',
               'mutates_scene': True,
               'requires_live_preview': True},
  'handler_key': 'organize_scene_for_production',
  'order': 1540,
  'groups': ('advanced_create', 'refinement', 'vehicle', 'product', 'character', 'procedural_3d'),
  'exposure': 'catalog',
  'owner': 'workflows_refinement'}])


def register(registry):
    registry.register_many(SPECS)


def register_handlers(handler_registry):
    from ...tool_handlers import workflows_refinement

    workflows_refinement.register(handler_registry, SPECS)
